// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package notifydb

import (
	"context"
	"encoding/json"
	"time"
)

const notifyAlertAppendDelivery = `-- name: NotifyAlertAppendDelivery :execrows
UPDATE alert_events
SET deliveries = deliveries || jsonb_build_array($1::jsonb)
WHERE id = $2
`

type NotifyAlertAppendDeliveryParams struct {
	Delivery json.RawMessage `json:"delivery"`
	ID       string          `json:"id"`
}

// NotifyAlertAppendDelivery atomically appends one delivery record (a JSON
// object) to the deliveries array of an alert.
func (q *Queries) NotifyAlertAppendDelivery(ctx context.Context, arg NotifyAlertAppendDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, notifyAlertAppendDelivery, arg.Delivery, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const notifyAlertGet = `-- name: NotifyAlertGet :one
SELECT id, created_at, tenant_id, namespace_id, site_id, kind, severity, title, message, details, dedup_key, deliveries FROM alert_events WHERE id = $1
`

func (q *Queries) NotifyAlertGet(ctx context.Context, id string) (AlertEvent, error) {
	row := q.db.QueryRow(ctx, notifyAlertGet, id)
	var i AlertEvent
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.TenantID,
		&i.NamespaceID,
		&i.SiteID,
		&i.Kind,
		&i.Severity,
		&i.Title,
		&i.Message,
		&i.Details,
		&i.DedupKey,
		&i.Deliveries,
	)
	return i, err
}

const notifyAlertInsert = `-- name: NotifyAlertInsert :one
INSERT INTO alert_events (
    id, created_at, tenant_id, namespace_id, site_id, kind, severity, title, message, details, dedup_key
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11
)
RETURNING id, created_at, tenant_id, namespace_id, site_id, kind, severity, title, message, details, dedup_key, deliveries
`

type NotifyAlertInsertParams struct {
	ID          string          `json:"id"`
	CreatedAt   time.Time       `json:"created_at"`
	TenantID    string          `json:"tenant_id"`
	NamespaceID string          `json:"namespace_id"`
	SiteID      string          `json:"site_id"`
	Kind        string          `json:"kind"`
	Severity    string          `json:"severity"`
	Title       string          `json:"title"`
	Message     string          `json:"message"`
	Details     json.RawMessage `json:"details"`
	DedupKey    string          `json:"dedup_key"`
}

func (q *Queries) NotifyAlertInsert(ctx context.Context, arg NotifyAlertInsertParams) (AlertEvent, error) {
	row := q.db.QueryRow(ctx, notifyAlertInsert,
		arg.ID,
		arg.CreatedAt,
		arg.TenantID,
		arg.NamespaceID,
		arg.SiteID,
		arg.Kind,
		arg.Severity,
		arg.Title,
		arg.Message,
		arg.Details,
		arg.DedupKey,
	)
	var i AlertEvent
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.TenantID,
		&i.NamespaceID,
		&i.SiteID,
		&i.Kind,
		&i.Severity,
		&i.Title,
		&i.Message,
		&i.Details,
		&i.DedupKey,
		&i.Deliveries,
	)
	return i, err
}

const notifyAlertList = `-- name: NotifyAlertList :many
SELECT id, created_at, tenant_id, namespace_id, site_id, kind, severity, title, message, details, dedup_key, deliveries FROM alert_events
WHERE tenant_id = $1
  AND ((namespace_id = '' AND $2::boolean)
       OR namespace_id = ANY($3::text[])
       OR (site_id <> '' AND site_id = ANY($4::text[])))
  AND ($5::text = '' OR namespace_id = $5::text)
  AND ($6::text = '' OR site_id = $6::text)
  AND ($7::text = '' OR kind = $7::text)
  AND ($8::text = '' OR severity = $8::text)
  AND ($9::timestamptz IS NULL OR created_at >= $9::timestamptz)
  AND ($10::timestamptz IS NULL OR created_at < $10::timestamptz)
  AND ($11::timestamptz IS NULL
       OR (created_at, id) < ($11::timestamptz, $12::text))
ORDER BY created_at DESC, id DESC
LIMIT $13
`

type NotifyAlertListParams struct {
	TenantID          string     `json:"tenant_id"`
	IncludeTenant     bool       `json:"include_tenant"`
	NamespaceIds      []string   `json:"namespace_ids"`
	SiteIds           []string   `json:"site_ids"`
	FilterNamespaceID string     `json:"filter_namespace_id"`
	FilterSiteID      string     `json:"filter_site_id"`
	FilterKind        string     `json:"filter_kind"`
	FilterSeverity    string     `json:"filter_severity"`
	FromAt            *time.Time `json:"from_at"`
	ToAt              *time.Time `json:"to_at"`
	CursorAt          *time.Time `json:"cursor_at"`
	CursorID          string     `json:"cursor_id"`
	LimitRows         int32      `json:"limit_rows"`
}

// NotifyAlertList pages alert events newest first (keyset on created_at, id).
// Visibility: tenant-level alerts when include_tenant; alerts of the listed
// namespaces; alerts of the listed sites.
func (q *Queries) NotifyAlertList(ctx context.Context, arg NotifyAlertListParams) ([]AlertEvent, error) {
	rows, err := q.db.Query(ctx, notifyAlertList,
		arg.TenantID,
		arg.IncludeTenant,
		arg.NamespaceIds,
		arg.SiteIds,
		arg.FilterNamespaceID,
		arg.FilterSiteID,
		arg.FilterKind,
		arg.FilterSeverity,
		arg.FromAt,
		arg.ToAt,
		arg.CursorAt,
		arg.CursorID,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertEvent{}
	for rows.Next() {
		var i AlertEvent
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.TenantID,
			&i.NamespaceID,
			&i.SiteID,
			&i.Kind,
			&i.Severity,
			&i.Title,
			&i.Message,
			&i.Details,
			&i.DedupKey,
			&i.Deliveries,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
