// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package notifydb

import (
	"context"
	"time"
)

const notifyChannelCount = `-- name: NotifyChannelCount :one
SELECT count(*) FROM notification_channels
WHERE tenant_id = $1
  AND ((namespace_id IS NULL AND $2::boolean)
       OR namespace_id = ANY($3::text[]))
`

type NotifyChannelCountParams struct {
	TenantID      string   `json:"tenant_id"`
	IncludeTenant bool     `json:"include_tenant"`
	NamespaceIds  []string `json:"namespace_ids"`
}

func (q *Queries) NotifyChannelCount(ctx context.Context, arg NotifyChannelCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, notifyChannelCount, arg.TenantID, arg.IncludeTenant, arg.NamespaceIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const notifyChannelDelete = `-- name: NotifyChannelDelete :one
DELETE FROM notification_channels WHERE id = $1 RETURNING id, tenant_id, namespace_id, name, kind, config_ciphertext, config_wrapped_dek, config_kek_id, event_types, site_ids, min_severity, enabled, last_delivery_at, last_delivery_status, created_by, created_at, updated_at
`

func (q *Queries) NotifyChannelDelete(ctx context.Context, id string) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, notifyChannelDelete, id)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.NamespaceID,
		&i.Name,
		&i.Kind,
		&i.ConfigCiphertext,
		&i.ConfigWrappedDek,
		&i.ConfigKekID,
		&i.EventTypes,
		&i.SiteIds,
		&i.MinSeverity,
		&i.Enabled,
		&i.LastDeliveryAt,
		&i.LastDeliveryStatus,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const notifyChannelGet = `-- name: NotifyChannelGet :one
SELECT id, tenant_id, namespace_id, name, kind, config_ciphertext, config_wrapped_dek, config_kek_id, event_types, site_ids, min_severity, enabled, last_delivery_at, last_delivery_status, created_by, created_at, updated_at FROM notification_channels WHERE id = $1
`

func (q *Queries) NotifyChannelGet(ctx context.Context, id string) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, notifyChannelGet, id)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.NamespaceID,
		&i.Name,
		&i.Kind,
		&i.ConfigCiphertext,
		&i.ConfigWrappedDek,
		&i.ConfigKekID,
		&i.EventTypes,
		&i.SiteIds,
		&i.MinSeverity,
		&i.Enabled,
		&i.LastDeliveryAt,
		&i.LastDeliveryStatus,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const notifyChannelGetForUpdate = `-- name: NotifyChannelGetForUpdate :one
SELECT id, tenant_id, namespace_id, name, kind, config_ciphertext, config_wrapped_dek, config_kek_id, event_types, site_ids, min_severity, enabled, last_delivery_at, last_delivery_status, created_by, created_at, updated_at FROM notification_channels WHERE id = $1 FOR UPDATE
`

func (q *Queries) NotifyChannelGetForUpdate(ctx context.Context, id string) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, notifyChannelGetForUpdate, id)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.NamespaceID,
		&i.Name,
		&i.Kind,
		&i.ConfigCiphertext,
		&i.ConfigWrappedDek,
		&i.ConfigKekID,
		&i.EventTypes,
		&i.SiteIds,
		&i.MinSeverity,
		&i.Enabled,
		&i.LastDeliveryAt,
		&i.LastDeliveryStatus,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const notifyChannelInsert = `-- name: NotifyChannelInsert :one
INSERT INTO notification_channels (
    id, tenant_id, namespace_id, name, kind,
    config_ciphertext, config_wrapped_dek, config_kek_id,
    event_types, site_ids, min_severity, enabled, created_by
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9::text[], $10::text[], $11, $12, $13
)
RETURNING id, tenant_id, namespace_id, name, kind, config_ciphertext, config_wrapped_dek, config_kek_id, event_types, site_ids, min_severity, enabled, last_delivery_at, last_delivery_status, created_by, created_at, updated_at
`

type NotifyChannelInsertParams struct {
	ID               string   `json:"id"`
	TenantID         string   `json:"tenant_id"`
	NamespaceID      *string  `json:"namespace_id"`
	Name             string   `json:"name"`
	Kind             string   `json:"kind"`
	ConfigCiphertext []byte   `json:"config_ciphertext"`
	ConfigWrappedDek []byte   `json:"config_wrapped_dek"`
	ConfigKekID      string   `json:"config_kek_id"`
	EventTypes       []string `json:"event_types"`
	SiteIds          []string `json:"site_ids"`
	MinSeverity      string   `json:"min_severity"`
	Enabled          bool     `json:"enabled"`
	CreatedBy        string   `json:"created_by"`
}

func (q *Queries) NotifyChannelInsert(ctx context.Context, arg NotifyChannelInsertParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, notifyChannelInsert,
		arg.ID,
		arg.TenantID,
		arg.NamespaceID,
		arg.Name,
		arg.Kind,
		arg.ConfigCiphertext,
		arg.ConfigWrappedDek,
		arg.ConfigKekID,
		arg.EventTypes,
		arg.SiteIds,
		arg.MinSeverity,
		arg.Enabled,
		arg.CreatedBy,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.NamespaceID,
		&i.Name,
		&i.Kind,
		&i.ConfigCiphertext,
		&i.ConfigWrappedDek,
		&i.ConfigKekID,
		&i.EventTypes,
		&i.SiteIds,
		&i.MinSeverity,
		&i.Enabled,
		&i.LastDeliveryAt,
		&i.LastDeliveryStatus,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const notifyChannelList = `-- name: NotifyChannelList :many
SELECT id, tenant_id, namespace_id, name, kind, config_ciphertext, config_wrapped_dek, config_kek_id, event_types, site_ids, min_severity, enabled, last_delivery_at, last_delivery_status, created_by, created_at, updated_at FROM notification_channels
WHERE tenant_id = $1
  AND ((namespace_id IS NULL AND $2::boolean)
       OR namespace_id = ANY($3::text[]))
  AND name > $4
ORDER BY name
LIMIT $5
`

type NotifyChannelListParams struct {
	TenantID      string   `json:"tenant_id"`
	IncludeTenant bool     `json:"include_tenant"`
	NamespaceIds  []string `json:"namespace_ids"`
	AfterName     string   `json:"after_name"`
	LimitRows     int32    `json:"limit_rows"`
}

// NotifyChannelList pages the channels of a tenant ordered by name. Tenant-wide
// channels are included when include_tenant is true; namespace channels when
// their namespace is listed in namespace_ids.
func (q *Queries) NotifyChannelList(ctx context.Context, arg NotifyChannelListParams) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, notifyChannelList,
		arg.TenantID,
		arg.IncludeTenant,
		arg.NamespaceIds,
		arg.AfterName,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.NamespaceID,
			&i.Name,
			&i.Kind,
			&i.ConfigCiphertext,
			&i.ConfigWrappedDek,
			&i.ConfigKekID,
			&i.EventTypes,
			&i.SiteIds,
			&i.MinSeverity,
			&i.Enabled,
			&i.LastDeliveryAt,
			&i.LastDeliveryStatus,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notifyChannelListEnabled = `-- name: NotifyChannelListEnabled :many
SELECT id, tenant_id, namespace_id, name, kind, config_ciphertext, config_wrapped_dek, config_kek_id, event_types, site_ids, min_severity, enabled, last_delivery_at, last_delivery_status, created_by, created_at, updated_at FROM notification_channels
WHERE tenant_id = $1 AND enabled
ORDER BY id
LIMIT $2
`

type NotifyChannelListEnabledParams struct {
	TenantID  string `json:"tenant_id"`
	LimitRows int32  `json:"limit_rows"`
}

// NotifyChannelListEnabled returns the enabled channels of a tenant, bounded
// by limit_rows, for alert matching.
func (q *Queries) NotifyChannelListEnabled(ctx context.Context, arg NotifyChannelListEnabledParams) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, notifyChannelListEnabled, arg.TenantID, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.NamespaceID,
			&i.Name,
			&i.Kind,
			&i.ConfigCiphertext,
			&i.ConfigWrappedDek,
			&i.ConfigKekID,
			&i.EventTypes,
			&i.SiteIds,
			&i.MinSeverity,
			&i.Enabled,
			&i.LastDeliveryAt,
			&i.LastDeliveryStatus,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notifyChannelSetDelivery = `-- name: NotifyChannelSetDelivery :exec
UPDATE notification_channels
SET last_delivery_at = $1,
    last_delivery_status = $2
WHERE id = $3
`

type NotifyChannelSetDeliveryParams struct {
	DeliveredAt *time.Time `json:"delivered_at"`
	Status      string     `json:"status"`
	ID          string     `json:"id"`
}

func (q *Queries) NotifyChannelSetDelivery(ctx context.Context, arg NotifyChannelSetDeliveryParams) error {
	_, err := q.db.Exec(ctx, notifyChannelSetDelivery, arg.DeliveredAt, arg.Status, arg.ID)
	return err
}

const notifyChannelUpdate = `-- name: NotifyChannelUpdate :one
UPDATE notification_channels
SET name = $1,
    config_ciphertext = $2,
    config_wrapped_dek = $3,
    config_kek_id = $4,
    event_types = $5::text[],
    site_ids = $6::text[],
    min_severity = $7,
    enabled = $8,
    updated_at = now()
WHERE id = $9
RETURNING id, tenant_id, namespace_id, name, kind, config_ciphertext, config_wrapped_dek, config_kek_id, event_types, site_ids, min_severity, enabled, last_delivery_at, last_delivery_status, created_by, created_at, updated_at
`

type NotifyChannelUpdateParams struct {
	Name             string   `json:"name"`
	ConfigCiphertext []byte   `json:"config_ciphertext"`
	ConfigWrappedDek []byte   `json:"config_wrapped_dek"`
	ConfigKekID      string   `json:"config_kek_id"`
	EventTypes       []string `json:"event_types"`
	SiteIds          []string `json:"site_ids"`
	MinSeverity      string   `json:"min_severity"`
	Enabled          bool     `json:"enabled"`
	ID               string   `json:"id"`
}

func (q *Queries) NotifyChannelUpdate(ctx context.Context, arg NotifyChannelUpdateParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, notifyChannelUpdate,
		arg.Name,
		arg.ConfigCiphertext,
		arg.ConfigWrappedDek,
		arg.ConfigKekID,
		arg.EventTypes,
		arg.SiteIds,
		arg.MinSeverity,
		arg.Enabled,
		arg.ID,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.NamespaceID,
		&i.Name,
		&i.Kind,
		&i.ConfigCiphertext,
		&i.ConfigWrappedDek,
		&i.ConfigKekID,
		&i.EventTypes,
		&i.SiteIds,
		&i.MinSeverity,
		&i.Enabled,
		&i.LastDeliveryAt,
		&i.LastDeliveryStatus,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const notifyTenantsSubscribed = `-- name: NotifyTenantsSubscribed :many
SELECT DISTINCT tenant_id FROM notification_channels
WHERE enabled
  AND (cardinality(event_types) = 0 OR $1::text = ANY(event_types))
ORDER BY tenant_id
LIMIT $2
`

type NotifyTenantsSubscribedParams struct {
	Kind      string `json:"kind"`
	LimitRows int32  `json:"limit_rows"`
}

// NotifyTenantsSubscribed lists tenants having at least one enabled channel
// subscribed to an alert kind (an empty subscription list means every kind).
func (q *Queries) NotifyTenantsSubscribed(ctx context.Context, arg NotifyTenantsSubscribedParams) ([]string, error) {
	rows, err := q.db.Query(ctx, notifyTenantsSubscribed, arg.Kind, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tenant_id string
		if err := rows.Scan(&tenant_id); err != nil {
			return nil, err
		}
		items = append(items, tenant_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
