// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: evaluate.sql

package notifydb

import (
	"context"
	"time"
)

const notifyBanCounts = `-- name: NotifyBanCounts :many
SELECT tenant_id, namespace_id, site_id, count(*)::bigint AS bans
FROM state_events
WHERE namespace_id = ANY($1::text[])
  AND created_at >= $2
  AND created_at < $3
  AND action = 'ban'
  AND NOT shadow
  AND site_id <> ''
GROUP BY tenant_id, namespace_id, site_id
`

type NotifyBanCountsParams struct {
	NamespaceIds []string  `json:"namespace_ids"`
	FromAt       time.Time `json:"from_at"`
	ToAt         time.Time `json:"to_at"`
}

type NotifyBanCountsRow struct {
	TenantID    string `json:"tenant_id"`
	NamespaceID string `json:"namespace_id"`
	SiteID      string `json:"site_id"`
	Bans        int64  `json:"bans"`
}

// NotifyBanCounts counts enforced ban state events per site in
// [from_at, to_at) for the listed namespaces (served by the
// (namespace_id, created_at) index).
func (q *Queries) NotifyBanCounts(ctx context.Context, arg NotifyBanCountsParams) ([]NotifyBanCountsRow, error) {
	rows, err := q.db.Query(ctx, notifyBanCounts, arg.NamespaceIds, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotifyBanCountsRow{}
	for rows.Next() {
		var i NotifyBanCountsRow
		if err := rows.Scan(
			&i.TenantID,
			&i.NamespaceID,
			&i.SiteID,
			&i.Bans,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notifyIdentityRef = `-- name: NotifyIdentityRef :one
SELECT id, site_id, client, type_id FROM identities WHERE id = $1
`

type NotifyIdentityRefRow struct {
	ID     string `json:"id"`
	SiteID string `json:"site_id"`
	Client string `json:"client"`
	TypeID string `json:"type_id"`
}

func (q *Queries) NotifyIdentityRef(ctx context.Context, id string) (NotifyIdentityRefRow, error) {
	row := q.db.QueryRow(ctx, notifyIdentityRef, id)
	var i NotifyIdentityRefRow
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Client,
		&i.TypeID,
	)
	return i, err
}

const notifyOutcomeTotals = `-- name: NotifyOutcomeTotals :many
SELECT namespace_id,
       site_id,
       sum(count)::bigint AS total,
       (coalesce(sum(count) FILTER (WHERE outcome = 'unknown'), 0))::bigint AS unknown,
       (coalesce(sum(count) FILTER (WHERE outcome = 'client_error'), 0))::bigint AS client_error
FROM outcome_stats_minutely
WHERE bucket >= $1
GROUP BY namespace_id, site_id
ORDER BY namespace_id, site_id
`

type NotifyOutcomeTotalsRow struct {
	NamespaceID string `json:"namespace_id"`
	SiteID      string `json:"site_id"`
	Total       int64  `json:"total"`
	Unknown     int64  `json:"unknown"`
	ClientError int64  `json:"client_error"`
}

// NotifyOutcomeTotals sums per-site outcome counts from from_at on.
func (q *Queries) NotifyOutcomeTotals(ctx context.Context, fromAt time.Time) ([]NotifyOutcomeTotalsRow, error) {
	rows, err := q.db.Query(ctx, notifyOutcomeTotals, fromAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotifyOutcomeTotalsRow{}
	for rows.Next() {
		var i NotifyOutcomeTotalsRow
		if err := rows.Scan(
			&i.NamespaceID,
			&i.SiteID,
			&i.Total,
			&i.Unknown,
			&i.ClientError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notifyProxyStateCounts = `-- name: NotifyProxyStateCounts :many
SELECT n.tenant_id,
       p.namespace_id,
       count(*) FILTER (WHERE p.state <> 'retired')::bigint AS total,
       count(*) FILTER (WHERE p.state = 'active')::bigint AS active,
       count(*) FILTER (WHERE p.state = 'dead')::bigint AS dead
FROM proxies p
JOIN namespaces n ON n.id = p.namespace_id
GROUP BY n.tenant_id, p.namespace_id
ORDER BY p.namespace_id
`

type NotifyProxyStateCountsRow struct {
	TenantID    string `json:"tenant_id"`
	NamespaceID string `json:"namespace_id"`
	Total       int64  `json:"total"`
	Active      int64  `json:"active"`
	Dead        int64  `json:"dead"`
}

// NotifyProxyStateCounts counts proxies per namespace: all non-retired
// proxies, active ones and dead ones.
func (q *Queries) NotifyProxyStateCounts(ctx context.Context) ([]NotifyProxyStateCountsRow, error) {
	rows, err := q.db.Query(ctx, notifyProxyStateCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotifyProxyStateCountsRow{}
	for rows.Next() {
		var i NotifyProxyStateCountsRow
		if err := rows.Scan(
			&i.TenantID,
			&i.NamespaceID,
			&i.Total,
			&i.Active,
			&i.Dead,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notifySecretsExpiring = `-- name: NotifySecretsExpiring :many
SELECT s.id, s.namespace_id, n.tenant_id, s.path, s.expires_at::timestamptz AS expires_at
FROM secrets s
JOIN namespaces n ON n.id = s.namespace_id
WHERE s.expires_at IS NOT NULL
  AND s.expires_at >= $1::timestamptz
  AND s.expires_at <= $2::timestamptz
ORDER BY s.expires_at, s.id
LIMIT $3
`

type NotifySecretsExpiringParams struct {
	FromAt    time.Time `json:"from_at"`
	ToAt      time.Time `json:"to_at"`
	LimitRows int32     `json:"limit_rows"`
}

type NotifySecretsExpiringRow struct {
	ID          string    `json:"id"`
	NamespaceID string    `json:"namespace_id"`
	TenantID    string    `json:"tenant_id"`
	Path        string    `json:"path"`
	ExpiresAt   time.Time `json:"expires_at"`
}

// NotifySecretsExpiring lists secrets whose expiry lies in [from_at, to_at].
func (q *Queries) NotifySecretsExpiring(ctx context.Context, arg NotifySecretsExpiringParams) ([]NotifySecretsExpiringRow, error) {
	rows, err := q.db.Query(ctx, notifySecretsExpiring, arg.FromAt, arg.ToAt, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotifySecretsExpiringRow{}
	for rows.Next() {
		var i NotifySecretsExpiringRow
		if err := rows.Scan(
			&i.ID,
			&i.NamespaceID,
			&i.TenantID,
			&i.Path,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notifyTenantName = `-- name: NotifyTenantName :one
SELECT name FROM tenants WHERE id = $1
`

func (q *Queries) NotifyTenantName(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, notifyTenantName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}
