// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity_expired.sql

package notifydb

import (
	"context"
	"encoding/json"
	"time"
)

const notifyExpiredIdentityEvents = `-- name: NotifyExpiredIdentityEvents :many
SELECT id, created_at, tenant_id, namespace_id, site_id, subject_id, from_state, reason
FROM state_events
WHERE action = 'expire'
  AND created_at >= $1::timestamptz
  AND (created_at, id) > ($1::timestamptz, $2::text)
  AND subject_kind = 'identity'
  AND to_state = 'expired'
  AND from_state <> 'expired'
  AND NOT shadow
ORDER BY created_at, id
LIMIT $3
`

type NotifyExpiredIdentityEventsParams struct {
	AfterAt   time.Time `json:"after_at"`
	AfterID   string    `json:"after_id"`
	LimitRows int32     `json:"limit_rows"`
}

type NotifyExpiredIdentityEventsRow struct {
	ID          string    `json:"id"`
	CreatedAt   time.Time `json:"created_at"`
	TenantID    string    `json:"tenant_id"`
	NamespaceID string    `json:"namespace_id"`
	SiteID      string    `json:"site_id"`
	SubjectID   string    `json:"subject_id"`
	FromState   string    `json:"from_state"`
	Reason      string    `json:"reason"`
}

// NotifyExpiredIdentityEvents pages the enforced transitions of identities to
// "expired" in (created_at, id) order, strictly after the keyset position
// (after_at, after_id). Served by the (action, created_at) index; all such
// transitions are recorded with action "expire".
func (q *Queries) NotifyExpiredIdentityEvents(ctx context.Context, arg NotifyExpiredIdentityEventsParams) ([]NotifyExpiredIdentityEventsRow, error) {
	rows, err := q.db.Query(ctx, notifyExpiredIdentityEvents, arg.AfterAt, arg.AfterID, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotifyExpiredIdentityEventsRow{}
	for rows.Next() {
		var i NotifyExpiredIdentityEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.TenantID,
			&i.NamespaceID,
			&i.SiteID,
			&i.SubjectID,
			&i.FromState,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notifyIdentityRefs = `-- name: NotifyIdentityRefs :many
SELECT id, site_id, client, type_id FROM identities WHERE id = ANY($1::text[])
`

type NotifyIdentityRefsRow struct {
	ID     string `json:"id"`
	SiteID string `json:"site_id"`
	Client string `json:"client"`
	TypeID string `json:"type_id"`
}

func (q *Queries) NotifyIdentityRefs(ctx context.Context, ids []string) ([]NotifyIdentityRefsRow, error) {
	rows, err := q.db.Query(ctx, notifyIdentityRefs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotifyIdentityRefsRow{}
	for rows.Next() {
		var i NotifyIdentityRefsRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Client,
			&i.TypeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notifySettingGet = `-- name: NotifySettingGet :one
SELECT value FROM system_settings WHERE key = $1
`

func (q *Queries) NotifySettingGet(ctx context.Context, key string) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, notifySettingGet, key)
	var value json.RawMessage
	err := row.Scan(&value)
	return value, err
}

const notifySettingPut = `-- name: NotifySettingPut :exec
INSERT INTO system_settings (key, value, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now()
`

type NotifySettingPutParams struct {
	Key   string          `json:"key"`
	Value json.RawMessage `json:"value"`
}

func (q *Queries) NotifySettingPut(ctx context.Context, arg NotifySettingPutParams) error {
	_, err := q.db.Exec(ctx, notifySettingPut, arg.Key, arg.Value)
	return err
}
