// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package catalogdb

import (
	"context"
	"encoding/json"
)

const catalogGetNamespace = `-- name: CatalogGetNamespace :one
SELECT n.id, n.tenant_id, t.name AS tenant_name, n.name, n.display_name
FROM namespaces n
JOIN tenants t ON t.id = n.tenant_id
WHERE n.id = $1
`

type CatalogGetNamespaceRow struct {
	ID          string `json:"id"`
	TenantID    string `json:"tenant_id"`
	TenantName  string `json:"tenant_name"`
	Name        string `json:"name"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) CatalogGetNamespace(ctx context.Context, id string) (CatalogGetNamespaceRow, error) {
	row := q.db.QueryRow(ctx, catalogGetNamespace, id)
	var i CatalogGetNamespaceRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TenantName,
		&i.Name,
		&i.DisplayName,
	)
	return i, err
}

const catalogListEndpointGroups = `-- name: CatalogListEndpointGroups :many
SELECT eg.id, eg.hkey, eg.site_id, eg.client, eg.name, eg.low_watermark
FROM endpoint_groups eg
JOIN sites s ON s.id = eg.site_id
WHERE s.namespace_id = $1
ORDER BY eg.site_id, eg.client, eg.name
`

type CatalogListEndpointGroupsRow struct {
	ID           string `json:"id"`
	Hkey         int64  `json:"hkey"`
	SiteID       string `json:"site_id"`
	Client       string `json:"client"`
	Name         string `json:"name"`
	LowWatermark int32  `json:"low_watermark"`
}

func (q *Queries) CatalogListEndpointGroups(ctx context.Context, namespaceID string) ([]CatalogListEndpointGroupsRow, error) {
	rows, err := q.db.Query(ctx, catalogListEndpointGroups, namespaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogListEndpointGroupsRow{}
	for rows.Next() {
		var i CatalogListEndpointGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Hkey,
			&i.SiteID,
			&i.Client,
			&i.Name,
			&i.LowWatermark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogListIdentityTypes = `-- name: CatalogListIdentityTypes :many
SELECT it.id, it.site_id, it.client, it.name, it.spec, it.version
FROM identity_types it
JOIN sites s ON s.id = it.site_id
WHERE s.namespace_id = $1
ORDER BY it.site_id, it.name
`

type CatalogListIdentityTypesRow struct {
	ID      string          `json:"id"`
	SiteID  string          `json:"site_id"`
	Client  string          `json:"client"`
	Name    string          `json:"name"`
	Spec    json.RawMessage `json:"spec"`
	Version int32           `json:"version"`
}

func (q *Queries) CatalogListIdentityTypes(ctx context.Context, namespaceID string) ([]CatalogListIdentityTypesRow, error) {
	rows, err := q.db.Query(ctx, catalogListIdentityTypes, namespaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogListIdentityTypesRow{}
	for rows.Next() {
		var i CatalogListIdentityTypesRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Client,
			&i.Name,
			&i.Spec,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogListNamespaceIDs = `-- name: CatalogListNamespaceIDs :many

SELECT id
FROM namespaces
ORDER BY id
`

// Read-only queries that load one namespace snapshot. They run inside a single
// REPEATABLE READ, READ ONLY transaction so that every row belongs to the same
// database snapshot.
func (q *Queries) CatalogListNamespaceIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, catalogListNamespaceIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogListPolicyBindings = `-- name: CatalogListPolicyBindings :many
SELECT id, policy_id, kind, site_id, client, endpoint_group_id
FROM policy_bindings
WHERE namespace_id = $1
ORDER BY created_at, id
`

type CatalogListPolicyBindingsRow struct {
	ID              string  `json:"id"`
	PolicyID        string  `json:"policy_id"`
	Kind            string  `json:"kind"`
	SiteID          *string `json:"site_id"`
	Client          *string `json:"client"`
	EndpointGroupID *string `json:"endpoint_group_id"`
}

func (q *Queries) CatalogListPolicyBindings(ctx context.Context, namespaceID string) ([]CatalogListPolicyBindingsRow, error) {
	rows, err := q.db.Query(ctx, catalogListPolicyBindings, namespaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogListPolicyBindingsRow{}
	for rows.Next() {
		var i CatalogListPolicyBindingsRow
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.Kind,
			&i.SiteID,
			&i.Client,
			&i.EndpointGroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogListPublishedPolicies = `-- name: CatalogListPublishedPolicies :many
SELECT p.id, p.kind, p.name, p.current_version, v.spec
FROM policies p
JOIN policy_versions v ON v.policy_id = p.id AND v.version = p.current_version
WHERE p.namespace_id = $1
  AND p.current_version > 0
ORDER BY p.kind, p.name
`

type CatalogListPublishedPoliciesRow struct {
	ID             string          `json:"id"`
	Kind           string          `json:"kind"`
	Name           string          `json:"name"`
	CurrentVersion int32           `json:"current_version"`
	Spec           json.RawMessage `json:"spec"`
}

// CatalogListPublishedPolicies returns every policy of the namespace that has
// a published version, with the spec of that version.
func (q *Queries) CatalogListPublishedPolicies(ctx context.Context, namespaceID string) ([]CatalogListPublishedPoliciesRow, error) {
	rows, err := q.db.Query(ctx, catalogListPublishedPolicies, namespaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogListPublishedPoliciesRow{}
	for rows.Next() {
		var i CatalogListPublishedPoliciesRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.CurrentVersion,
			&i.Spec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogListSites = `-- name: CatalogListSites :many
SELECT id, hkey, name, display_name, clients, paused, paused_reason
FROM sites
WHERE namespace_id = $1
ORDER BY name
`

type CatalogListSitesRow struct {
	ID           string   `json:"id"`
	Hkey         int64    `json:"hkey"`
	Name         string   `json:"name"`
	DisplayName  string   `json:"display_name"`
	Clients      []string `json:"clients"`
	Paused       bool     `json:"paused"`
	PausedReason string   `json:"paused_reason"`
}

func (q *Queries) CatalogListSites(ctx context.Context, namespaceID string) ([]CatalogListSitesRow, error) {
	rows, err := q.db.Query(ctx, catalogListSites, namespaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogListSitesRow{}
	for rows.Next() {
		var i CatalogListSitesRow
		if err := rows.Scan(
			&i.ID,
			&i.Hkey,
			&i.Name,
			&i.DisplayName,
			&i.Clients,
			&i.Paused,
			&i.PausedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogListURIRules = `-- name: CatalogListURIRules :many
SELECT r.id, r.endpoint_group_id, r.kind, r.pattern, r.position
FROM uri_rules r
JOIN endpoint_groups eg ON eg.id = r.endpoint_group_id
JOIN sites s ON s.id = eg.site_id
WHERE s.namespace_id = $1
ORDER BY r.endpoint_group_id, r.position, r.id
`

type CatalogListURIRulesRow struct {
	ID              string `json:"id"`
	EndpointGroupID string `json:"endpoint_group_id"`
	Kind            string `json:"kind"`
	Pattern         string `json:"pattern"`
	Position        int32  `json:"position"`
}

func (q *Queries) CatalogListURIRules(ctx context.Context, namespaceID string) ([]CatalogListURIRulesRow, error) {
	rows, err := q.db.Query(ctx, catalogListURIRules, namespaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogListURIRulesRow{}
	for rows.Next() {
		var i CatalogListURIRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.EndpointGroupID,
			&i.Kind,
			&i.Pattern,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
