// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: breaker.sql

package breakerdb

import (
	"context"
	"encoding/json"
	"time"
)

const breakerGroupsByKeys = `-- name: BreakerGroupsByKeys :many
SELECT eg.hkey, eg.id, eg.site_id, eg.client, eg.name
FROM endpoint_groups eg
JOIN sites s ON s.id = eg.site_id
WHERE s.namespace_id = $1
  AND eg.hkey = ANY ($2::bigint[])
`

type BreakerGroupsByKeysParams struct {
	NamespaceID string  `json:"namespace_id"`
	Hkeys       []int64 `json:"hkeys"`
}

type BreakerGroupsByKeysRow struct {
	Hkey   int64  `json:"hkey"`
	ID     string `json:"id"`
	SiteID string `json:"site_id"`
	Client string `json:"client"`
	Name   string `json:"name"`
}

func (q *Queries) BreakerGroupsByKeys(ctx context.Context, arg BreakerGroupsByKeysParams) ([]BreakerGroupsByKeysRow, error) {
	rows, err := q.db.Query(ctx, breakerGroupsByKeys, arg.NamespaceID, arg.Hkeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BreakerGroupsByKeysRow{}
	for rows.Next() {
		var i BreakerGroupsByKeysRow
		if err := rows.Scan(
			&i.Hkey,
			&i.ID,
			&i.SiteID,
			&i.Client,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const breakerInsertEvent = `-- name: BreakerInsertEvent :exec
INSERT INTO breaker_events (
    id, created_at, tenant_id, namespace_id, site_id, endpoint_group_id,
    from_state, to_state, trigger, reason, open_until, metrics, actor
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12, $13
)
`

type BreakerInsertEventParams struct {
	ID              string          `json:"id"`
	CreatedAt       time.Time       `json:"created_at"`
	TenantID        string          `json:"tenant_id"`
	NamespaceID     string          `json:"namespace_id"`
	SiteID          string          `json:"site_id"`
	EndpointGroupID string          `json:"endpoint_group_id"`
	FromState       string          `json:"from_state"`
	ToState         string          `json:"to_state"`
	Trigger         string          `json:"trigger"`
	Reason          string          `json:"reason"`
	OpenUntil       *time.Time      `json:"open_until"`
	Metrics         json.RawMessage `json:"metrics"`
	Actor           string          `json:"actor"`
}

// Records one breaker transition or site switch (query names are prefixed
// with "Breaker" to stay globally unique across private sqlc packages).
func (q *Queries) BreakerInsertEvent(ctx context.Context, arg BreakerInsertEventParams) error {
	_, err := q.db.Exec(ctx, breakerInsertEvent,
		arg.ID,
		arg.CreatedAt,
		arg.TenantID,
		arg.NamespaceID,
		arg.SiteID,
		arg.EndpointGroupID,
		arg.FromState,
		arg.ToState,
		arg.Trigger,
		arg.Reason,
		arg.OpenUntil,
		arg.Metrics,
		arg.Actor,
	)
	return err
}

const breakerListEvents = `-- name: BreakerListEvents :many
SELECT be.id,
       be.created_at,
       be.site_id,
       be.endpoint_group_id,
       be.from_state,
       be.to_state,
       be.trigger,
       be.reason,
       be.open_until,
       be.metrics,
       be.actor,
       COALESCE(s.name, '')::text    AS site_name,
       COALESCE(eg.name, '')::text   AS endpoint_group_name,
       COALESCE(eg.client, '')::text AS client
FROM breaker_events be
LEFT JOIN sites s ON s.id = be.site_id
LEFT JOIN endpoint_groups eg ON eg.id = be.endpoint_group_id
WHERE be.namespace_id = $1
  AND ($2::boolean OR be.site_id = ANY ($3::text[]))
  AND ($4::text IS NULL OR be.site_id = $4::text)
  AND ($5::text IS NULL OR be.endpoint_group_id = $5::text)
  AND ($6::text IS NULL OR be.trigger = $6::text)
  AND ($7::timestamptz IS NULL OR be.created_at >= $7::timestamptz)
  AND ($8::timestamptz IS NULL OR be.created_at < $8::timestamptz)
  AND ($9::timestamptz IS NULL
       OR (be.created_at, be.id) < ($9::timestamptz, $10::text))
ORDER BY be.created_at DESC, be.id DESC
LIMIT $11
`

type BreakerListEventsParams struct {
	NamespaceID     string     `json:"namespace_id"`
	AllSites        bool       `json:"all_sites"`
	SiteIds         []string   `json:"site_ids"`
	SiteID          *string    `json:"site_id"`
	EndpointGroupID *string    `json:"endpoint_group_id"`
	TriggerFilter   *string    `json:"trigger_filter"`
	StartAt         *time.Time `json:"start_at"`
	EndAt           *time.Time `json:"end_at"`
	CursorAt        *time.Time `json:"cursor_at"`
	CursorID        string     `json:"cursor_id"`
	PageLimit       int32      `json:"page_limit"`
}

type BreakerListEventsRow struct {
	ID                string          `json:"id"`
	CreatedAt         time.Time       `json:"created_at"`
	SiteID            string          `json:"site_id"`
	EndpointGroupID   string          `json:"endpoint_group_id"`
	FromState         string          `json:"from_state"`
	ToState           string          `json:"to_state"`
	Trigger           string          `json:"trigger"`
	Reason            string          `json:"reason"`
	OpenUntil         *time.Time      `json:"open_until"`
	Metrics           json.RawMessage `json:"metrics"`
	Actor             string          `json:"actor"`
	SiteName          string          `json:"site_name"`
	EndpointGroupName string          `json:"endpoint_group_name"`
	Client            string          `json:"client"`
}

// Keyset pagination over (created_at DESC, id DESC). Site restriction: when
// all_sites is false only rows of site_ids are returned.
func (q *Queries) BreakerListEvents(ctx context.Context, arg BreakerListEventsParams) ([]BreakerListEventsRow, error) {
	rows, err := q.db.Query(ctx, breakerListEvents,
		arg.NamespaceID,
		arg.AllSites,
		arg.SiteIds,
		arg.SiteID,
		arg.EndpointGroupID,
		arg.TriggerFilter,
		arg.StartAt,
		arg.EndAt,
		arg.CursorAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BreakerListEventsRow{}
	for rows.Next() {
		var i BreakerListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.SiteID,
			&i.EndpointGroupID,
			&i.FromState,
			&i.ToState,
			&i.Trigger,
			&i.Reason,
			&i.OpenUntil,
			&i.Metrics,
			&i.Actor,
			&i.SiteName,
			&i.EndpointGroupName,
			&i.Client,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const breakerLockSite = `-- name: BreakerLockSite :one
SELECT paused, paused_reason, paused_at, paused_by
FROM sites
WHERE id = $1 AND namespace_id = $2
FOR UPDATE
`

type BreakerLockSiteParams struct {
	ID          string `json:"id"`
	NamespaceID string `json:"namespace_id"`
}

type BreakerLockSiteRow struct {
	Paused       bool       `json:"paused"`
	PausedReason string     `json:"paused_reason"`
	PausedAt     *time.Time `json:"paused_at"`
	PausedBy     string     `json:"paused_by"`
}

func (q *Queries) BreakerLockSite(ctx context.Context, arg BreakerLockSiteParams) (BreakerLockSiteRow, error) {
	row := q.db.QueryRow(ctx, breakerLockSite, arg.ID, arg.NamespaceID)
	var i BreakerLockSiteRow
	err := row.Scan(
		&i.Paused,
		&i.PausedReason,
		&i.PausedAt,
		&i.PausedBy,
	)
	return i, err
}

const breakerNamespace = `-- name: BreakerNamespace :one
SELECT id, tenant_id, name
FROM namespaces
WHERE id = $1
`

type BreakerNamespaceRow struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
	Name     string `json:"name"`
}

func (q *Queries) BreakerNamespace(ctx context.Context, id string) (BreakerNamespaceRow, error) {
	row := q.db.QueryRow(ctx, breakerNamespace, id)
	var i BreakerNamespaceRow
	err := row.Scan(&i.ID, &i.TenantID, &i.Name)
	return i, err
}

const breakerNamespaceSites = `-- name: BreakerNamespaceSites :many
SELECT id, hkey, name, paused, paused_reason, paused_at
FROM sites
WHERE namespace_id = $1
ORDER BY name
`

type BreakerNamespaceSitesRow struct {
	ID           string     `json:"id"`
	Hkey         int64      `json:"hkey"`
	Name         string     `json:"name"`
	Paused       bool       `json:"paused"`
	PausedReason string     `json:"paused_reason"`
	PausedAt     *time.Time `json:"paused_at"`
}

func (q *Queries) BreakerNamespaceSites(ctx context.Context, namespaceID string) ([]BreakerNamespaceSitesRow, error) {
	rows, err := q.db.Query(ctx, breakerNamespaceSites, namespaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BreakerNamespaceSitesRow{}
	for rows.Next() {
		var i BreakerNamespaceSitesRow
		if err := rows.Scan(
			&i.ID,
			&i.Hkey,
			&i.Name,
			&i.Paused,
			&i.PausedReason,
			&i.PausedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const breakerUpdateSitePaused = `-- name: BreakerUpdateSitePaused :one
UPDATE sites
SET paused        = $1,
    paused_reason = $2,
    paused_at     = $3,
    paused_by     = $4,
    updated_at    = now()
WHERE id = $5 AND namespace_id = $6
RETURNING paused, paused_reason, paused_at, paused_by
`

type BreakerUpdateSitePausedParams struct {
	Paused       bool       `json:"paused"`
	PausedReason string     `json:"paused_reason"`
	PausedAt     *time.Time `json:"paused_at"`
	PausedBy     string     `json:"paused_by"`
	ID           string     `json:"id"`
	NamespaceID  string     `json:"namespace_id"`
}

type BreakerUpdateSitePausedRow struct {
	Paused       bool       `json:"paused"`
	PausedReason string     `json:"paused_reason"`
	PausedAt     *time.Time `json:"paused_at"`
	PausedBy     string     `json:"paused_by"`
}

func (q *Queries) BreakerUpdateSitePaused(ctx context.Context, arg BreakerUpdateSitePausedParams) (BreakerUpdateSitePausedRow, error) {
	row := q.db.QueryRow(ctx, breakerUpdateSitePaused,
		arg.Paused,
		arg.PausedReason,
		arg.PausedAt,
		arg.PausedBy,
		arg.ID,
		arg.NamespaceID,
	)
	var i BreakerUpdateSitePausedRow
	err := row.Scan(
		&i.Paused,
		&i.PausedReason,
		&i.PausedAt,
		&i.PausedBy,
	)
	return i, err
}
