// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package statsdb

import (
	"context"
	"time"
)

const statsUpsertAcquireMinutely = `-- name: StatsUpsertAcquireMinutely :exec
INSERT INTO acquire_stats_minutely AS t (
    bucket, namespace_id, site_id, endpoint_group_id, result, count, duration_us_sum
)
SELECT unnest($1::timestamptz[]),
       unnest($2::text[]),
       unnest($3::text[]),
       unnest($4::text[]),
       unnest($5::text[]),
       unnest($6::bigint[]),
       unnest($7::bigint[])
ON CONFLICT (bucket, namespace_id, site_id, endpoint_group_id, result) DO UPDATE
SET count = t.count + EXCLUDED.count,
    duration_us_sum = t.duration_us_sum + EXCLUDED.duration_us_sum
`

type StatsUpsertAcquireMinutelyParams struct {
	Buckets          []time.Time `json:"buckets"`
	NamespaceIds     []string    `json:"namespace_ids"`
	SiteIds          []string    `json:"site_ids"`
	EndpointGroupIds []string    `json:"endpoint_group_ids"`
	Results          []string    `json:"results"`
	Counts           []int64     `json:"counts"`
	DurationUsSums   []int64     `json:"duration_us_sums"`
}

// StatsUpsertAcquireMinutely adds acquire result counters per minute bucket.
// Rows are parallel arrays of equal length (select-list unnest expands them in
// lockstep); counters add to existing rows because several instances flush the
// same buckets. A statement must not repeat a primary key, and rows should be
// ordered by primary key so concurrent writers lock rows in the same order.
// The same conventions apply to every upsert in this file.
func (q *Queries) StatsUpsertAcquireMinutely(ctx context.Context, arg StatsUpsertAcquireMinutelyParams) error {
	_, err := q.db.Exec(ctx, statsUpsertAcquireMinutely,
		arg.Buckets,
		arg.NamespaceIds,
		arg.SiteIds,
		arg.EndpointGroupIds,
		arg.Results,
		arg.Counts,
		arg.DurationUsSums,
	)
	return err
}

const statsUpsertIdentityHourly = `-- name: StatsUpsertIdentityHourly :exec
INSERT INTO identity_stats_hourly AS t (
    bucket, site_id, identity_id, endpoint_group_id, outcome, count
)
SELECT unnest($1::timestamptz[]),
       unnest($2::text[]),
       unnest($3::text[]),
       unnest($4::text[]),
       unnest($5::text[]),
       unnest($6::bigint[])
ON CONFLICT (bucket, identity_id, endpoint_group_id, outcome) DO UPDATE
SET count = t.count + EXCLUDED.count
`

type StatsUpsertIdentityHourlyParams struct {
	Buckets          []time.Time `json:"buckets"`
	SiteIds          []string    `json:"site_ids"`
	IdentityIds      []string    `json:"identity_ids"`
	EndpointGroupIds []string    `json:"endpoint_group_ids"`
	Outcomes         []string    `json:"outcomes"`
	Counts           []int64     `json:"counts"`
}

// StatsUpsertIdentityHourly adds per-identity outcome counters per hour bucket.
func (q *Queries) StatsUpsertIdentityHourly(ctx context.Context, arg StatsUpsertIdentityHourlyParams) error {
	_, err := q.db.Exec(ctx, statsUpsertIdentityHourly,
		arg.Buckets,
		arg.SiteIds,
		arg.IdentityIds,
		arg.EndpointGroupIds,
		arg.Outcomes,
		arg.Counts,
	)
	return err
}

const statsUpsertNodeMinutely = `-- name: StatsUpsertNodeMinutely :exec
INSERT INTO node_stats_minutely AS t (
    bucket, namespace_id, node, acquires, reports, abandoned, rejected
)
SELECT unnest($1::timestamptz[]),
       unnest($2::text[]),
       unnest($3::text[]),
       unnest($4::bigint[]),
       unnest($5::bigint[]),
       unnest($6::bigint[]),
       unnest($7::bigint[])
ON CONFLICT (bucket, namespace_id, node) DO UPDATE
SET acquires = t.acquires + EXCLUDED.acquires,
    reports = t.reports + EXCLUDED.reports,
    abandoned = t.abandoned + EXCLUDED.abandoned,
    rejected = t.rejected + EXCLUDED.rejected
`

type StatsUpsertNodeMinutelyParams struct {
	Buckets      []time.Time `json:"buckets"`
	NamespaceIds []string    `json:"namespace_ids"`
	Nodes        []string    `json:"nodes"`
	Acquires     []int64     `json:"acquires"`
	Reports      []int64     `json:"reports"`
	Abandoned    []int64     `json:"abandoned"`
	Rejected     []int64     `json:"rejected"`
}

// StatsUpsertNodeMinutely adds per-node lease and report counters.
func (q *Queries) StatsUpsertNodeMinutely(ctx context.Context, arg StatsUpsertNodeMinutelyParams) error {
	_, err := q.db.Exec(ctx, statsUpsertNodeMinutely,
		arg.Buckets,
		arg.NamespaceIds,
		arg.Nodes,
		arg.Acquires,
		arg.Reports,
		arg.Abandoned,
		arg.Rejected,
	)
	return err
}

const statsUpsertOutcomeMinutely = `-- name: StatsUpsertOutcomeMinutely :exec
INSERT INTO outcome_stats_minutely AS t (
    bucket, namespace_id, site_id, endpoint_group_id, proxy_id, outcome, count, latency_ms_sum, response_bytes_sum
)
SELECT unnest($1::timestamptz[]),
       unnest($2::text[]),
       unnest($3::text[]),
       unnest($4::text[]),
       unnest($5::text[]),
       unnest($6::text[]),
       unnest($7::bigint[]),
       unnest($8::bigint[]),
       unnest($9::bigint[])
ON CONFLICT (bucket, namespace_id, site_id, endpoint_group_id, proxy_id, outcome) DO UPDATE
SET count = t.count + EXCLUDED.count,
    latency_ms_sum = t.latency_ms_sum + EXCLUDED.latency_ms_sum,
    response_bytes_sum = t.response_bytes_sum + EXCLUDED.response_bytes_sum
`

type StatsUpsertOutcomeMinutelyParams struct {
	Buckets           []time.Time `json:"buckets"`
	NamespaceIds      []string    `json:"namespace_ids"`
	SiteIds           []string    `json:"site_ids"`
	EndpointGroupIds  []string    `json:"endpoint_group_ids"`
	ProxyIds          []string    `json:"proxy_ids"`
	Outcomes          []string    `json:"outcomes"`
	Counts            []int64     `json:"counts"`
	LatencyMsSums     []int64     `json:"latency_ms_sums"`
	ResponseBytesSums []int64     `json:"response_bytes_sums"`
}

// StatsUpsertOutcomeMinutely adds report outcome counters and latency/size sums.
func (q *Queries) StatsUpsertOutcomeMinutely(ctx context.Context, arg StatsUpsertOutcomeMinutelyParams) error {
	_, err := q.db.Exec(ctx, statsUpsertOutcomeMinutely,
		arg.Buckets,
		arg.NamespaceIds,
		arg.SiteIds,
		arg.EndpointGroupIds,
		arg.ProxyIds,
		arg.Outcomes,
		arg.Counts,
		arg.LatencyMsSums,
		arg.ResponseBytesSums,
	)
	return err
}

const statsUpsertPayloadAccessMinutely = `-- name: StatsUpsertPayloadAccessMinutely :exec
INSERT INTO payload_access_minutely AS t (
    bucket, namespace_id, token_id, identity_type_id, count
)
SELECT unnest($1::timestamptz[]),
       unnest($2::text[]),
       unnest($3::text[]),
       unnest($4::text[]),
       unnest($5::bigint[])
ON CONFLICT (bucket, namespace_id, token_id, identity_type_id) DO UPDATE
SET count = t.count + EXCLUDED.count
`

type StatsUpsertPayloadAccessMinutelyParams struct {
	Buckets         []time.Time `json:"buckets"`
	NamespaceIds    []string    `json:"namespace_ids"`
	TokenIds        []string    `json:"token_ids"`
	IdentityTypeIds []string    `json:"identity_type_ids"`
	Counts          []int64     `json:"counts"`
}

// StatsUpsertPayloadAccessMinutely adds credential delivery counters per token and identity type.
func (q *Queries) StatsUpsertPayloadAccessMinutely(ctx context.Context, arg StatsUpsertPayloadAccessMinutelyParams) error {
	_, err := q.db.Exec(ctx, statsUpsertPayloadAccessMinutely,
		arg.Buckets,
		arg.NamespaceIds,
		arg.TokenIds,
		arg.IdentityTypeIds,
		arg.Counts,
	)
	return err
}
