// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rewrap.sql

package vaultdb

import (
	"context"
	"encoding/json"
	"time"
)

const vaultKEKRecordCounts = `-- name: VaultKEKRecordCounts :many
SELECT t.kek_id::text AS kek_id, count(*)::bigint AS records
FROM (
    SELECT kek_id FROM identity_payloads
    UNION ALL
    SELECT kek_id FROM secret_versions
    UNION ALL
    SELECT url_kek_id FROM proxies
    UNION ALL
    SELECT config_kek_id FROM notification_channels
    UNION ALL
    SELECT kek_id FROM system_keys
) AS t
GROUP BY t.kek_id
ORDER BY t.kek_id
`

type VaultKEKRecordCountsRow struct {
	KekID   string `json:"kek_id"`
	Records int64  `json:"records"`
}

// VaultKEKRecordCounts counts envelope-encrypted records per KEK id across
// every table holding wrapped DEKs.
func (q *Queries) VaultKEKRecordCounts(ctx context.Context) ([]VaultKEKRecordCountsRow, error) {
	rows, err := q.db.Query(ctx, vaultKEKRecordCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultKEKRecordCountsRow{}
	for rows.Next() {
		var i VaultKEKRecordCountsRow
		if err := rows.Scan(&i.KekID, &i.Records); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const vaultRewrapChannelBatch = `-- name: VaultRewrapChannelBatch :many
SELECT id, config_wrapped_dek AS wrapped_dek, config_kek_id AS kek_id
FROM notification_channels
WHERE config_kek_id <> $1::text
  AND id > $2::text
ORDER BY id
LIMIT $3::integer
`

type VaultRewrapChannelBatchParams struct {
	CurrentKekID string `json:"current_kek_id"`
	AfterID      string `json:"after_id"`
	LimitRows    int32  `json:"limit_rows"`
}

type VaultRewrapChannelBatchRow struct {
	ID         string `json:"id"`
	WrappedDek []byte `json:"wrapped_dek"`
	KekID      string `json:"kek_id"`
}

func (q *Queries) VaultRewrapChannelBatch(ctx context.Context, arg VaultRewrapChannelBatchParams) ([]VaultRewrapChannelBatchRow, error) {
	rows, err := q.db.Query(ctx, vaultRewrapChannelBatch, arg.CurrentKekID, arg.AfterID, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultRewrapChannelBatchRow{}
	for rows.Next() {
		var i VaultRewrapChannelBatchRow
		if err := rows.Scan(&i.ID, &i.WrappedDek, &i.KekID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const vaultRewrapChannelUpdate = `-- name: VaultRewrapChannelUpdate :execrows
UPDATE notification_channels AS t
SET config_wrapped_dek = u.new_wrapped_dek,
    config_kek_id      = $1::text
FROM (
    SELECT unnest($2::text[])                AS id,
           unnest($3::bytea[])  AS old_wrapped_dek,
           unnest($4::text[])        AS old_kek_id,
           unnest($5::bytea[])  AS new_wrapped_dek
) AS u
WHERE t.id = u.id
  AND t.config_kek_id = u.old_kek_id
  AND t.config_wrapped_dek = u.old_wrapped_dek
`

type VaultRewrapChannelUpdateParams struct {
	NewKekID       string   `json:"new_kek_id"`
	Ids            []string `json:"ids"`
	OldWrappedDeks [][]byte `json:"old_wrapped_deks"`
	OldKekIds      []string `json:"old_kek_ids"`
	NewWrappedDeks [][]byte `json:"new_wrapped_deks"`
}

func (q *Queries) VaultRewrapChannelUpdate(ctx context.Context, arg VaultRewrapChannelUpdateParams) (int64, error) {
	result, err := q.db.Exec(ctx, vaultRewrapChannelUpdate,
		arg.NewKekID,
		arg.Ids,
		arg.OldWrappedDeks,
		arg.OldKekIds,
		arg.NewWrappedDeks,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const vaultRewrapIdentityPayloadBatch = `-- name: VaultRewrapIdentityPayloadBatch :many
SELECT identity_id, version, wrapped_dek, kek_id
FROM identity_payloads
WHERE kek_id <> $1::text
  AND (identity_id, version) > ($2::text, $3::integer)
ORDER BY identity_id, version
LIMIT $4::integer
`

type VaultRewrapIdentityPayloadBatchParams struct {
	CurrentKekID string `json:"current_kek_id"`
	AfterID      string `json:"after_id"`
	AfterVersion int32  `json:"after_version"`
	LimitRows    int32  `json:"limit_rows"`
}

type VaultRewrapIdentityPayloadBatchRow struct {
	IdentityID string `json:"identity_id"`
	Version    int32  `json:"version"`
	WrappedDek []byte `json:"wrapped_dek"`
	KekID      string `json:"kek_id"`
}

func (q *Queries) VaultRewrapIdentityPayloadBatch(ctx context.Context, arg VaultRewrapIdentityPayloadBatchParams) ([]VaultRewrapIdentityPayloadBatchRow, error) {
	rows, err := q.db.Query(ctx, vaultRewrapIdentityPayloadBatch,
		arg.CurrentKekID,
		arg.AfterID,
		arg.AfterVersion,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultRewrapIdentityPayloadBatchRow{}
	for rows.Next() {
		var i VaultRewrapIdentityPayloadBatchRow
		if err := rows.Scan(
			&i.IdentityID,
			&i.Version,
			&i.WrappedDek,
			&i.KekID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const vaultRewrapIdentityPayloadUpdate = `-- name: VaultRewrapIdentityPayloadUpdate :execrows
UPDATE identity_payloads AS t
SET wrapped_dek = u.new_wrapped_dek,
    kek_id      = $1::text
FROM (
    SELECT unnest($2::text[])                AS id,
           unnest($3::integer[])        AS version,
           unnest($4::bytea[])  AS old_wrapped_dek,
           unnest($5::text[])        AS old_kek_id,
           unnest($6::bytea[])  AS new_wrapped_dek
) AS u
WHERE t.identity_id = u.id
  AND t.version = u.version
  AND t.kek_id = u.old_kek_id
  AND t.wrapped_dek = u.old_wrapped_dek
`

type VaultRewrapIdentityPayloadUpdateParams struct {
	NewKekID       string   `json:"new_kek_id"`
	Ids            []string `json:"ids"`
	Versions       []int32  `json:"versions"`
	OldWrappedDeks [][]byte `json:"old_wrapped_deks"`
	OldKekIds      []string `json:"old_kek_ids"`
	NewWrappedDeks [][]byte `json:"new_wrapped_deks"`
}

func (q *Queries) VaultRewrapIdentityPayloadUpdate(ctx context.Context, arg VaultRewrapIdentityPayloadUpdateParams) (int64, error) {
	result, err := q.db.Exec(ctx, vaultRewrapIdentityPayloadUpdate,
		arg.NewKekID,
		arg.Ids,
		arg.Versions,
		arg.OldWrappedDeks,
		arg.OldKekIds,
		arg.NewWrappedDeks,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const vaultRewrapPendingCount = `-- name: VaultRewrapPendingCount :one
SELECT ((SELECT count(*) FROM identity_payloads WHERE identity_payloads.kek_id <> $1::text)
      + (SELECT count(*) FROM secret_versions WHERE secret_versions.kek_id <> $1::text)
      + (SELECT count(*) FROM proxies WHERE proxies.url_kek_id <> $1::text)
      + (SELECT count(*) FROM notification_channels WHERE notification_channels.config_kek_id <> $1::text)
      + (SELECT count(*) FROM system_keys WHERE system_keys.kek_id <> $1::text))::bigint AS pending
`

func (q *Queries) VaultRewrapPendingCount(ctx context.Context, currentKekID string) (int64, error) {
	row := q.db.QueryRow(ctx, vaultRewrapPendingCount, currentKekID)
	var pending int64
	err := row.Scan(&pending)
	return pending, err
}

const vaultRewrapProxyBatch = `-- name: VaultRewrapProxyBatch :many
SELECT id, url_wrapped_dek AS wrapped_dek, url_kek_id AS kek_id
FROM proxies
WHERE url_kek_id <> $1::text
  AND id > $2::text
ORDER BY id
LIMIT $3::integer
`

type VaultRewrapProxyBatchParams struct {
	CurrentKekID string `json:"current_kek_id"`
	AfterID      string `json:"after_id"`
	LimitRows    int32  `json:"limit_rows"`
}

type VaultRewrapProxyBatchRow struct {
	ID         string `json:"id"`
	WrappedDek []byte `json:"wrapped_dek"`
	KekID      string `json:"kek_id"`
}

func (q *Queries) VaultRewrapProxyBatch(ctx context.Context, arg VaultRewrapProxyBatchParams) ([]VaultRewrapProxyBatchRow, error) {
	rows, err := q.db.Query(ctx, vaultRewrapProxyBatch, arg.CurrentKekID, arg.AfterID, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultRewrapProxyBatchRow{}
	for rows.Next() {
		var i VaultRewrapProxyBatchRow
		if err := rows.Scan(&i.ID, &i.WrappedDek, &i.KekID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const vaultRewrapProxyUpdate = `-- name: VaultRewrapProxyUpdate :execrows
UPDATE proxies AS t
SET url_wrapped_dek = u.new_wrapped_dek,
    url_kek_id      = $1::text
FROM (
    SELECT unnest($2::text[])                AS id,
           unnest($3::bytea[])  AS old_wrapped_dek,
           unnest($4::text[])        AS old_kek_id,
           unnest($5::bytea[])  AS new_wrapped_dek
) AS u
WHERE t.id = u.id
  AND t.url_kek_id = u.old_kek_id
  AND t.url_wrapped_dek = u.old_wrapped_dek
`

type VaultRewrapProxyUpdateParams struct {
	NewKekID       string   `json:"new_kek_id"`
	Ids            []string `json:"ids"`
	OldWrappedDeks [][]byte `json:"old_wrapped_deks"`
	OldKekIds      []string `json:"old_kek_ids"`
	NewWrappedDeks [][]byte `json:"new_wrapped_deks"`
}

func (q *Queries) VaultRewrapProxyUpdate(ctx context.Context, arg VaultRewrapProxyUpdateParams) (int64, error) {
	result, err := q.db.Exec(ctx, vaultRewrapProxyUpdate,
		arg.NewKekID,
		arg.Ids,
		arg.OldWrappedDeks,
		arg.OldKekIds,
		arg.NewWrappedDeks,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const vaultRewrapSecretVersionBatch = `-- name: VaultRewrapSecretVersionBatch :many
SELECT secret_id, version, wrapped_dek, kek_id
FROM secret_versions
WHERE kek_id <> $1::text
  AND (secret_id, version) > ($2::text, $3::integer)
ORDER BY secret_id, version
LIMIT $4::integer
`

type VaultRewrapSecretVersionBatchParams struct {
	CurrentKekID string `json:"current_kek_id"`
	AfterID      string `json:"after_id"`
	AfterVersion int32  `json:"after_version"`
	LimitRows    int32  `json:"limit_rows"`
}

type VaultRewrapSecretVersionBatchRow struct {
	SecretID   string `json:"secret_id"`
	Version    int32  `json:"version"`
	WrappedDek []byte `json:"wrapped_dek"`
	KekID      string `json:"kek_id"`
}

func (q *Queries) VaultRewrapSecretVersionBatch(ctx context.Context, arg VaultRewrapSecretVersionBatchParams) ([]VaultRewrapSecretVersionBatchRow, error) {
	rows, err := q.db.Query(ctx, vaultRewrapSecretVersionBatch,
		arg.CurrentKekID,
		arg.AfterID,
		arg.AfterVersion,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultRewrapSecretVersionBatchRow{}
	for rows.Next() {
		var i VaultRewrapSecretVersionBatchRow
		if err := rows.Scan(
			&i.SecretID,
			&i.Version,
			&i.WrappedDek,
			&i.KekID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const vaultRewrapSecretVersionUpdate = `-- name: VaultRewrapSecretVersionUpdate :execrows
UPDATE secret_versions AS t
SET wrapped_dek = u.new_wrapped_dek,
    kek_id      = $1::text
FROM (
    SELECT unnest($2::text[])                AS id,
           unnest($3::integer[])        AS version,
           unnest($4::bytea[])  AS old_wrapped_dek,
           unnest($5::text[])        AS old_kek_id,
           unnest($6::bytea[])  AS new_wrapped_dek
) AS u
WHERE t.secret_id = u.id
  AND t.version = u.version
  AND t.kek_id = u.old_kek_id
  AND t.wrapped_dek = u.old_wrapped_dek
`

type VaultRewrapSecretVersionUpdateParams struct {
	NewKekID       string   `json:"new_kek_id"`
	Ids            []string `json:"ids"`
	Versions       []int32  `json:"versions"`
	OldWrappedDeks [][]byte `json:"old_wrapped_deks"`
	OldKekIds      []string `json:"old_kek_ids"`
	NewWrappedDeks [][]byte `json:"new_wrapped_deks"`
}

func (q *Queries) VaultRewrapSecretVersionUpdate(ctx context.Context, arg VaultRewrapSecretVersionUpdateParams) (int64, error) {
	result, err := q.db.Exec(ctx, vaultRewrapSecretVersionUpdate,
		arg.NewKekID,
		arg.Ids,
		arg.Versions,
		arg.OldWrappedDeks,
		arg.OldKekIds,
		arg.NewWrappedDeks,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const vaultRewrapSystemKeyBatch = `-- name: VaultRewrapSystemKeyBatch :many
SELECT name AS id, wrapped_dek, kek_id
FROM system_keys
WHERE kek_id <> $1::text
  AND name > $2::text
ORDER BY name
LIMIT $3::integer
`

type VaultRewrapSystemKeyBatchParams struct {
	CurrentKekID string `json:"current_kek_id"`
	AfterID      string `json:"after_id"`
	LimitRows    int32  `json:"limit_rows"`
}

type VaultRewrapSystemKeyBatchRow struct {
	ID         string `json:"id"`
	WrappedDek []byte `json:"wrapped_dek"`
	KekID      string `json:"kek_id"`
}

func (q *Queries) VaultRewrapSystemKeyBatch(ctx context.Context, arg VaultRewrapSystemKeyBatchParams) ([]VaultRewrapSystemKeyBatchRow, error) {
	rows, err := q.db.Query(ctx, vaultRewrapSystemKeyBatch, arg.CurrentKekID, arg.AfterID, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultRewrapSystemKeyBatchRow{}
	for rows.Next() {
		var i VaultRewrapSystemKeyBatchRow
		if err := rows.Scan(&i.ID, &i.WrappedDek, &i.KekID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const vaultRewrapSystemKeyUpdate = `-- name: VaultRewrapSystemKeyUpdate :execrows
UPDATE system_keys AS t
SET wrapped_dek = u.new_wrapped_dek,
    kek_id      = $1::text,
    updated_at  = now()
FROM (
    SELECT unnest($2::text[])                AS id,
           unnest($3::bytea[])  AS old_wrapped_dek,
           unnest($4::text[])        AS old_kek_id,
           unnest($5::bytea[])  AS new_wrapped_dek
) AS u
WHERE t.name = u.id
  AND t.kek_id = u.old_kek_id
  AND t.wrapped_dek = u.old_wrapped_dek
`

type VaultRewrapSystemKeyUpdateParams struct {
	NewKekID       string   `json:"new_kek_id"`
	Ids            []string `json:"ids"`
	OldWrappedDeks [][]byte `json:"old_wrapped_deks"`
	OldKekIds      []string `json:"old_kek_ids"`
	NewWrappedDeks [][]byte `json:"new_wrapped_deks"`
}

func (q *Queries) VaultRewrapSystemKeyUpdate(ctx context.Context, arg VaultRewrapSystemKeyUpdateParams) (int64, error) {
	result, err := q.db.Exec(ctx, vaultRewrapSystemKeyUpdate,
		arg.NewKekID,
		arg.Ids,
		arg.OldWrappedDeks,
		arg.OldKekIds,
		arg.NewWrappedDeks,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const vaultSettingGet = `-- name: VaultSettingGet :one

SELECT value, updated_at
FROM system_settings
WHERE key = $1
`

type VaultSettingGetRow struct {
	Value     json.RawMessage `json:"value"`
	UpdatedAt time.Time       `json:"updated_at"`
}

// KEK rewrap job and status (vault-secrets track).
func (q *Queries) VaultSettingGet(ctx context.Context, key string) (VaultSettingGetRow, error) {
	row := q.db.QueryRow(ctx, vaultSettingGet, key)
	var i VaultSettingGetRow
	err := row.Scan(&i.Value, &i.UpdatedAt)
	return i, err
}

const vaultSettingPut = `-- name: VaultSettingPut :exec
INSERT INTO system_settings (key, value, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (key) DO UPDATE
SET value      = EXCLUDED.value,
    updated_at = EXCLUDED.updated_at
`

type VaultSettingPutParams struct {
	Key   string          `json:"key"`
	Value json.RawMessage `json:"value"`
}

func (q *Queries) VaultSettingPut(ctx context.Context, arg VaultSettingPutParams) error {
	_, err := q.db.Exec(ctx, vaultSettingPut, arg.Key, arg.Value)
	return err
}
