// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secrets.sql

package vaultdb

import (
	"context"
	"time"
)

const vaultSecretAccessLogs = `-- name: VaultSecretAccessLogs :many
SELECT id,
       created_at,
       actor_kind,
       actor_id,
       actor_name,
       action,
       result,
       ip,
       COALESCE(details ->> 'version', '')::text AS version
FROM audit_logs
WHERE tenant_id = $1
  AND resource_kind = 'secret'
  AND resource_id = $2
  AND created_at >= $3::timestamptz
  AND (NOT $4::boolean
       OR (created_at, id) < ($5::timestamptz, $6::text))
ORDER BY created_at DESC, id DESC
LIMIT $7::integer
`

type VaultSecretAccessLogsParams struct {
	TenantID        string    `json:"tenant_id"`
	SecretID        string    `json:"secret_id"`
	Since           time.Time `json:"since"`
	HasCursor       bool      `json:"has_cursor"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        string    `json:"cursor_id"`
	LimitRows       int32     `json:"limit_rows"`
}

type VaultSecretAccessLogsRow struct {
	ID        string    `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	ActorKind string    `json:"actor_kind"`
	ActorID   string    `json:"actor_id"`
	ActorName string    `json:"actor_name"`
	Action    string    `json:"action"`
	Result    string    `json:"result"`
	Ip        string    `json:"ip"`
	Version   string    `json:"version"`
}

// VaultSecretAccessLogs returns one keyset page of the audit entries of a
// secret, newest first. since bounds the scanned partitions.
func (q *Queries) VaultSecretAccessLogs(ctx context.Context, arg VaultSecretAccessLogsParams) ([]VaultSecretAccessLogsRow, error) {
	rows, err := q.db.Query(ctx, vaultSecretAccessLogs,
		arg.TenantID,
		arg.SecretID,
		arg.Since,
		arg.HasCursor,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultSecretAccessLogsRow{}
	for rows.Next() {
		var i VaultSecretAccessLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ActorKind,
			&i.ActorID,
			&i.ActorName,
			&i.Action,
			&i.Result,
			&i.Ip,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const vaultSecretCount = `-- name: VaultSecretCount :one
SELECT count(*)::bigint AS total
FROM secrets s
WHERE s.namespace_id = $1
  AND ($2::text = '' OR starts_with(s.path, $2::text))
  AND ($3::text = ''
       OR strpos(lower(s.path), lower($3::text)) > 0
       OR strpos(lower(s.description), lower($3::text)) > 0)
  AND (cardinality($4::text[]) = 0 OR s.tags @> $4::text[])
`

type VaultSecretCountParams struct {
	NamespaceID string   `json:"namespace_id"`
	Prefix      string   `json:"prefix"`
	Search      string   `json:"search"`
	Tags        []string `json:"tags"`
}

func (q *Queries) VaultSecretCount(ctx context.Context, arg VaultSecretCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, vaultSecretCount,
		arg.NamespaceID,
		arg.Prefix,
		arg.Search,
		arg.Tags,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const vaultSecretDelete = `-- name: VaultSecretDelete :execrows
DELETE FROM secrets
WHERE id = $1
`

func (q *Queries) VaultSecretDelete(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, vaultSecretDelete, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const vaultSecretGet = `-- name: VaultSecretGet :one
SELECT s.id,
       s.namespace_id,
       n.tenant_id,
       n.name AS namespace_name,
       s.path,
       s.description,
       s.tags,
       s.current_version,
       s.expires_at,
       s.last_accessed_at,
       s.created_by,
       s.created_at,
       s.updated_at,
       v.ciphertext,
       v.wrapped_dek,
       v.kek_id
FROM secrets s
JOIN namespaces n ON n.id = s.namespace_id
LEFT JOIN secret_versions v ON v.secret_id = s.id AND v.version = s.current_version
WHERE s.id = $1
`

type VaultSecretGetRow struct {
	ID             string     `json:"id"`
	NamespaceID    string     `json:"namespace_id"`
	TenantID       string     `json:"tenant_id"`
	NamespaceName  string     `json:"namespace_name"`
	Path           string     `json:"path"`
	Description    string     `json:"description"`
	Tags           []string   `json:"tags"`
	CurrentVersion int32      `json:"current_version"`
	ExpiresAt      *time.Time `json:"expires_at"`
	LastAccessedAt *time.Time `json:"last_accessed_at"`
	CreatedBy      string     `json:"created_by"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	Ciphertext     []byte     `json:"ciphertext"`
	WrappedDek     []byte     `json:"wrapped_dek"`
	KekID          *string    `json:"kek_id"`
}

// VaultSecretGet loads a secret with its namespace (for authorization) and
// the envelope of its current version (for masking).
func (q *Queries) VaultSecretGet(ctx context.Context, id string) (VaultSecretGetRow, error) {
	row := q.db.QueryRow(ctx, vaultSecretGet, id)
	var i VaultSecretGetRow
	err := row.Scan(
		&i.ID,
		&i.NamespaceID,
		&i.TenantID,
		&i.NamespaceName,
		&i.Path,
		&i.Description,
		&i.Tags,
		&i.CurrentVersion,
		&i.ExpiresAt,
		&i.LastAccessedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Ciphertext,
		&i.WrappedDek,
		&i.KekID,
	)
	return i, err
}

const vaultSecretIDByPath = `-- name: VaultSecretIDByPath :one
SELECT id
FROM secrets
WHERE namespace_id = $1
  AND path = $2
`

type VaultSecretIDByPathParams struct {
	NamespaceID string `json:"namespace_id"`
	Path        string `json:"path"`
}

func (q *Queries) VaultSecretIDByPath(ctx context.Context, arg VaultSecretIDByPathParams) (string, error) {
	row := q.db.QueryRow(ctx, vaultSecretIDByPath, arg.NamespaceID, arg.Path)
	var id string
	err := row.Scan(&id)
	return id, err
}

const vaultSecretInsert = `-- name: VaultSecretInsert :one

INSERT INTO secrets (id, namespace_id, path, description, tags, current_version, expires_at, created_by)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5::text[],
    1,
    $6::timestamptz,
    $7
)
RETURNING created_at, updated_at
`

type VaultSecretInsertParams struct {
	ID          string     `json:"id"`
	NamespaceID string     `json:"namespace_id"`
	Path        string     `json:"path"`
	Description string     `json:"description"`
	Tags        []string   `json:"tags"`
	ExpiresAt   *time.Time `json:"expires_at"`
	CreatedBy   string     `json:"created_by"`
}

type VaultSecretInsertRow struct {
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Secrets and secret versions (vault-secrets track).
func (q *Queries) VaultSecretInsert(ctx context.Context, arg VaultSecretInsertParams) (VaultSecretInsertRow, error) {
	row := q.db.QueryRow(ctx, vaultSecretInsert,
		arg.ID,
		arg.NamespaceID,
		arg.Path,
		arg.Description,
		arg.Tags,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i VaultSecretInsertRow
	err := row.Scan(&i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const vaultSecretList = `-- name: VaultSecretList :many
SELECT s.id,
       s.namespace_id,
       s.path,
       s.description,
       s.tags,
       s.current_version,
       s.expires_at,
       s.last_accessed_at,
       s.created_by,
       s.created_at,
       s.updated_at,
       v.ciphertext,
       v.wrapped_dek,
       v.kek_id
FROM secrets s
LEFT JOIN secret_versions v ON v.secret_id = s.id AND v.version = s.current_version
WHERE s.namespace_id = $1
  AND ($2::text = '' OR starts_with(s.path, $2::text))
  AND ($3::text = ''
       OR strpos(lower(s.path), lower($3::text)) > 0
       OR strpos(lower(s.description), lower($3::text)) > 0)
  AND (cardinality($4::text[]) = 0 OR s.tags @> $4::text[])
  AND s.path > $5::text
ORDER BY s.path
LIMIT $6::integer
`

type VaultSecretListParams struct {
	NamespaceID string   `json:"namespace_id"`
	Prefix      string   `json:"prefix"`
	Search      string   `json:"search"`
	Tags        []string `json:"tags"`
	AfterPath   string   `json:"after_path"`
	LimitRows   int32    `json:"limit_rows"`
}

type VaultSecretListRow struct {
	ID             string     `json:"id"`
	NamespaceID    string     `json:"namespace_id"`
	Path           string     `json:"path"`
	Description    string     `json:"description"`
	Tags           []string   `json:"tags"`
	CurrentVersion int32      `json:"current_version"`
	ExpiresAt      *time.Time `json:"expires_at"`
	LastAccessedAt *time.Time `json:"last_accessed_at"`
	CreatedBy      string     `json:"created_by"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	Ciphertext     []byte     `json:"ciphertext"`
	WrappedDek     []byte     `json:"wrapped_dek"`
	KekID          *string    `json:"kek_id"`
}

// VaultSecretList returns one keyset page of secrets ordered by path together
// with the envelope of their current version.
func (q *Queries) VaultSecretList(ctx context.Context, arg VaultSecretListParams) ([]VaultSecretListRow, error) {
	rows, err := q.db.Query(ctx, vaultSecretList,
		arg.NamespaceID,
		arg.Prefix,
		arg.Search,
		arg.Tags,
		arg.AfterPath,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultSecretListRow{}
	for rows.Next() {
		var i VaultSecretListRow
		if err := rows.Scan(
			&i.ID,
			&i.NamespaceID,
			&i.Path,
			&i.Description,
			&i.Tags,
			&i.CurrentVersion,
			&i.ExpiresAt,
			&i.LastAccessedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Ciphertext,
			&i.WrappedDek,
			&i.KekID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const vaultSecretLock = `-- name: VaultSecretLock :one
SELECT s.id,
       s.namespace_id,
       n.tenant_id,
       n.name AS namespace_name,
       s.path,
       s.current_version
FROM secrets s
JOIN namespaces n ON n.id = s.namespace_id
WHERE s.id = $1
FOR UPDATE OF s
`

type VaultSecretLockRow struct {
	ID             string `json:"id"`
	NamespaceID    string `json:"namespace_id"`
	TenantID       string `json:"tenant_id"`
	NamespaceName  string `json:"namespace_name"`
	Path           string `json:"path"`
	CurrentVersion int32  `json:"current_version"`
}

// VaultSecretLock loads the authorization data of a secret and locks its row
// until the end of the transaction.
func (q *Queries) VaultSecretLock(ctx context.Context, id string) (VaultSecretLockRow, error) {
	row := q.db.QueryRow(ctx, vaultSecretLock, id)
	var i VaultSecretLockRow
	err := row.Scan(
		&i.ID,
		&i.NamespaceID,
		&i.TenantID,
		&i.NamespaceName,
		&i.Path,
		&i.CurrentVersion,
	)
	return i, err
}

const vaultSecretReadByPath = `-- name: VaultSecretReadByPath :one
SELECT s.id,
       s.path,
       s.expires_at,
       v.version,
       v.ciphertext,
       v.wrapped_dek,
       v.kek_id
FROM secrets s
JOIN secret_versions v ON v.secret_id = s.id
WHERE s.namespace_id = $1
  AND s.path = $2
  AND v.version = CASE WHEN $3::integer > 0 THEN $3::integer ELSE s.current_version END
`

type VaultSecretReadByPathParams struct {
	NamespaceID string `json:"namespace_id"`
	Path        string `json:"path"`
	Version     int32  `json:"version"`
}

type VaultSecretReadByPathRow struct {
	ID         string     `json:"id"`
	Path       string     `json:"path"`
	ExpiresAt  *time.Time `json:"expires_at"`
	Version    int32      `json:"version"`
	Ciphertext []byte     `json:"ciphertext"`
	WrappedDek []byte     `json:"wrapped_dek"`
	KekID      string     `json:"kek_id"`
}

// VaultSecretReadByPath loads one version (0 = current) of a secret addressed
// by namespace and path.
func (q *Queries) VaultSecretReadByPath(ctx context.Context, arg VaultSecretReadByPathParams) (VaultSecretReadByPathRow, error) {
	row := q.db.QueryRow(ctx, vaultSecretReadByPath, arg.NamespaceID, arg.Path, arg.Version)
	var i VaultSecretReadByPathRow
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.ExpiresAt,
		&i.Version,
		&i.Ciphertext,
		&i.WrappedDek,
		&i.KekID,
	)
	return i, err
}

const vaultSecretTouch = `-- name: VaultSecretTouch :execrows
UPDATE secrets AS s
SET last_accessed_at = GREATEST(COALESCE(s.last_accessed_at, a.accessed_at), a.accessed_at)
FROM (
    SELECT unnest($1::text[]) AS id,
           unnest($2::timestamptz[]) AS accessed_at
) AS a
WHERE s.id = a.id
`

type VaultSecretTouchParams struct {
	Ids        []string    `json:"ids"`
	AccessedAt []time.Time `json:"accessed_at"`
}

// VaultSecretTouch advances last_accessed_at of many secrets at once; it
// never moves the timestamp backwards.
func (q *Queries) VaultSecretTouch(ctx context.Context, arg VaultSecretTouchParams) (int64, error) {
	result, err := q.db.Exec(ctx, vaultSecretTouch, arg.Ids, arg.AccessedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const vaultSecretUpdate = `-- name: VaultSecretUpdate :exec
UPDATE secrets
SET current_version = $1,
    description     = CASE WHEN $2::boolean THEN $3::text ELSE description END,
    tags            = CASE WHEN $4::boolean THEN $5::text[] ELSE tags END,
    expires_at      = CASE WHEN $6::boolean THEN $7::timestamptz ELSE expires_at END,
    updated_at      = now()
WHERE id = $8
`

type VaultSecretUpdateParams struct {
	CurrentVersion int32      `json:"current_version"`
	SetDescription bool       `json:"set_description"`
	Description    string     `json:"description"`
	SetTags        bool       `json:"set_tags"`
	Tags           []string   `json:"tags"`
	SetExpiresAt   bool       `json:"set_expires_at"`
	ExpiresAt      *time.Time `json:"expires_at"`
	ID             string     `json:"id"`
}

func (q *Queries) VaultSecretUpdate(ctx context.Context, arg VaultSecretUpdateParams) error {
	_, err := q.db.Exec(ctx, vaultSecretUpdate,
		arg.CurrentVersion,
		arg.SetDescription,
		arg.Description,
		arg.SetTags,
		arg.Tags,
		arg.SetExpiresAt,
		arg.ExpiresAt,
		arg.ID,
	)
	return err
}

const vaultSecretVersionCount = `-- name: VaultSecretVersionCount :one
SELECT count(*)::bigint AS total
FROM secret_versions
WHERE secret_id = $1
`

func (q *Queries) VaultSecretVersionCount(ctx context.Context, secretID string) (int64, error) {
	row := q.db.QueryRow(ctx, vaultSecretVersionCount, secretID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const vaultSecretVersionGet = `-- name: VaultSecretVersionGet :one
SELECT version, ciphertext, wrapped_dek, kek_id
FROM secret_versions
WHERE secret_id = $1
  AND version = $2
`

type VaultSecretVersionGetParams struct {
	SecretID string `json:"secret_id"`
	Version  int32  `json:"version"`
}

type VaultSecretVersionGetRow struct {
	Version    int32  `json:"version"`
	Ciphertext []byte `json:"ciphertext"`
	WrappedDek []byte `json:"wrapped_dek"`
	KekID      string `json:"kek_id"`
}

func (q *Queries) VaultSecretVersionGet(ctx context.Context, arg VaultSecretVersionGetParams) (VaultSecretVersionGetRow, error) {
	row := q.db.QueryRow(ctx, vaultSecretVersionGet, arg.SecretID, arg.Version)
	var i VaultSecretVersionGetRow
	err := row.Scan(
		&i.Version,
		&i.Ciphertext,
		&i.WrappedDek,
		&i.KekID,
	)
	return i, err
}

const vaultSecretVersionInsert = `-- name: VaultSecretVersionInsert :exec
INSERT INTO secret_versions (secret_id, version, ciphertext, wrapped_dek, kek_id, created_by)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type VaultSecretVersionInsertParams struct {
	SecretID   string `json:"secret_id"`
	Version    int32  `json:"version"`
	Ciphertext []byte `json:"ciphertext"`
	WrappedDek []byte `json:"wrapped_dek"`
	KekID      string `json:"kek_id"`
	CreatedBy  string `json:"created_by"`
}

func (q *Queries) VaultSecretVersionInsert(ctx context.Context, arg VaultSecretVersionInsertParams) error {
	_, err := q.db.Exec(ctx, vaultSecretVersionInsert,
		arg.SecretID,
		arg.Version,
		arg.Ciphertext,
		arg.WrappedDek,
		arg.KekID,
		arg.CreatedBy,
	)
	return err
}

const vaultSecretVersionList = `-- name: VaultSecretVersionList :many
SELECT version, kek_id, created_by, created_at
FROM secret_versions
WHERE secret_id = $1
  AND ($2::integer <= 0 OR version < $2::integer)
ORDER BY version DESC
LIMIT $3::integer
`

type VaultSecretVersionListParams struct {
	SecretID      string `json:"secret_id"`
	BeforeVersion int32  `json:"before_version"`
	LimitRows     int32  `json:"limit_rows"`
}

type VaultSecretVersionListRow struct {
	Version   int32     `json:"version"`
	KekID     string    `json:"kek_id"`
	CreatedBy string    `json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) VaultSecretVersionList(ctx context.Context, arg VaultSecretVersionListParams) ([]VaultSecretVersionListRow, error) {
	rows, err := q.db.Query(ctx, vaultSecretVersionList, arg.SecretID, arg.BeforeVersion, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultSecretVersionListRow{}
	for rows.Next() {
		var i VaultSecretVersionListRow
		if err := rows.Scan(
			&i.Version,
			&i.KekID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
