// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: systemkeys.sql

package vaultdb

import (
	"context"
)

const vaultSystemKeyGet = `-- name: VaultSystemKeyGet :one

SELECT name, ciphertext, wrapped_dek, kek_id
FROM system_keys
WHERE name = $1
`

type VaultSystemKeyGetRow struct {
	Name       string `json:"name"`
	Ciphertext []byte `json:"ciphertext"`
	WrappedDek []byte `json:"wrapped_dek"`
	KekID      string `json:"kek_id"`
}

// System keys (vault-secrets track).
func (q *Queries) VaultSystemKeyGet(ctx context.Context, name string) (VaultSystemKeyGetRow, error) {
	row := q.db.QueryRow(ctx, vaultSystemKeyGet, name)
	var i VaultSystemKeyGetRow
	err := row.Scan(
		&i.Name,
		&i.Ciphertext,
		&i.WrappedDek,
		&i.KekID,
	)
	return i, err
}

const vaultSystemKeyInsert = `-- name: VaultSystemKeyInsert :execrows
INSERT INTO system_keys (name, ciphertext, wrapped_dek, kek_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (name) DO NOTHING
`

type VaultSystemKeyInsertParams struct {
	Name       string `json:"name"`
	Ciphertext []byte `json:"ciphertext"`
	WrappedDek []byte `json:"wrapped_dek"`
	KekID      string `json:"kek_id"`
}

// VaultSystemKeyInsert inserts a key unless one with the same name exists; it
// returns 0 affected rows when another instance won the race.
func (q *Queries) VaultSystemKeyInsert(ctx context.Context, arg VaultSystemKeyInsertParams) (int64, error) {
	result, err := q.db.Exec(ctx, vaultSystemKeyInsert,
		arg.Name,
		arg.Ciphertext,
		arg.WrappedDek,
		arg.KekID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
