global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: spinneret
    metrics_path: /metrics
    dns_sd_configs:
      - names: ["spinneret"]
        type: A
        port: 8080
