// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package proxydb

import (
	"context"
	"errors"
	"time"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const proxySetState = `-- name: ProxySetState :batchexec
UPDATE proxies SET
    state = $1,
    state_reason = $2,
    state_changed_at = $3,
    ban_until = $4,
    cooldown_until = $5,
    consecutive_check_failures = $6,
    next_check_at = $7,
    updated_at = $8
WHERE id = $9
`

type ProxySetStateBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type ProxySetStateParams struct {
	State                    string     `json:"state"`
	StateReason              string     `json:"state_reason"`
	StateChangedAt           time.Time  `json:"state_changed_at"`
	BanUntil                 *time.Time `json:"ban_until"`
	CooldownUntil            *time.Time `json:"cooldown_until"`
	ConsecutiveCheckFailures int32      `json:"consecutive_check_failures"`
	NextCheckAt              time.Time  `json:"next_check_at"`
	UpdatedAt                time.Time  `json:"updated_at"`
	ID                       string     `json:"id"`
}

func (q *Queries) ProxySetState(ctx context.Context, arg []ProxySetStateParams) *ProxySetStateBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.State,
			a.StateReason,
			a.StateChangedAt,
			a.BanUntil,
			a.CooldownUntil,
			a.ConsecutiveCheckFailures,
			a.NextCheckAt,
			a.UpdatedAt,
			a.ID,
		}
		batch.Queue(proxySetState, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &ProxySetStateBatchResults{br, len(arg), false}
}

func (b *ProxySetStateBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *ProxySetStateBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
