// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package proxydb

import (
	"context"
)

// iteratorForProxyInsertStateEvents implements pgx.CopyFromSource.
type iteratorForProxyInsertStateEvents struct {
	rows                 []ProxyInsertStateEventsParams
	skippedFirstNextCall bool
}

func (r *iteratorForProxyInsertStateEvents) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForProxyInsertStateEvents) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].CreatedAt,
		r.rows[0].TenantID,
		r.rows[0].NamespaceID,
		r.rows[0].SiteID,
		r.rows[0].SubjectKind,
		r.rows[0].SubjectID,
		r.rows[0].FromState,
		r.rows[0].ToState,
		r.rows[0].Action,
		r.rows[0].Scope,
		r.rows[0].Until,
		r.rows[0].Permanent,
		r.rows[0].Actor,
		r.rows[0].Reason,
		r.rows[0].Details,
	}, nil
}

func (r iteratorForProxyInsertStateEvents) Err() error {
	return nil
}

func (q *Queries) ProxyInsertStateEvents(ctx context.Context, arg []ProxyInsertStateEventsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"state_events"}, []string{"id", "created_at", "tenant_id", "namespace_id", "site_id", "subject_kind", "subject_id", "from_state", "to_state", "action", "scope", "until", "permanent", "actor", "reason", "details"}, &iteratorForProxyInsertStateEvents{rows: arg})
}
