// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proxy.sql

package proxydb

import (
	"context"
	"encoding/json"
	"time"
)

const proxyBoundCounts = `-- name: ProxyBoundCounts :many
SELECT proxy_id, count(*)::integer AS bound
FROM proxy_bindings
WHERE proxy_id = ANY($1::text[])
GROUP BY proxy_id
`

type ProxyBoundCountsRow struct {
	ProxyID string `json:"proxy_id"`
	Bound   int32  `json:"bound"`
}

func (q *Queries) ProxyBoundCounts(ctx context.Context, ids []string) ([]ProxyBoundCountsRow, error) {
	rows, err := q.db.Query(ctx, proxyBoundCounts, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProxyBoundCountsRow{}
	for rows.Next() {
		var i ProxyBoundCountsRow
		if err := rows.Scan(&i.ProxyID, &i.Bound); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const proxyCount = `-- name: ProxyCount :one
SELECT count(*)::bigint FROM proxies
WHERE namespace_id = $1
  AND ((cardinality($2::text[]) = 0 AND state <> 'retired') OR state = ANY($2::text[]))
  AND (cardinality($3::text[]) = 0 OR kind = ANY($3::text[]))
  AND (cardinality($4::text[]) = 0 OR provider = ANY($4::text[]))
  AND (cardinality($5::text[]) = 0 OR region = ANY($5::text[]))
  AND tags @> $6::text[]
  AND ($7::text = ''
       OR display_url ILIKE $7::text
       OR host ILIKE $7::text
       OR exit_ip ILIKE $7::text
       OR id LIKE $8::text)
`

type ProxyCountParams struct {
	NamespaceID     string   `json:"namespace_id"`
	States          []string `json:"states"`
	Kinds           []string `json:"kinds"`
	Providers       []string `json:"providers"`
	Regions         []string `json:"regions"`
	Tags            []string `json:"tags"`
	SearchPattern   string   `json:"search_pattern"`
	IDPrefixPattern string   `json:"id_prefix_pattern"`
}

func (q *Queries) ProxyCount(ctx context.Context, arg ProxyCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, proxyCount,
		arg.NamespaceID,
		arg.States,
		arg.Kinds,
		arg.Providers,
		arg.Regions,
		arg.Tags,
		arg.SearchPattern,
		arg.IDPrefixPattern,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const proxyCountByNamespaceState = `-- name: ProxyCountByNamespaceState :many
SELECT namespace_id, state, count(*)::bigint AS proxies
FROM proxies
GROUP BY namespace_id, state
`

type ProxyCountByNamespaceStateRow struct {
	NamespaceID string `json:"namespace_id"`
	State       string `json:"state"`
	Proxies     int64  `json:"proxies"`
}

func (q *Queries) ProxyCountByNamespaceState(ctx context.Context) ([]ProxyCountByNamespaceStateRow, error) {
	rows, err := q.db.Query(ctx, proxyCountByNamespaceState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProxyCountByNamespaceStateRow{}
	for rows.Next() {
		var i ProxyCountByNamespaceStateRow
		if err := rows.Scan(&i.NamespaceID, &i.State, &i.Proxies); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const proxyDeleteMany = `-- name: ProxyDeleteMany :many
DELETE FROM proxies WHERE id = ANY($1::text[]) RETURNING id, namespace_id, hkey, state, display_url
`

type ProxyDeleteManyRow struct {
	ID          string `json:"id"`
	NamespaceID string `json:"namespace_id"`
	Hkey        int64  `json:"hkey"`
	State       string `json:"state"`
	DisplayUrl  string `json:"display_url"`
}

func (q *Queries) ProxyDeleteMany(ctx context.Context, ids []string) ([]ProxyDeleteManyRow, error) {
	rows, err := q.db.Query(ctx, proxyDeleteMany, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProxyDeleteManyRow{}
	for rows.Next() {
		var i ProxyDeleteManyRow
		if err := rows.Scan(
			&i.ID,
			&i.NamespaceID,
			&i.Hkey,
			&i.State,
			&i.DisplayUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const proxyDueForCheck = `-- name: ProxyDueForCheck :many
SELECT id, hkey, namespace_id, scheme, host, port, username_hint, display_url, url_hash, url_ciphertext, url_wrapped_dek, url_kek_id, url_version, kind, region, city, provider, max_concurrency, tags, session_template, state, state_reason, state_changed_at, ban_until, cooldown_until, consecutive_check_failures, last_check_at, last_check_ok, last_latency_ms, exit_ip, next_check_at, created_at, updated_at FROM proxies
WHERE state IN ('active', 'dead')
  AND next_check_at <= $1::timestamptz
  AND (next_check_at, id) > ($2::timestamptz, $3::text)
ORDER BY next_check_at, id
LIMIT $4::integer
`

type ProxyDueForCheckParams struct {
	Now       time.Time `json:"now"`
	AfterAt   time.Time `json:"after_at"`
	AfterID   string    `json:"after_id"`
	PageLimit int32     `json:"page_limit"`
}

func (q *Queries) ProxyDueForCheck(ctx context.Context, arg ProxyDueForCheckParams) ([]Proxy, error) {
	rows, err := q.db.Query(ctx, proxyDueForCheck,
		arg.Now,
		arg.AfterAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Proxy{}
	for rows.Next() {
		var i Proxy
		if err := rows.Scan(
			&i.ID,
			&i.Hkey,
			&i.NamespaceID,
			&i.Scheme,
			&i.Host,
			&i.Port,
			&i.UsernameHint,
			&i.DisplayUrl,
			&i.UrlHash,
			&i.UrlCiphertext,
			&i.UrlWrappedDek,
			&i.UrlKekID,
			&i.UrlVersion,
			&i.Kind,
			&i.Region,
			&i.City,
			&i.Provider,
			&i.MaxConcurrency,
			&i.Tags,
			&i.SessionTemplate,
			&i.State,
			&i.StateReason,
			&i.StateChangedAt,
			&i.BanUntil,
			&i.CooldownUntil,
			&i.ConsecutiveCheckFailures,
			&i.LastCheckAt,
			&i.LastCheckOk,
			&i.LastLatencyMs,
			&i.ExitIp,
			&i.NextCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const proxyFindByHashes = `-- name: ProxyFindByHashes :many
SELECT id, url_hash, kind, region, city, provider, max_concurrency, tags, session_template
FROM proxies
WHERE namespace_id = $1 AND url_hash = ANY($2::bytea[])
`

type ProxyFindByHashesParams struct {
	NamespaceID string   `json:"namespace_id"`
	Hashes      [][]byte `json:"hashes"`
}

type ProxyFindByHashesRow struct {
	ID              string   `json:"id"`
	UrlHash         []byte   `json:"url_hash"`
	Kind            string   `json:"kind"`
	Region          string   `json:"region"`
	City            string   `json:"city"`
	Provider        string   `json:"provider"`
	MaxConcurrency  int32    `json:"max_concurrency"`
	Tags            []string `json:"tags"`
	SessionTemplate string   `json:"session_template"`
}

// Only the columns import de-duplication needs (imports match up to 100 000 rows).
func (q *Queries) ProxyFindByHashes(ctx context.Context, arg ProxyFindByHashesParams) ([]ProxyFindByHashesRow, error) {
	rows, err := q.db.Query(ctx, proxyFindByHashes, arg.NamespaceID, arg.Hashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProxyFindByHashesRow{}
	for rows.Next() {
		var i ProxyFindByHashesRow
		if err := rows.Scan(
			&i.ID,
			&i.UrlHash,
			&i.Kind,
			&i.Region,
			&i.City,
			&i.Provider,
			&i.MaxConcurrency,
			&i.Tags,
			&i.SessionTemplate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const proxyGet = `-- name: ProxyGet :one

SELECT id, hkey, namespace_id, scheme, host, port, username_hint, display_url, url_hash, url_ciphertext, url_wrapped_dek, url_kek_id, url_version, kind, region, city, provider, max_concurrency, tags, session_template, state, state_reason, state_changed_at, ban_until, cooldown_until, consecutive_check_failures, last_check_at, last_check_ok, last_latency_ms, exit_ip, next_check_at, created_at, updated_at FROM proxies WHERE id = $1
`

// Queries of the proxy domain (internal/proxy). Generated into package proxydb
// with: sqlc generate -f internal/proxy/sqlc.yaml
func (q *Queries) ProxyGet(ctx context.Context, id string) (Proxy, error) {
	row := q.db.QueryRow(ctx, proxyGet, id)
	var i Proxy
	err := row.Scan(
		&i.ID,
		&i.Hkey,
		&i.NamespaceID,
		&i.Scheme,
		&i.Host,
		&i.Port,
		&i.UsernameHint,
		&i.DisplayUrl,
		&i.UrlHash,
		&i.UrlCiphertext,
		&i.UrlWrappedDek,
		&i.UrlKekID,
		&i.UrlVersion,
		&i.Kind,
		&i.Region,
		&i.City,
		&i.Provider,
		&i.MaxConcurrency,
		&i.Tags,
		&i.SessionTemplate,
		&i.State,
		&i.StateReason,
		&i.StateChangedAt,
		&i.BanUntil,
		&i.CooldownUntil,
		&i.ConsecutiveCheckFailures,
		&i.LastCheckAt,
		&i.LastCheckOk,
		&i.LastLatencyMs,
		&i.ExitIp,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const proxyGetForUpdate = `-- name: ProxyGetForUpdate :one
SELECT id, hkey, namespace_id, scheme, host, port, username_hint, display_url, url_hash, url_ciphertext, url_wrapped_dek, url_kek_id, url_version, kind, region, city, provider, max_concurrency, tags, session_template, state, state_reason, state_changed_at, ban_until, cooldown_until, consecutive_check_failures, last_check_at, last_check_ok, last_latency_ms, exit_ip, next_check_at, created_at, updated_at FROM proxies WHERE id = $1 FOR UPDATE
`

func (q *Queries) ProxyGetForUpdate(ctx context.Context, id string) (Proxy, error) {
	row := q.db.QueryRow(ctx, proxyGetForUpdate, id)
	var i Proxy
	err := row.Scan(
		&i.ID,
		&i.Hkey,
		&i.NamespaceID,
		&i.Scheme,
		&i.Host,
		&i.Port,
		&i.UsernameHint,
		&i.DisplayUrl,
		&i.UrlHash,
		&i.UrlCiphertext,
		&i.UrlWrappedDek,
		&i.UrlKekID,
		&i.UrlVersion,
		&i.Kind,
		&i.Region,
		&i.City,
		&i.Provider,
		&i.MaxConcurrency,
		&i.Tags,
		&i.SessionTemplate,
		&i.State,
		&i.StateReason,
		&i.StateChangedAt,
		&i.BanUntil,
		&i.CooldownUntil,
		&i.ConsecutiveCheckFailures,
		&i.LastCheckAt,
		&i.LastCheckOk,
		&i.LastLatencyMs,
		&i.ExitIp,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const proxyGetMany = `-- name: ProxyGetMany :many
SELECT id, hkey, namespace_id, scheme, host, port, username_hint, display_url, url_hash, url_ciphertext, url_wrapped_dek, url_kek_id, url_version, kind, region, city, provider, max_concurrency, tags, session_template, state, state_reason, state_changed_at, ban_until, cooldown_until, consecutive_check_failures, last_check_at, last_check_ok, last_latency_ms, exit_ip, next_check_at, created_at, updated_at FROM proxies WHERE id = ANY($1::text[]) ORDER BY id
`

func (q *Queries) ProxyGetMany(ctx context.Context, ids []string) ([]Proxy, error) {
	rows, err := q.db.Query(ctx, proxyGetMany, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Proxy{}
	for rows.Next() {
		var i Proxy
		if err := rows.Scan(
			&i.ID,
			&i.Hkey,
			&i.NamespaceID,
			&i.Scheme,
			&i.Host,
			&i.Port,
			&i.UsernameHint,
			&i.DisplayUrl,
			&i.UrlHash,
			&i.UrlCiphertext,
			&i.UrlWrappedDek,
			&i.UrlKekID,
			&i.UrlVersion,
			&i.Kind,
			&i.Region,
			&i.City,
			&i.Provider,
			&i.MaxConcurrency,
			&i.Tags,
			&i.SessionTemplate,
			&i.State,
			&i.StateReason,
			&i.StateChangedAt,
			&i.BanUntil,
			&i.CooldownUntil,
			&i.ConsecutiveCheckFailures,
			&i.LastCheckAt,
			&i.LastCheckOk,
			&i.LastLatencyMs,
			&i.ExitIp,
			&i.NextCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const proxyGetManyForUpdate = `-- name: ProxyGetManyForUpdate :many
SELECT id, hkey, namespace_id, scheme, host, port, username_hint, display_url, url_hash, url_ciphertext, url_wrapped_dek, url_kek_id, url_version, kind, region, city, provider, max_concurrency, tags, session_template, state, state_reason, state_changed_at, ban_until, cooldown_until, consecutive_check_failures, last_check_at, last_check_ok, last_latency_ms, exit_ip, next_check_at, created_at, updated_at FROM proxies WHERE id = ANY($1::text[]) ORDER BY id FOR UPDATE
`

func (q *Queries) ProxyGetManyForUpdate(ctx context.Context, ids []string) ([]Proxy, error) {
	rows, err := q.db.Query(ctx, proxyGetManyForUpdate, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Proxy{}
	for rows.Next() {
		var i Proxy
		if err := rows.Scan(
			&i.ID,
			&i.Hkey,
			&i.NamespaceID,
			&i.Scheme,
			&i.Host,
			&i.Port,
			&i.UsernameHint,
			&i.DisplayUrl,
			&i.UrlHash,
			&i.UrlCiphertext,
			&i.UrlWrappedDek,
			&i.UrlKekID,
			&i.UrlVersion,
			&i.Kind,
			&i.Region,
			&i.City,
			&i.Provider,
			&i.MaxConcurrency,
			&i.Tags,
			&i.SessionTemplate,
			&i.State,
			&i.StateReason,
			&i.StateChangedAt,
			&i.BanUntil,
			&i.CooldownUntil,
			&i.ConsecutiveCheckFailures,
			&i.LastCheckAt,
			&i.LastCheckOk,
			&i.LastLatencyMs,
			&i.ExitIp,
			&i.NextCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const proxyInsertBatch = `-- name: ProxyInsertBatch :many
INSERT INTO proxies (
    id, namespace_id, scheme, host, port, username_hint, display_url, url_hash,
    url_ciphertext, url_wrapped_dek, url_kek_id, kind, region, city, provider,
    max_concurrency, tags, session_template
)
SELECT
    u.id, $1::text, u.scheme, u.host, u.port, u.username_hint, u.display_url, u.url_hash,
    u.url_ciphertext, u.url_wrapped_dek, u.url_kek_id, u.kind, u.region, u.city, u.provider,
    u.max_concurrency, CASE WHEN u.tags = '' THEN '{}'::text[] ELSE string_to_array(u.tags, ',') END,
    u.session_template
FROM (
    SELECT
        unnest($2::text[]) AS id,
        unnest($3::text[]) AS scheme,
        unnest($4::text[]) AS host,
        unnest($5::integer[]) AS port,
        unnest($6::text[]) AS username_hint,
        unnest($7::text[]) AS display_url,
        unnest($8::bytea[]) AS url_hash,
        unnest($9::bytea[]) AS url_ciphertext,
        unnest($10::bytea[]) AS url_wrapped_dek,
        unnest($11::text[]) AS url_kek_id,
        unnest($12::text[]) AS kind,
        unnest($13::text[]) AS region,
        unnest($14::text[]) AS city,
        unnest($15::text[]) AS provider,
        unnest($16::integer[]) AS max_concurrency,
        unnest($17::text[]) AS tags,
        unnest($18::text[]) AS session_template
) AS u
ON CONFLICT (namespace_id, url_hash) DO NOTHING
RETURNING id
`

type ProxyInsertBatchParams struct {
	NamespaceID      string   `json:"namespace_id"`
	Ids              []string `json:"ids"`
	Schemes          []string `json:"schemes"`
	Hosts            []string `json:"hosts"`
	Ports            []int32  `json:"ports"`
	UsernameHints    []string `json:"username_hints"`
	DisplayUrls      []string `json:"display_urls"`
	UrlHashes        [][]byte `json:"url_hashes"`
	UrlCiphertexts   [][]byte `json:"url_ciphertexts"`
	UrlWrappedDeks   [][]byte `json:"url_wrapped_deks"`
	UrlKekIds        []string `json:"url_kek_ids"`
	Kinds            []string `json:"kinds"`
	Regions          []string `json:"regions"`
	Cities           []string `json:"cities"`
	Providers        []string `json:"providers"`
	MaxConcurrencies []int32  `json:"max_concurrencies"`
	Tags             []string `json:"tags"`
	SessionTemplates []string `json:"session_templates"`
}

// Tags are passed as comma-joined strings because PostgreSQL cannot unnest
// arrays of arrays; tags never contain commas.
func (q *Queries) ProxyInsertBatch(ctx context.Context, arg ProxyInsertBatchParams) ([]string, error) {
	rows, err := q.db.Query(ctx, proxyInsertBatch,
		arg.NamespaceID,
		arg.Ids,
		arg.Schemes,
		arg.Hosts,
		arg.Ports,
		arg.UsernameHints,
		arg.DisplayUrls,
		arg.UrlHashes,
		arg.UrlCiphertexts,
		arg.UrlWrappedDeks,
		arg.UrlKekIds,
		arg.Kinds,
		arg.Regions,
		arg.Cities,
		arg.Providers,
		arg.MaxConcurrencies,
		arg.Tags,
		arg.SessionTemplates,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type ProxyInsertStateEventsParams struct {
	ID          string          `json:"id"`
	CreatedAt   time.Time       `json:"created_at"`
	TenantID    string          `json:"tenant_id"`
	NamespaceID string          `json:"namespace_id"`
	SiteID      string          `json:"site_id"`
	SubjectKind string          `json:"subject_kind"`
	SubjectID   string          `json:"subject_id"`
	FromState   string          `json:"from_state"`
	ToState     string          `json:"to_state"`
	Action      string          `json:"action"`
	Scope       string          `json:"scope"`
	Until       *time.Time      `json:"until"`
	Permanent   bool            `json:"permanent"`
	Actor       string          `json:"actor"`
	Reason      string          `json:"reason"`
	Details     json.RawMessage `json:"details"`
}

const proxyList = `-- name: ProxyList :many
SELECT id, hkey, namespace_id, scheme, host, port, username_hint, display_url, url_hash, url_ciphertext, url_wrapped_dek, url_kek_id, url_version, kind, region, city, provider, max_concurrency, tags, session_template, state, state_reason, state_changed_at, ban_until, cooldown_until, consecutive_check_failures, last_check_at, last_check_ok, last_latency_ms, exit_ip, next_check_at, created_at, updated_at FROM proxies
WHERE namespace_id = $1
  AND ((cardinality($2::text[]) = 0 AND state <> 'retired') OR state = ANY($2::text[]))
  AND (cardinality($3::text[]) = 0 OR kind = ANY($3::text[]))
  AND (cardinality($4::text[]) = 0 OR provider = ANY($4::text[]))
  AND (cardinality($5::text[]) = 0 OR region = ANY($5::text[]))
  AND tags @> $6::text[]
  AND ($7::text = ''
       OR display_url ILIKE $7::text
       OR host ILIKE $7::text
       OR exit_ip ILIKE $7::text
       OR id LIKE $8::text)
  AND ($9::text = '' OR id < $9::text)
ORDER BY id DESC
LIMIT $10::integer
`

type ProxyListParams struct {
	NamespaceID     string   `json:"namespace_id"`
	States          []string `json:"states"`
	Kinds           []string `json:"kinds"`
	Providers       []string `json:"providers"`
	Regions         []string `json:"regions"`
	Tags            []string `json:"tags"`
	SearchPattern   string   `json:"search_pattern"`
	IDPrefixPattern string   `json:"id_prefix_pattern"`
	AfterID         string   `json:"after_id"`
	PageLimit       int32    `json:"page_limit"`
}

func (q *Queries) ProxyList(ctx context.Context, arg ProxyListParams) ([]Proxy, error) {
	rows, err := q.db.Query(ctx, proxyList,
		arg.NamespaceID,
		arg.States,
		arg.Kinds,
		arg.Providers,
		arg.Regions,
		arg.Tags,
		arg.SearchPattern,
		arg.IDPrefixPattern,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Proxy{}
	for rows.Next() {
		var i Proxy
		if err := rows.Scan(
			&i.ID,
			&i.Hkey,
			&i.NamespaceID,
			&i.Scheme,
			&i.Host,
			&i.Port,
			&i.UsernameHint,
			&i.DisplayUrl,
			&i.UrlHash,
			&i.UrlCiphertext,
			&i.UrlWrappedDek,
			&i.UrlKekID,
			&i.UrlVersion,
			&i.Kind,
			&i.Region,
			&i.City,
			&i.Provider,
			&i.MaxConcurrency,
			&i.Tags,
			&i.SessionTemplate,
			&i.State,
			&i.StateReason,
			&i.StateChangedAt,
			&i.BanUntil,
			&i.CooldownUntil,
			&i.ConsecutiveCheckFailures,
			&i.LastCheckAt,
			&i.LastCheckOk,
			&i.LastLatencyMs,
			&i.ExitIp,
			&i.NextCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const proxyProviderCounts = `-- name: ProxyProviderCounts :many
SELECT
    provider,
    (count(*) FILTER (WHERE state <> 'retired'))::integer AS proxies,
    (count(*) FILTER (WHERE state = 'active'))::integer AS active,
    (count(*) FILTER (WHERE state = 'dead'))::integer AS dead
FROM proxies
WHERE namespace_id = $1
GROUP BY provider
`

type ProxyProviderCountsRow struct {
	Provider string `json:"provider"`
	Proxies  int32  `json:"proxies"`
	Active   int32  `json:"active"`
	Dead     int32  `json:"dead"`
}

func (q *Queries) ProxyProviderCounts(ctx context.Context, namespaceID string) ([]ProxyProviderCountsRow, error) {
	rows, err := q.db.Query(ctx, proxyProviderCounts, namespaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProxyProviderCountsRow{}
	for rows.Next() {
		var i ProxyProviderCountsRow
		if err := rows.Scan(
			&i.Provider,
			&i.Proxies,
			&i.Active,
			&i.Dead,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const proxyProviderOutcomes = `-- name: ProxyProviderOutcomes :many
SELECT
    p.provider,
    coalesce(sum(o.count), 0)::bigint AS requests,
    coalesce(sum(o.count) FILTER (WHERE o.outcome = 'success'), 0)::bigint AS successes,
    coalesce(sum(o.count) FILTER (WHERE o.outcome = ANY($1::text[])), 0)::bigint AS risks,
    coalesce(sum(o.latency_ms_sum), 0)::bigint AS latency_ms_sum
FROM outcome_stats_minutely AS o
JOIN proxies AS p ON p.id = o.proxy_id AND p.namespace_id = o.namespace_id
WHERE o.namespace_id = $2
  AND o.bucket >= $3::timestamptz
  AND o.bucket < $4::timestamptz
  AND o.proxy_id <> ''
  AND ($5::boolean OR o.site_id = ANY($6::text[]))
GROUP BY p.provider
`

type ProxyProviderOutcomesParams struct {
	RiskOutcomes []string  `json:"risk_outcomes"`
	NamespaceID  string    `json:"namespace_id"`
	RangeStart   time.Time `json:"range_start"`
	RangeEnd     time.Time `json:"range_end"`
	AllSites     bool      `json:"all_sites"`
	SiteIds      []string  `json:"site_ids"`
}

type ProxyProviderOutcomesRow struct {
	Provider     string `json:"provider"`
	Requests     int64  `json:"requests"`
	Successes    int64  `json:"successes"`
	Risks        int64  `json:"risks"`
	LatencyMsSum int64  `json:"latency_ms_sum"`
}

func (q *Queries) ProxyProviderOutcomes(ctx context.Context, arg ProxyProviderOutcomesParams) ([]ProxyProviderOutcomesRow, error) {
	rows, err := q.db.Query(ctx, proxyProviderOutcomes,
		arg.RiskOutcomes,
		arg.NamespaceID,
		arg.RangeStart,
		arg.RangeEnd,
		arg.AllSites,
		arg.SiteIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProxyProviderOutcomesRow{}
	for rows.Next() {
		var i ProxyProviderOutcomesRow
		if err := rows.Scan(
			&i.Provider,
			&i.Requests,
			&i.Successes,
			&i.Risks,
			&i.LatencyMsSum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const proxyRecordCheck = `-- name: ProxyRecordCheck :exec
UPDATE proxies SET
    last_check_at = $1,
    last_check_ok = $2,
    last_latency_ms = $3,
    exit_ip = $4,
    consecutive_check_failures = $5,
    state = $6,
    state_reason = $7,
    state_changed_at = $8,
    next_check_at = $9,
    region = $10,
    city = $11,
    updated_at = $1
WHERE id = $12
`

type ProxyRecordCheckParams struct {
	CheckedAt                *time.Time `json:"checked_at"`
	Ok                       *bool      `json:"ok"`
	LastLatencyMs            *int32     `json:"last_latency_ms"`
	ExitIp                   string     `json:"exit_ip"`
	ConsecutiveCheckFailures int32      `json:"consecutive_check_failures"`
	State                    string     `json:"state"`
	StateReason              string     `json:"state_reason"`
	StateChangedAt           time.Time  `json:"state_changed_at"`
	NextCheckAt              time.Time  `json:"next_check_at"`
	Region                   string     `json:"region"`
	City                     string     `json:"city"`
	ID                       string     `json:"id"`
}

func (q *Queries) ProxyRecordCheck(ctx context.Context, arg ProxyRecordCheckParams) error {
	_, err := q.db.Exec(ctx, proxyRecordCheck,
		arg.CheckedAt,
		arg.Ok,
		arg.LastLatencyMs,
		arg.ExitIp,
		arg.ConsecutiveCheckFailures,
		arg.State,
		arg.StateReason,
		arg.StateChangedAt,
		arg.NextCheckAt,
		arg.Region,
		arg.City,
		arg.ID,
	)
	return err
}

const proxyResolveLoad = `-- name: ProxyResolveLoad :one
SELECT namespace_id, url_ciphertext, url_wrapped_dek, url_kek_id, url_version, kind, region, session_template
FROM proxies
WHERE id = $1
`

type ProxyResolveLoadRow struct {
	NamespaceID     string `json:"namespace_id"`
	UrlCiphertext   []byte `json:"url_ciphertext"`
	UrlWrappedDek   []byte `json:"url_wrapped_dek"`
	UrlKekID        string `json:"url_kek_id"`
	UrlVersion      int32  `json:"url_version"`
	Kind            string `json:"kind"`
	Region          string `json:"region"`
	SessionTemplate string `json:"session_template"`
}

func (q *Queries) ProxyResolveLoad(ctx context.Context, id string) (ProxyResolveLoadRow, error) {
	row := q.db.QueryRow(ctx, proxyResolveLoad, id)
	var i ProxyResolveLoadRow
	err := row.Scan(
		&i.NamespaceID,
		&i.UrlCiphertext,
		&i.UrlWrappedDek,
		&i.UrlKekID,
		&i.UrlVersion,
		&i.Kind,
		&i.Region,
		&i.SessionTemplate,
	)
	return i, err
}

const proxyUpdate = `-- name: ProxyUpdate :one
UPDATE proxies SET
    scheme = $1,
    host = $2,
    port = $3,
    username_hint = $4,
    display_url = $5,
    url_hash = $6,
    url_ciphertext = $7,
    url_wrapped_dek = $8,
    url_kek_id = $9,
    url_version = $10,
    kind = $11,
    region = $12,
    city = $13,
    provider = $14,
    max_concurrency = $15,
    tags = $16::text[],
    session_template = $17,
    updated_at = now()
WHERE id = $18
RETURNING id, hkey, namespace_id, scheme, host, port, username_hint, display_url, url_hash, url_ciphertext, url_wrapped_dek, url_kek_id, url_version, kind, region, city, provider, max_concurrency, tags, session_template, state, state_reason, state_changed_at, ban_until, cooldown_until, consecutive_check_failures, last_check_at, last_check_ok, last_latency_ms, exit_ip, next_check_at, created_at, updated_at
`

type ProxyUpdateParams struct {
	Scheme          string   `json:"scheme"`
	Host            string   `json:"host"`
	Port            int32    `json:"port"`
	UsernameHint    string   `json:"username_hint"`
	DisplayUrl      string   `json:"display_url"`
	UrlHash         []byte   `json:"url_hash"`
	UrlCiphertext   []byte   `json:"url_ciphertext"`
	UrlWrappedDek   []byte   `json:"url_wrapped_dek"`
	UrlKekID        string   `json:"url_kek_id"`
	UrlVersion      int32    `json:"url_version"`
	Kind            string   `json:"kind"`
	Region          string   `json:"region"`
	City            string   `json:"city"`
	Provider        string   `json:"provider"`
	MaxConcurrency  int32    `json:"max_concurrency"`
	Tags            []string `json:"tags"`
	SessionTemplate string   `json:"session_template"`
	ID              string   `json:"id"`
}

func (q *Queries) ProxyUpdate(ctx context.Context, arg ProxyUpdateParams) (Proxy, error) {
	row := q.db.QueryRow(ctx, proxyUpdate,
		arg.Scheme,
		arg.Host,
		arg.Port,
		arg.UsernameHint,
		arg.DisplayUrl,
		arg.UrlHash,
		arg.UrlCiphertext,
		arg.UrlWrappedDek,
		arg.UrlKekID,
		arg.UrlVersion,
		arg.Kind,
		arg.Region,
		arg.City,
		arg.Provider,
		arg.MaxConcurrency,
		arg.Tags,
		arg.SessionTemplate,
		arg.ID,
	)
	var i Proxy
	err := row.Scan(
		&i.ID,
		&i.Hkey,
		&i.NamespaceID,
		&i.Scheme,
		&i.Host,
		&i.Port,
		&i.UsernameHint,
		&i.DisplayUrl,
		&i.UrlHash,
		&i.UrlCiphertext,
		&i.UrlWrappedDek,
		&i.UrlKekID,
		&i.UrlVersion,
		&i.Kind,
		&i.Region,
		&i.City,
		&i.Provider,
		&i.MaxConcurrency,
		&i.Tags,
		&i.SessionTemplate,
		&i.State,
		&i.StateReason,
		&i.StateChangedAt,
		&i.BanUntil,
		&i.CooldownUntil,
		&i.ConsecutiveCheckFailures,
		&i.LastCheckAt,
		&i.LastCheckOk,
		&i.LastLatencyMs,
		&i.ExitIp,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const proxyUpdateAttributesBatch = `-- name: ProxyUpdateAttributesBatch :exec
UPDATE proxies AS p SET
    kind = u.kind,
    region = u.region,
    city = u.city,
    provider = u.provider,
    max_concurrency = u.max_concurrency,
    tags = CASE WHEN u.tags = '' THEN '{}'::text[] ELSE string_to_array(u.tags, ',') END,
    session_template = u.session_template,
    updated_at = now()
FROM (
    SELECT
        unnest($2::text[]) AS id,
        unnest($3::text[]) AS kind,
        unnest($4::text[]) AS region,
        unnest($5::text[]) AS city,
        unnest($6::text[]) AS provider,
        unnest($7::integer[]) AS max_concurrency,
        unnest($8::text[]) AS tags,
        unnest($9::text[]) AS session_template
) AS u
WHERE p.id = u.id AND p.namespace_id = $1::text
`

type ProxyUpdateAttributesBatchParams struct {
	NamespaceID      string   `json:"namespace_id"`
	Ids              []string `json:"ids"`
	Kinds            []string `json:"kinds"`
	Regions          []string `json:"regions"`
	Cities           []string `json:"cities"`
	Providers        []string `json:"providers"`
	MaxConcurrencies []int32  `json:"max_concurrencies"`
	Tags             []string `json:"tags"`
	SessionTemplates []string `json:"session_templates"`
}

func (q *Queries) ProxyUpdateAttributesBatch(ctx context.Context, arg ProxyUpdateAttributesBatchParams) error {
	_, err := q.db.Exec(ctx, proxyUpdateAttributesBatch,
		arg.NamespaceID,
		arg.Ids,
		arg.Kinds,
		arg.Regions,
		arg.Cities,
		arg.Providers,
		arg.MaxConcurrencies,
		arg.Tags,
		arg.SessionTemplates,
	)
	return err
}
