// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package actiondb

import (
	"context"
	"time"
)

const actionCooldownAccount = `-- name: ActionCooldownAccount :one
UPDATE accounts
SET cooldown_until = GREATEST(COALESCE(cooldown_until, $1::timestamptz), $1::timestamptz),
    updated_at     = $2::timestamptz
WHERE id = $3::text
RETURNING id, hkey, state, cooldown_until
`

type ActionCooldownAccountParams struct {
	Until     time.Time `json:"until"`
	ChangedAt time.Time `json:"changed_at"`
	ID        string    `json:"id"`
}

type ActionCooldownAccountRow struct {
	ID            string     `json:"id"`
	Hkey          int64      `json:"hkey"`
	State         string     `json:"state"`
	CooldownUntil *time.Time `json:"cooldown_until"`
}

func (q *Queries) ActionCooldownAccount(ctx context.Context, arg ActionCooldownAccountParams) (ActionCooldownAccountRow, error) {
	row := q.db.QueryRow(ctx, actionCooldownAccount, arg.Until, arg.ChangedAt, arg.ID)
	var i ActionCooldownAccountRow
	err := row.Scan(
		&i.ID,
		&i.Hkey,
		&i.State,
		&i.CooldownUntil,
	)
	return i, err
}

const actionCountAccountMembers = `-- name: ActionCountAccountMembers :one
SELECT count(*)::int AS members FROM identities WHERE account_id = $1::text
`

func (q *Queries) ActionCountAccountMembers(ctx context.Context, accountID string) (int32, error) {
	row := q.db.QueryRow(ctx, actionCountAccountMembers, accountID)
	var members int32
	err := row.Scan(&members)
	return members, err
}

const actionLoadAccount = `-- name: ActionLoadAccount :one

SELECT a.id, a.hkey, a.site_id, a.state, a.ban_until, a.cooldown_until
FROM accounts AS a
JOIN sites AS s ON s.id = a.site_id
WHERE a.id = $1
  AND s.namespace_id = $2
`

type ActionLoadAccountParams struct {
	ID          string `json:"id"`
	NamespaceID string `json:"namespace_id"`
}

type ActionLoadAccountRow struct {
	ID            string     `json:"id"`
	Hkey          int64      `json:"hkey"`
	SiteID        string     `json:"site_id"`
	State         string     `json:"state"`
	BanUntil      *time.Time `json:"ban_until"`
	CooldownUntil *time.Time `json:"cooldown_until"`
}

// Manual account operations (Operator).
func (q *Queries) ActionLoadAccount(ctx context.Context, arg ActionLoadAccountParams) (ActionLoadAccountRow, error) {
	row := q.db.QueryRow(ctx, actionLoadAccount, arg.ID, arg.NamespaceID)
	var i ActionLoadAccountRow
	err := row.Scan(
		&i.ID,
		&i.Hkey,
		&i.SiteID,
		&i.State,
		&i.BanUntil,
		&i.CooldownUntil,
	)
	return i, err
}

const actionTransitionAccount = `-- name: ActionTransitionAccount :one
UPDATE accounts AS a
SET state      = $1::text,
    ban_until  = $2::timestamptz,
    updated_at = $3::timestamptz
FROM (
    SELECT x.id, x.state
    FROM accounts AS x
    WHERE x.id = $4::text
      AND x.state = ANY($5::text[])
    FOR UPDATE
) AS prev
WHERE a.id = prev.id
RETURNING a.id, a.hkey, prev.state AS from_state
`

type ActionTransitionAccountParams struct {
	ToState    string     `json:"to_state"`
	BanUntil   *time.Time `json:"ban_until"`
	ChangedAt  time.Time  `json:"changed_at"`
	ID         string     `json:"id"`
	FromStates []string   `json:"from_states"`
}

type ActionTransitionAccountRow struct {
	ID        string `json:"id"`
	Hkey      int64  `json:"hkey"`
	FromState string `json:"from_state"`
}

func (q *Queries) ActionTransitionAccount(ctx context.Context, arg ActionTransitionAccountParams) (ActionTransitionAccountRow, error) {
	row := q.db.QueryRow(ctx, actionTransitionAccount,
		arg.ToState,
		arg.BanUntil,
		arg.ChangedAt,
		arg.ID,
		arg.FromStates,
	)
	var i ActionTransitionAccountRow
	err := row.Scan(&i.ID, &i.Hkey, &i.FromState)
	return i, err
}
