// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expiry.sql

package actiondb

import (
	"context"
	"time"
)

const actionDueIdentityBans = `-- name: ActionDueIdentityBans :many

SELECT i.id, i.site_id, i.client
FROM identities AS i
WHERE i.state = 'banned'
  AND i.ban_until IS NOT NULL
  AND i.ban_until <= $1::timestamptz
  AND NOT EXISTS (
      SELECT 1 FROM accounts AS a
      WHERE a.id = i.account_id
        AND a.state = 'banned'
        AND (a.ban_until IS NULL OR a.ban_until > $1::timestamptz)
  )
ORDER BY i.ban_until
LIMIT $2::int
`

type ActionDueIdentityBansParams struct {
	Now     time.Time `json:"now"`
	MaxRows int32     `json:"max_rows"`
}

type ActionDueIdentityBansRow struct {
	ID     string `json:"id"`
	SiteID string `json:"site_id"`
	Client string `json:"client"`
}

// Ban / quarantine expiry (leader job, spec §6.8).
func (q *Queries) ActionDueIdentityBans(ctx context.Context, arg ActionDueIdentityBansParams) ([]ActionDueIdentityBansRow, error) {
	rows, err := q.db.Query(ctx, actionDueIdentityBans, arg.Now, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionDueIdentityBansRow{}
	for rows.Next() {
		var i ActionDueIdentityBansRow
		if err := rows.Scan(&i.ID, &i.SiteID, &i.Client); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const actionNamespaceTenants = `-- name: ActionNamespaceTenants :many
SELECT id, tenant_id FROM namespaces WHERE id = ANY($1::text[])
`

type ActionNamespaceTenantsRow struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) ActionNamespaceTenants(ctx context.Context, namespaceIds []string) ([]ActionNamespaceTenantsRow, error) {
	rows, err := q.db.Query(ctx, actionNamespaceTenants, namespaceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionNamespaceTenantsRow{}
	for rows.Next() {
		var i ActionNamespaceTenantsRow
		if err := rows.Scan(&i.ID, &i.TenantID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const actionRecentExpiryReleases = `-- name: ActionRecentExpiryReleases :many
SELECT DISTINCT e.subject_kind, e.subject_id, e.site_id, e.namespace_id
FROM state_events AS e
WHERE e.action IN ('unban', 'unquarantine')
  AND e.actor = 'system'
  AND e.reason IN ('ban_expired', 'quarantine_expired')
  AND e.shadow = false
  AND e.created_at >= $1::timestamptz
LIMIT $2::int
`

type ActionRecentExpiryReleasesParams struct {
	Since   time.Time `json:"since"`
	MaxRows int32     `json:"max_rows"`
}

type ActionRecentExpiryReleasesRow struct {
	SubjectKind string `json:"subject_kind"`
	SubjectID   string `json:"subject_id"`
	SiteID      string `json:"site_id"`
	NamespaceID string `json:"namespace_id"`
}

// Subjects released by the expiry job since a time; used to re-synchronize
// the hot state after a leadership change (releases whose Redis push may have
// failed on the previous leader).
func (q *Queries) ActionRecentExpiryReleases(ctx context.Context, arg ActionRecentExpiryReleasesParams) ([]ActionRecentExpiryReleasesRow, error) {
	rows, err := q.db.Query(ctx, actionRecentExpiryReleases, arg.Since, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionRecentExpiryReleasesRow{}
	for rows.Next() {
		var i ActionRecentExpiryReleasesRow
		if err := rows.Scan(
			&i.SubjectKind,
			&i.SubjectID,
			&i.SiteID,
			&i.NamespaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const actionReleaseDueAccountBans = `-- name: ActionReleaseDueAccountBans :many
UPDATE accounts AS a
SET state      = 'active',
    ban_until  = NULL,
    updated_at = $1::timestamptz
FROM (
    SELECT x.id, x.state
    FROM accounts AS x
    WHERE x.state = 'banned'
      AND x.ban_until IS NOT NULL
      AND x.ban_until <= $1::timestamptz
    ORDER BY x.ban_until
    LIMIT $2::int
    FOR UPDATE SKIP LOCKED
) AS prev
WHERE a.id = prev.id
RETURNING a.id, a.hkey, a.site_id, prev.state AS from_state
`

type ActionReleaseDueAccountBansParams struct {
	Now     time.Time `json:"now"`
	MaxRows int32     `json:"max_rows"`
}

type ActionReleaseDueAccountBansRow struct {
	ID        string `json:"id"`
	Hkey      int64  `json:"hkey"`
	SiteID    string `json:"site_id"`
	FromState string `json:"from_state"`
}

func (q *Queries) ActionReleaseDueAccountBans(ctx context.Context, arg ActionReleaseDueAccountBansParams) ([]ActionReleaseDueAccountBansRow, error) {
	rows, err := q.db.Query(ctx, actionReleaseDueAccountBans, arg.Now, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionReleaseDueAccountBansRow{}
	for rows.Next() {
		var i ActionReleaseDueAccountBansRow
		if err := rows.Scan(
			&i.ID,
			&i.Hkey,
			&i.SiteID,
			&i.FromState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const actionReleaseDueBans = `-- name: ActionReleaseDueBans :many
UPDATE identities AS i
SET state            = $1::text,
    state_reason     = $2::text,
    state_changed_at = $3::timestamptz,
    ban_until        = NULL,
    quarantine_until = NULL,
    activated_at     = CASE WHEN $1::text = 'active' THEN $3::timestamptz ELSE i.activated_at END,
    updated_at       = $3::timestamptz
FROM (
    SELECT x.id, x.state
    FROM identities AS x
    WHERE x.id = ANY($4::text[])
      AND x.state = 'banned'
      AND x.ban_until IS NOT NULL
      AND x.ban_until <= $3::timestamptz
    FOR UPDATE SKIP LOCKED
) AS prev
WHERE i.id = prev.id
RETURNING i.id, i.hkey, i.site_id, i.client, i.type_id, prev.state AS from_state
`

type ActionReleaseDueBansParams struct {
	ToState string    `json:"to_state"`
	Reason  string    `json:"reason"`
	Now     time.Time `json:"now"`
	Ids     []string  `json:"ids"`
}

type ActionReleaseDueBansRow struct {
	ID        string `json:"id"`
	Hkey      int64  `json:"hkey"`
	SiteID    string `json:"site_id"`
	Client    string `json:"client"`
	TypeID    string `json:"type_id"`
	FromState string `json:"from_state"`
}

func (q *Queries) ActionReleaseDueBans(ctx context.Context, arg ActionReleaseDueBansParams) ([]ActionReleaseDueBansRow, error) {
	rows, err := q.db.Query(ctx, actionReleaseDueBans,
		arg.ToState,
		arg.Reason,
		arg.Now,
		arg.Ids,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionReleaseDueBansRow{}
	for rows.Next() {
		var i ActionReleaseDueBansRow
		if err := rows.Scan(
			&i.ID,
			&i.Hkey,
			&i.SiteID,
			&i.Client,
			&i.TypeID,
			&i.FromState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const actionReleaseDueProxies = `-- name: ActionReleaseDueProxies :many
UPDATE proxies AS p
SET state            = 'active',
    state_reason     = $1::text,
    state_changed_at = $2::timestamptz,
    ban_until        = NULL,
    updated_at       = $2::timestamptz
FROM (
    SELECT x.id, x.state
    FROM proxies AS x
    WHERE x.state IN ('banned', 'quarantined')
      AND x.ban_until IS NOT NULL
      AND x.ban_until <= $2::timestamptz
    ORDER BY x.ban_until
    LIMIT $3::int
    FOR UPDATE SKIP LOCKED
) AS prev
WHERE p.id = prev.id
RETURNING p.id, p.hkey, p.namespace_id, prev.state AS from_state
`

type ActionReleaseDueProxiesParams struct {
	Reason  string    `json:"reason"`
	Now     time.Time `json:"now"`
	MaxRows int32     `json:"max_rows"`
}

type ActionReleaseDueProxiesRow struct {
	ID          string `json:"id"`
	Hkey        int64  `json:"hkey"`
	NamespaceID string `json:"namespace_id"`
	FromState   string `json:"from_state"`
}

func (q *Queries) ActionReleaseDueProxies(ctx context.Context, arg ActionReleaseDueProxiesParams) ([]ActionReleaseDueProxiesRow, error) {
	rows, err := q.db.Query(ctx, actionReleaseDueProxies, arg.Reason, arg.Now, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionReleaseDueProxiesRow{}
	for rows.Next() {
		var i ActionReleaseDueProxiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Hkey,
			&i.NamespaceID,
			&i.FromState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const actionReleaseDueQuarantines = `-- name: ActionReleaseDueQuarantines :many
UPDATE identities AS i
SET state            = 'pending',
    state_reason     = $1::text,
    state_changed_at = $2::timestamptz,
    ban_until        = NULL,
    quarantine_until = NULL,
    updated_at       = $2::timestamptz
FROM (
    SELECT x.id, x.state
    FROM identities AS x
    WHERE x.state = 'quarantined'
      AND x.quarantine_until IS NOT NULL
      AND x.quarantine_until <= $2::timestamptz
    ORDER BY x.quarantine_until
    LIMIT $3::int
    FOR UPDATE SKIP LOCKED
) AS prev
WHERE i.id = prev.id
RETURNING i.id, i.hkey, i.site_id, i.client, i.type_id, prev.state AS from_state
`

type ActionReleaseDueQuarantinesParams struct {
	Reason  string    `json:"reason"`
	Now     time.Time `json:"now"`
	MaxRows int32     `json:"max_rows"`
}

type ActionReleaseDueQuarantinesRow struct {
	ID        string `json:"id"`
	Hkey      int64  `json:"hkey"`
	SiteID    string `json:"site_id"`
	Client    string `json:"client"`
	TypeID    string `json:"type_id"`
	FromState string `json:"from_state"`
}

func (q *Queries) ActionReleaseDueQuarantines(ctx context.Context, arg ActionReleaseDueQuarantinesParams) ([]ActionReleaseDueQuarantinesRow, error) {
	rows, err := q.db.Query(ctx, actionReleaseDueQuarantines, arg.Reason, arg.Now, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionReleaseDueQuarantinesRow{}
	for rows.Next() {
		var i ActionReleaseDueQuarantinesRow
		if err := rows.Scan(
			&i.ID,
			&i.Hkey,
			&i.SiteID,
			&i.Client,
			&i.TypeID,
			&i.FromState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const actionSiteTenancy = `-- name: ActionSiteTenancy :many
SELECT s.id, s.namespace_id, n.tenant_id
FROM sites AS s
JOIN namespaces AS n ON n.id = s.namespace_id
WHERE s.id = ANY($1::text[])
`

type ActionSiteTenancyRow struct {
	ID          string `json:"id"`
	NamespaceID string `json:"namespace_id"`
	TenantID    string `json:"tenant_id"`
}

func (q *Queries) ActionSiteTenancy(ctx context.Context, siteIds []string) ([]ActionSiteTenancyRow, error) {
	rows, err := q.db.Query(ctx, actionSiteTenancy, siteIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionSiteTenancyRow{}
	for rows.Next() {
		var i ActionSiteTenancyRow
		if err := rows.Scan(&i.ID, &i.NamespaceID, &i.TenantID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
