// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identities.sql

package actiondb

import (
	"context"
	"time"
)

const actionAccountIDsByKeys = `-- name: ActionAccountIDsByKeys :many
SELECT id, hkey FROM accounts WHERE hkey = ANY($1::bigint[])
`

type ActionAccountIDsByKeysRow struct {
	ID   string `json:"id"`
	Hkey int64  `json:"hkey"`
}

func (q *Queries) ActionAccountIDsByKeys(ctx context.Context, hkeys []int64) ([]ActionAccountIDsByKeysRow, error) {
	rows, err := q.db.Query(ctx, actionAccountIDsByKeys, hkeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionAccountIDsByKeysRow{}
	for rows.Next() {
		var i ActionAccountIDsByKeysRow
		if err := rows.Scan(&i.ID, &i.Hkey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const actionBanAccountMembers = `-- name: ActionBanAccountMembers :many
UPDATE identities AS i
SET state            = 'banned',
    state_reason     = $1::text,
    state_changed_at = $2::timestamptz,
    ban_until        = $3::timestamptz,
    quarantine_until = NULL,
    updated_at       = $2::timestamptz
FROM (
    SELECT x.id, x.state
    FROM identities AS x
    WHERE x.account_id = $4::text
      AND (
          x.state IN ('active', 'pending', 'quarantined', 'expired')
          -- Members disabled only because the account was disabled follow the
          -- account into the ban (and are released by its unban).
          OR (x.state = 'disabled' AND x.state_reason = 'account_disabled')
          OR (x.state = 'banned' AND x.ban_until IS NOT NULL
              AND ($3::timestamptz IS NULL OR x.ban_until < $3::timestamptz))
      )
    FOR UPDATE
) AS prev
WHERE i.id = prev.id
RETURNING i.id, i.hkey, i.client, i.type_id, prev.state AS from_state
`

type ActionBanAccountMembersParams struct {
	Reason    string     `json:"reason"`
	ChangedAt time.Time  `json:"changed_at"`
	BanUntil  *time.Time `json:"ban_until"`
	AccountID string     `json:"account_id"`
}

type ActionBanAccountMembersRow struct {
	ID        string `json:"id"`
	Hkey      int64  `json:"hkey"`
	Client    string `json:"client"`
	TypeID    string `json:"type_id"`
	FromState string `json:"from_state"`
}

func (q *Queries) ActionBanAccountMembers(ctx context.Context, arg ActionBanAccountMembersParams) ([]ActionBanAccountMembersRow, error) {
	rows, err := q.db.Query(ctx, actionBanAccountMembers,
		arg.Reason,
		arg.ChangedAt,
		arg.BanUntil,
		arg.AccountID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionBanAccountMembersRow{}
	for rows.Next() {
		var i ActionBanAccountMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Hkey,
			&i.Client,
			&i.TypeID,
			&i.FromState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const actionIdentityIDsByKeys = `-- name: ActionIdentityIDsByKeys :many
SELECT id, hkey FROM identities WHERE hkey = ANY($1::bigint[])
`

type ActionIdentityIDsByKeysRow struct {
	ID   string `json:"id"`
	Hkey int64  `json:"hkey"`
}

func (q *Queries) ActionIdentityIDsByKeys(ctx context.Context, hkeys []int64) ([]ActionIdentityIDsByKeysRow, error) {
	rows, err := q.db.Query(ctx, actionIdentityIDsByKeys, hkeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionIdentityIDsByKeysRow{}
	for rows.Next() {
		var i ActionIdentityIDsByKeysRow
		if err := rows.Scan(&i.ID, &i.Hkey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const actionLoadIdentities = `-- name: ActionLoadIdentities :many

SELECT i.id, i.hkey, i.site_id, i.client, i.type_id, i.account_id, i.state, i.state_changed_at
FROM identities AS i
JOIN sites AS s ON s.id = i.site_id
WHERE s.namespace_id = $1
  AND i.id = ANY($2::text[])
`

type ActionLoadIdentitiesParams struct {
	NamespaceID string   `json:"namespace_id"`
	Ids         []string `json:"ids"`
}

type ActionLoadIdentitiesRow struct {
	ID             string    `json:"id"`
	Hkey           int64     `json:"hkey"`
	SiteID         string    `json:"site_id"`
	Client         string    `json:"client"`
	TypeID         string    `json:"type_id"`
	AccountID      *string   `json:"account_id"`
	State          string    `json:"state"`
	StateChangedAt time.Time `json:"state_changed_at"`
}

// Manual identity operations (Operator). Every transition locks the affected
// rows, re-checks the allowed source states and returns the previous state so
// that state events record the exact transition.
func (q *Queries) ActionLoadIdentities(ctx context.Context, arg ActionLoadIdentitiesParams) ([]ActionLoadIdentitiesRow, error) {
	rows, err := q.db.Query(ctx, actionLoadIdentities, arg.NamespaceID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionLoadIdentitiesRow{}
	for rows.Next() {
		var i ActionLoadIdentitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Hkey,
			&i.SiteID,
			&i.Client,
			&i.TypeID,
			&i.AccountID,
			&i.State,
			&i.StateChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const actionProxyIDsByKeys = `-- name: ActionProxyIDsByKeys :many
SELECT id, hkey FROM proxies WHERE hkey = ANY($1::bigint[])
`

type ActionProxyIDsByKeysRow struct {
	ID   string `json:"id"`
	Hkey int64  `json:"hkey"`
}

func (q *Queries) ActionProxyIDsByKeys(ctx context.Context, hkeys []int64) ([]ActionProxyIDsByKeysRow, error) {
	rows, err := q.db.Query(ctx, actionProxyIDsByKeys, hkeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionProxyIDsByKeysRow{}
	for rows.Next() {
		var i ActionProxyIDsByKeysRow
		if err := rows.Scan(&i.ID, &i.Hkey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const actionSetAccountMembersState = `-- name: ActionSetAccountMembersState :many
UPDATE identities AS i
SET state            = $1::text,
    state_reason     = $2::text,
    state_changed_at = $3::timestamptz,
    ban_until        = NULL,
    quarantine_until = NULL,
    activated_at     = CASE WHEN $1::text = 'active' THEN $3::timestamptz ELSE i.activated_at END,
    updated_at       = $3::timestamptz
FROM (
    SELECT x.id, x.state
    FROM identities AS x
    WHERE x.account_id = $4::text
      AND x.state = ANY($5::text[])
      AND ($6::text = '' OR x.state_reason = $6::text)
    FOR UPDATE
) AS prev
WHERE i.id = prev.id
RETURNING i.id, i.hkey, i.client, i.type_id, prev.state AS from_state
`

type ActionSetAccountMembersStateParams struct {
	ToState    string    `json:"to_state"`
	Reason     string    `json:"reason"`
	ChangedAt  time.Time `json:"changed_at"`
	AccountID  string    `json:"account_id"`
	FromStates []string  `json:"from_states"`
	OnlyReason string    `json:"only_reason"`
}

type ActionSetAccountMembersStateRow struct {
	ID        string `json:"id"`
	Hkey      int64  `json:"hkey"`
	Client    string `json:"client"`
	TypeID    string `json:"type_id"`
	FromState string `json:"from_state"`
}

func (q *Queries) ActionSetAccountMembersState(ctx context.Context, arg ActionSetAccountMembersStateParams) ([]ActionSetAccountMembersStateRow, error) {
	rows, err := q.db.Query(ctx, actionSetAccountMembersState,
		arg.ToState,
		arg.Reason,
		arg.ChangedAt,
		arg.AccountID,
		arg.FromStates,
		arg.OnlyReason,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionSetAccountMembersStateRow{}
	for rows.Next() {
		var i ActionSetAccountMembersStateRow
		if err := rows.Scan(
			&i.ID,
			&i.Hkey,
			&i.Client,
			&i.TypeID,
			&i.FromState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const actionTransitionIdentities = `-- name: ActionTransitionIdentities :many
UPDATE identities AS i
SET state            = $1::text,
    state_reason     = $2::text,
    state_changed_at = $3::timestamptz,
    ban_until        = $4::timestamptz,
    quarantine_until = $5::timestamptz,
    activated_at     = CASE WHEN $1::text = 'active' THEN $3::timestamptz ELSE i.activated_at END,
    updated_at       = $3::timestamptz
FROM (
    SELECT x.id, x.state
    FROM identities AS x
    WHERE x.id = ANY($6::text[])
      AND x.site_id = $7::text
      AND x.state = ANY($8::text[])
    FOR UPDATE
) AS prev
WHERE i.id = prev.id
RETURNING i.id, i.hkey, i.client, i.type_id, prev.state AS from_state
`

type ActionTransitionIdentitiesParams struct {
	ToState         string     `json:"to_state"`
	Reason          string     `json:"reason"`
	ChangedAt       time.Time  `json:"changed_at"`
	BanUntil        *time.Time `json:"ban_until"`
	QuarantineUntil *time.Time `json:"quarantine_until"`
	Ids             []string   `json:"ids"`
	SiteID          string     `json:"site_id"`
	FromStates      []string   `json:"from_states"`
}

type ActionTransitionIdentitiesRow struct {
	ID        string `json:"id"`
	Hkey      int64  `json:"hkey"`
	Client    string `json:"client"`
	TypeID    string `json:"type_id"`
	FromState string `json:"from_state"`
}

func (q *Queries) ActionTransitionIdentities(ctx context.Context, arg ActionTransitionIdentitiesParams) ([]ActionTransitionIdentitiesRow, error) {
	rows, err := q.db.Query(ctx, actionTransitionIdentities,
		arg.ToState,
		arg.Reason,
		arg.ChangedAt,
		arg.BanUntil,
		arg.QuarantineUntil,
		arg.Ids,
		arg.SiteID,
		arg.FromStates,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionTransitionIdentitiesRow{}
	for rows.Next() {
		var i ActionTransitionIdentitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Hkey,
			&i.Client,
			&i.TypeID,
			&i.FromState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
