// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: revert.sql

package actiondb

import (
	"context"
	"time"
)

const actionRevertAccountCandidates = `-- name: ActionRevertAccountCandidates :many
SELECT DISTINCT ON (e.subject_id)
       e.id, e.created_at, e.site_id, e.subject_id
FROM state_events AS e
JOIN accounts AS a ON a.id = e.subject_id
WHERE e.namespace_id = $1::text
  AND e.subject_kind = 'account'
  AND e.shadow = false
  AND e.actor = 'system'
  AND e.action = 'ban'
  AND e.site_id = ANY($2::text[])
  AND e.created_at >= $3::timestamptz
  AND e.created_at < $4::timestamptz
  AND ($5::text = '' OR e.policy_id = $5::text)
  AND ($6::text = '' OR e.rule = $6::text)
  AND a.state = 'banned'
  -- Still in the state produced by the event: no later lifecycle change of
  -- the account (every account transition records a state event in the same
  -- transaction; attribute edits and cooldowns do not change the state).
  AND NOT EXISTS (
      SELECT 1
      FROM state_events AS l
      WHERE l.subject_id = e.subject_id
        AND l.subject_kind = 'account'
        AND l.shadow = false
        AND l.action <> 'cooldown'
        AND l.created_at > e.created_at
  )
ORDER BY e.subject_id, e.created_at DESC
LIMIT $7::int
`

type ActionRevertAccountCandidatesParams struct {
	NamespaceID string    `json:"namespace_id"`
	SiteIds     []string  `json:"site_ids"`
	FromTs      time.Time `json:"from_ts"`
	ToTs        time.Time `json:"to_ts"`
	PolicyID    string    `json:"policy_id"`
	Rule        string    `json:"rule"`
	MaxRows     int32     `json:"max_rows"`
}

type ActionRevertAccountCandidatesRow struct {
	ID        string    `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	SiteID    string    `json:"site_id"`
	SubjectID string    `json:"subject_id"`
}

func (q *Queries) ActionRevertAccountCandidates(ctx context.Context, arg ActionRevertAccountCandidatesParams) ([]ActionRevertAccountCandidatesRow, error) {
	rows, err := q.db.Query(ctx, actionRevertAccountCandidates,
		arg.NamespaceID,
		arg.SiteIds,
		arg.FromTs,
		arg.ToTs,
		arg.PolicyID,
		arg.Rule,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionRevertAccountCandidatesRow{}
	for rows.Next() {
		var i ActionRevertAccountCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.SiteID,
			&i.SubjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const actionRevertCooldownCandidates = `-- name: ActionRevertCooldownCandidates :many
SELECT DISTINCT ON (e.subject_id, e.scope, e.endpoint_group_id)
       e.id, e.created_at, e.site_id, e.subject_id, e.endpoint_group_id, e.scope, e.until,
       i.hkey, i.client
FROM state_events AS e
JOIN identities AS i ON i.id = e.subject_id
WHERE e.namespace_id = $1::text
  AND e.subject_kind = 'identity'
  AND e.shadow = false
  AND e.actor = 'system'
  AND e.action = 'cooldown'
  AND e.scope IN ('identity_endpoint', 'identity_site')
  AND e.until IS NOT NULL
  AND e.until > $2::timestamptz
  AND e.site_id = ANY($3::text[])
  AND e.created_at >= $4::timestamptz
  AND e.created_at < $5::timestamptz
  AND ($6::text = '' OR e.policy_id = $6::text)
  AND ($7::text = '' OR e.rule = $7::text)
ORDER BY e.subject_id, e.scope, e.endpoint_group_id, e.created_at DESC
LIMIT $8::int
`

type ActionRevertCooldownCandidatesParams struct {
	NamespaceID string    `json:"namespace_id"`
	Now         time.Time `json:"now"`
	SiteIds     []string  `json:"site_ids"`
	FromTs      time.Time `json:"from_ts"`
	ToTs        time.Time `json:"to_ts"`
	PolicyID    string    `json:"policy_id"`
	Rule        string    `json:"rule"`
	MaxRows     int32     `json:"max_rows"`
}

type ActionRevertCooldownCandidatesRow struct {
	ID              string     `json:"id"`
	CreatedAt       time.Time  `json:"created_at"`
	SiteID          string     `json:"site_id"`
	SubjectID       string     `json:"subject_id"`
	EndpointGroupID string     `json:"endpoint_group_id"`
	Scope           string     `json:"scope"`
	Until           *time.Time `json:"until"`
	Hkey            int64      `json:"hkey"`
	Client          string     `json:"client"`
}

func (q *Queries) ActionRevertCooldownCandidates(ctx context.Context, arg ActionRevertCooldownCandidatesParams) ([]ActionRevertCooldownCandidatesRow, error) {
	rows, err := q.db.Query(ctx, actionRevertCooldownCandidates,
		arg.NamespaceID,
		arg.Now,
		arg.SiteIds,
		arg.FromTs,
		arg.ToTs,
		arg.PolicyID,
		arg.Rule,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionRevertCooldownCandidatesRow{}
	for rows.Next() {
		var i ActionRevertCooldownCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.SiteID,
			&i.SubjectID,
			&i.EndpointGroupID,
			&i.Scope,
			&i.Until,
			&i.Hkey,
			&i.Client,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const actionRevertLifecycleCandidates = `-- name: ActionRevertLifecycleCandidates :many

SELECT DISTINCT ON (e.subject_id)
       e.id, e.created_at, e.site_id, e.subject_id, e.action, e.to_state,
       i.state AS current_state, i.state_changed_at
FROM state_events AS e
JOIN identities AS i ON i.id = e.subject_id
WHERE e.namespace_id = $1::text
  AND e.subject_kind = 'identity'
  AND e.shadow = false
  AND e.actor = 'system'
  AND e.action = ANY($2::text[])
  AND e.site_id = ANY($3::text[])
  AND e.created_at >= $4::timestamptz
  AND e.created_at < $5::timestamptz
  AND ($6::text = '' OR e.policy_id = $6::text)
  AND ($7::text = '' OR e.rule = $7::text)
ORDER BY e.subject_id, e.created_at DESC
LIMIT $8::int
`

type ActionRevertLifecycleCandidatesParams struct {
	NamespaceID string    `json:"namespace_id"`
	Actions     []string  `json:"actions"`
	SiteIds     []string  `json:"site_ids"`
	FromTs      time.Time `json:"from_ts"`
	ToTs        time.Time `json:"to_ts"`
	PolicyID    string    `json:"policy_id"`
	Rule        string    `json:"rule"`
	MaxRows     int32     `json:"max_rows"`
}

type ActionRevertLifecycleCandidatesRow struct {
	ID             string    `json:"id"`
	CreatedAt      time.Time `json:"created_at"`
	SiteID         string    `json:"site_id"`
	SubjectID      string    `json:"subject_id"`
	Action         string    `json:"action"`
	ToState        string    `json:"to_state"`
	CurrentState   string    `json:"current_state"`
	StateChangedAt time.Time `json:"state_changed_at"`
}

// Rollback of automatic actions (RevertActions, design doc §8.5).
func (q *Queries) ActionRevertLifecycleCandidates(ctx context.Context, arg ActionRevertLifecycleCandidatesParams) ([]ActionRevertLifecycleCandidatesRow, error) {
	rows, err := q.db.Query(ctx, actionRevertLifecycleCandidates,
		arg.NamespaceID,
		arg.Actions,
		arg.SiteIds,
		arg.FromTs,
		arg.ToTs,
		arg.PolicyID,
		arg.Rule,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionRevertLifecycleCandidatesRow{}
	for rows.Next() {
		var i ActionRevertLifecycleCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.SiteID,
			&i.SubjectID,
			&i.Action,
			&i.ToState,
			&i.CurrentState,
			&i.StateChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
