// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: site.sql

package sitesvcdb

import (
	"context"
	"time"
)

const endpointGroupCount = `-- name: EndpointGroupCount :one
SELECT count(*)::integer
FROM endpoint_groups eg
WHERE eg.site_id = $1
  AND ($2::text = '' OR eg.client = $2::text)
`

type EndpointGroupCountParams struct {
	SiteID string `json:"site_id"`
	Client string `json:"client"`
}

func (q *Queries) EndpointGroupCount(ctx context.Context, arg EndpointGroupCountParams) (int32, error) {
	row := q.db.QueryRow(ctx, endpointGroupCount, arg.SiteID, arg.Client)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const endpointGroupDelete = `-- name: EndpointGroupDelete :execrows
DELETE FROM endpoint_groups
WHERE id = $1
`

func (q *Queries) EndpointGroupDelete(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, endpointGroupDelete, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const endpointGroupDeleteByClients = `-- name: EndpointGroupDeleteByClients :execrows
DELETE FROM endpoint_groups
WHERE site_id = $1
  AND client = ANY ($2::text[])
`

type EndpointGroupDeleteByClientsParams struct {
	SiteID  string   `json:"site_id"`
	Clients []string `json:"clients"`
}

func (q *Queries) EndpointGroupDeleteByClients(ctx context.Context, arg EndpointGroupDeleteByClientsParams) (int64, error) {
	result, err := q.db.Exec(ctx, endpointGroupDeleteByClients, arg.SiteID, arg.Clients)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const endpointGroupGet = `-- name: EndpointGroupGet :one
SELECT eg.id, eg.hkey, eg.site_id, s.hkey AS site_hkey, s.name AS site_name, s.namespace_id,
       n.name AS namespace_name, n.tenant_id, eg.client, eg.name, eg.description, eg.low_watermark,
       eg.created_at, eg.updated_at
FROM endpoint_groups eg
JOIN sites s ON s.id = eg.site_id
JOIN namespaces n ON n.id = s.namespace_id
WHERE eg.id = $1
`

type EndpointGroupGetRow struct {
	ID            string    `json:"id"`
	Hkey          int64     `json:"hkey"`
	SiteID        string    `json:"site_id"`
	SiteHkey      int64     `json:"site_hkey"`
	SiteName      string    `json:"site_name"`
	NamespaceID   string    `json:"namespace_id"`
	NamespaceName string    `json:"namespace_name"`
	TenantID      string    `json:"tenant_id"`
	Client        string    `json:"client"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	LowWatermark  int32     `json:"low_watermark"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) EndpointGroupGet(ctx context.Context, id string) (EndpointGroupGetRow, error) {
	row := q.db.QueryRow(ctx, endpointGroupGet, id)
	var i EndpointGroupGetRow
	err := row.Scan(
		&i.ID,
		&i.Hkey,
		&i.SiteID,
		&i.SiteHkey,
		&i.SiteName,
		&i.NamespaceID,
		&i.NamespaceName,
		&i.TenantID,
		&i.Client,
		&i.Name,
		&i.Description,
		&i.LowWatermark,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const endpointGroupInsert = `-- name: EndpointGroupInsert :one
INSERT INTO endpoint_groups (id, site_id, client, name, description, low_watermark)
VALUES ($1, $2, $3, $4, $5,
        $6)
RETURNING id, hkey, site_id, client, name, description, low_watermark, created_at, updated_at
`

type EndpointGroupInsertParams struct {
	ID           string `json:"id"`
	SiteID       string `json:"site_id"`
	Client       string `json:"client"`
	Name         string `json:"name"`
	Description  string `json:"description"`
	LowWatermark int32  `json:"low_watermark"`
}

func (q *Queries) EndpointGroupInsert(ctx context.Context, arg EndpointGroupInsertParams) (EndpointGroup, error) {
	row := q.db.QueryRow(ctx, endpointGroupInsert,
		arg.ID,
		arg.SiteID,
		arg.Client,
		arg.Name,
		arg.Description,
		arg.LowWatermark,
	)
	var i EndpointGroup
	err := row.Scan(
		&i.ID,
		&i.Hkey,
		&i.SiteID,
		&i.Client,
		&i.Name,
		&i.Description,
		&i.LowWatermark,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const endpointGroupInsertDefaults = `-- name: EndpointGroupInsertDefaults :execrows
INSERT INTO endpoint_groups (id, site_id, client, name)
SELECT unnest($1::text[]), $2::text, unnest($3::text[]), '_default'
ON CONFLICT (site_id, client, name) DO NOTHING
`

type EndpointGroupInsertDefaultsParams struct {
	Ids     []string `json:"ids"`
	SiteID  string   `json:"site_id"`
	Clients []string `json:"clients"`
}

// EndpointGroupInsertDefaults creates the "_default" group of every listed
// client that does not have one yet.
func (q *Queries) EndpointGroupInsertDefaults(ctx context.Context, arg EndpointGroupInsertDefaultsParams) (int64, error) {
	result, err := q.db.Exec(ctx, endpointGroupInsertDefaults, arg.Ids, arg.SiteID, arg.Clients)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const endpointGroupList = `-- name: EndpointGroupList :many
SELECT eg.id, eg.hkey, eg.site_id, eg.client, eg.name, eg.description, eg.low_watermark, eg.created_at, eg.updated_at
FROM endpoint_groups eg
WHERE eg.site_id = $1
  AND ($2::text = '' OR eg.client = $2::text)
  AND (eg.client, eg.name) > ($3::text, $4::text)
ORDER BY eg.client, eg.name
LIMIT $5
`

type EndpointGroupListParams struct {
	SiteID      string `json:"site_id"`
	Client      string `json:"client"`
	AfterClient string `json:"after_client"`
	AfterName   string `json:"after_name"`
	MaxRows     int32  `json:"max_rows"`
}

func (q *Queries) EndpointGroupList(ctx context.Context, arg EndpointGroupListParams) ([]EndpointGroup, error) {
	rows, err := q.db.Query(ctx, endpointGroupList,
		arg.SiteID,
		arg.Client,
		arg.AfterClient,
		arg.AfterName,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EndpointGroup{}
	for rows.Next() {
		var i EndpointGroup
		if err := rows.Scan(
			&i.ID,
			&i.Hkey,
			&i.SiteID,
			&i.Client,
			&i.Name,
			&i.Description,
			&i.LowWatermark,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const endpointGroupTouch = `-- name: EndpointGroupTouch :exec
UPDATE endpoint_groups
SET updated_at = now()
WHERE id = $1
`

func (q *Queries) EndpointGroupTouch(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, endpointGroupTouch, id)
	return err
}

const endpointGroupUpdate = `-- name: EndpointGroupUpdate :exec
UPDATE endpoint_groups
SET description   = $1,
    low_watermark = $2,
    updated_at    = now()
WHERE id = $3
`

type EndpointGroupUpdateParams struct {
	Description  string `json:"description"`
	LowWatermark int32  `json:"low_watermark"`
	ID           string `json:"id"`
}

func (q *Queries) EndpointGroupUpdate(ctx context.Context, arg EndpointGroupUpdateParams) error {
	_, err := q.db.Exec(ctx, endpointGroupUpdate, arg.Description, arg.LowWatermark, arg.ID)
	return err
}

const siteCount = `-- name: SiteCount :one
SELECT count(*)::integer
FROM sites s
WHERE s.namespace_id = $1
  AND ($2::boolean OR s.id = ANY ($3::text[]))
`

type SiteCountParams struct {
	NamespaceID string   `json:"namespace_id"`
	AllSites    bool     `json:"all_sites"`
	SiteIds     []string `json:"site_ids"`
}

func (q *Queries) SiteCount(ctx context.Context, arg SiteCountParams) (int32, error) {
	row := q.db.QueryRow(ctx, siteCount, arg.NamespaceID, arg.AllSites, arg.SiteIds)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const siteCountClientUsage = `-- name: SiteCountClientUsage :one
SELECT (SELECT count(*) FROM identity_types it
        WHERE it.site_id = $1 AND it.client = ANY ($2::text[]))::integer AS identity_types,
       (SELECT count(*) FROM identities i
        WHERE i.site_id = $1 AND i.client = ANY ($2::text[]))::integer AS identities
`

type SiteCountClientUsageParams struct {
	SiteID  string   `json:"site_id"`
	Clients []string `json:"clients"`
}

type SiteCountClientUsageRow struct {
	IdentityTypes int32 `json:"identity_types"`
	Identities    int32 `json:"identities"`
}

// SiteCountClientUsage counts identity types and identities of the given
// clients of a site.
func (q *Queries) SiteCountClientUsage(ctx context.Context, arg SiteCountClientUsageParams) (SiteCountClientUsageRow, error) {
	row := q.db.QueryRow(ctx, siteCountClientUsage, arg.SiteID, arg.Clients)
	var i SiteCountClientUsageRow
	err := row.Scan(&i.IdentityTypes, &i.Identities)
	return i, err
}

const siteCountIdentities = `-- name: SiteCountIdentities :one
SELECT count(*)::integer
FROM identities
WHERE site_id = $1
`

func (q *Queries) SiteCountIdentities(ctx context.Context, siteID string) (int32, error) {
	row := q.db.QueryRow(ctx, siteCountIdentities, siteID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const siteDelete = `-- name: SiteDelete :execrows
DELETE FROM sites
WHERE id = $1
`

func (q *Queries) SiteDelete(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, siteDelete, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const siteDeleteClientBindings = `-- name: SiteDeleteClientBindings :execrows
DELETE FROM policy_bindings
WHERE site_id = $1::text
  AND client = ANY ($2::text[])
  AND endpoint_group_id IS NULL
`

type SiteDeleteClientBindingsParams struct {
	SiteID  string   `json:"site_id"`
	Clients []string `json:"clients"`
}

// SiteDeleteClientBindings removes client-level policy bindings of removed
// clients (endpoint-group bindings are removed with their groups).
func (q *Queries) SiteDeleteClientBindings(ctx context.Context, arg SiteDeleteClientBindingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, siteDeleteClientBindings, arg.SiteID, arg.Clients)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const siteDeleteIdentities = `-- name: SiteDeleteIdentities :execrows
DELETE FROM identities
WHERE site_id = $1
`

func (q *Queries) SiteDeleteIdentities(ctx context.Context, siteID string) (int64, error) {
	result, err := q.db.Exec(ctx, siteDeleteIdentities, siteID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const siteGet = `-- name: SiteGet :one
SELECT s.id, s.hkey, s.namespace_id, n.name AS namespace_name, n.tenant_id, s.name, s.display_name, s.description,
       s.clients, s.paused, s.paused_reason, s.paused_at, s.created_at, s.updated_at,
       (SELECT count(*) FROM endpoint_groups eg WHERE eg.site_id = s.id)::integer AS endpoint_group_count,
       (SELECT count(*) FROM identities i WHERE i.site_id = s.id AND i.state <> 'retired')::integer AS identity_count
FROM sites s
JOIN namespaces n ON n.id = s.namespace_id
WHERE s.id = $1
`

type SiteGetRow struct {
	ID                 string     `json:"id"`
	Hkey               int64      `json:"hkey"`
	NamespaceID        string     `json:"namespace_id"`
	NamespaceName      string     `json:"namespace_name"`
	TenantID           string     `json:"tenant_id"`
	Name               string     `json:"name"`
	DisplayName        string     `json:"display_name"`
	Description        string     `json:"description"`
	Clients            []string   `json:"clients"`
	Paused             bool       `json:"paused"`
	PausedReason       string     `json:"paused_reason"`
	PausedAt           *time.Time `json:"paused_at"`
	CreatedAt          time.Time  `json:"created_at"`
	UpdatedAt          time.Time  `json:"updated_at"`
	EndpointGroupCount int32      `json:"endpoint_group_count"`
	IdentityCount      int32      `json:"identity_count"`
}

// SiteGet returns a site with its namespace, tenant and counts.
func (q *Queries) SiteGet(ctx context.Context, id string) (SiteGetRow, error) {
	row := q.db.QueryRow(ctx, siteGet, id)
	var i SiteGetRow
	err := row.Scan(
		&i.ID,
		&i.Hkey,
		&i.NamespaceID,
		&i.NamespaceName,
		&i.TenantID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.Clients,
		&i.Paused,
		&i.PausedReason,
		&i.PausedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndpointGroupCount,
		&i.IdentityCount,
	)
	return i, err
}

const siteGetRef = `-- name: SiteGetRef :one
SELECT s.id, s.hkey, s.namespace_id, n.name AS namespace_name, n.tenant_id, s.name
FROM sites s
JOIN namespaces n ON n.id = s.namespace_id
WHERE s.id = $1
`

type SiteGetRefRow struct {
	ID            string `json:"id"`
	Hkey          int64  `json:"hkey"`
	NamespaceID   string `json:"namespace_id"`
	NamespaceName string `json:"namespace_name"`
	TenantID      string `json:"tenant_id"`
	Name          string `json:"name"`
}

func (q *Queries) SiteGetRef(ctx context.Context, id string) (SiteGetRefRow, error) {
	row := q.db.QueryRow(ctx, siteGetRef, id)
	var i SiteGetRefRow
	err := row.Scan(
		&i.ID,
		&i.Hkey,
		&i.NamespaceID,
		&i.NamespaceName,
		&i.TenantID,
		&i.Name,
	)
	return i, err
}

const siteGetRefByName = `-- name: SiteGetRefByName :one
SELECT s.id, s.hkey, s.namespace_id, n.name AS namespace_name, n.tenant_id, s.name
FROM sites s
JOIN namespaces n ON n.id = s.namespace_id
WHERE s.namespace_id = $1 AND s.name = $2
`

type SiteGetRefByNameParams struct {
	NamespaceID string `json:"namespace_id"`
	Name        string `json:"name"`
}

type SiteGetRefByNameRow struct {
	ID            string `json:"id"`
	Hkey          int64  `json:"hkey"`
	NamespaceID   string `json:"namespace_id"`
	NamespaceName string `json:"namespace_name"`
	TenantID      string `json:"tenant_id"`
	Name          string `json:"name"`
}

func (q *Queries) SiteGetRefByName(ctx context.Context, arg SiteGetRefByNameParams) (SiteGetRefByNameRow, error) {
	row := q.db.QueryRow(ctx, siteGetRefByName, arg.NamespaceID, arg.Name)
	var i SiteGetRefByNameRow
	err := row.Scan(
		&i.ID,
		&i.Hkey,
		&i.NamespaceID,
		&i.NamespaceName,
		&i.TenantID,
		&i.Name,
	)
	return i, err
}

const siteInsert = `-- name: SiteInsert :one
INSERT INTO sites (id, namespace_id, name, display_name, description, clients)
VALUES ($1, $2, $3, $4, $5,
        $6::text[])
RETURNING id, hkey, namespace_id, name, display_name, description, clients, paused, paused_reason, paused_at,
          created_at, updated_at
`

type SiteInsertParams struct {
	ID          string   `json:"id"`
	NamespaceID string   `json:"namespace_id"`
	Name        string   `json:"name"`
	DisplayName string   `json:"display_name"`
	Description string   `json:"description"`
	Clients     []string `json:"clients"`
}

type SiteInsertRow struct {
	ID           string     `json:"id"`
	Hkey         int64      `json:"hkey"`
	NamespaceID  string     `json:"namespace_id"`
	Name         string     `json:"name"`
	DisplayName  string     `json:"display_name"`
	Description  string     `json:"description"`
	Clients      []string   `json:"clients"`
	Paused       bool       `json:"paused"`
	PausedReason string     `json:"paused_reason"`
	PausedAt     *time.Time `json:"paused_at"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}

func (q *Queries) SiteInsert(ctx context.Context, arg SiteInsertParams) (SiteInsertRow, error) {
	row := q.db.QueryRow(ctx, siteInsert,
		arg.ID,
		arg.NamespaceID,
		arg.Name,
		arg.DisplayName,
		arg.Description,
		arg.Clients,
	)
	var i SiteInsertRow
	err := row.Scan(
		&i.ID,
		&i.Hkey,
		&i.NamespaceID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.Clients,
		&i.Paused,
		&i.PausedReason,
		&i.PausedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const siteList = `-- name: SiteList :many
SELECT s.id, s.hkey, s.namespace_id, n.name AS namespace_name, n.tenant_id, s.name, s.display_name, s.description,
       s.clients, s.paused, s.paused_reason, s.paused_at, s.created_at, s.updated_at,
       (SELECT count(*) FROM endpoint_groups eg WHERE eg.site_id = s.id)::integer AS endpoint_group_count,
       (SELECT count(*) FROM identities i WHERE i.site_id = s.id AND i.state <> 'retired')::integer AS identity_count
FROM sites s
JOIN namespaces n ON n.id = s.namespace_id
WHERE s.namespace_id = $1
  AND ($2::boolean OR s.id = ANY ($3::text[]))
  AND s.name > $4
ORDER BY s.name
LIMIT $5
`

type SiteListParams struct {
	NamespaceID string   `json:"namespace_id"`
	AllSites    bool     `json:"all_sites"`
	SiteIds     []string `json:"site_ids"`
	AfterName   string   `json:"after_name"`
	MaxRows     int32    `json:"max_rows"`
}

type SiteListRow struct {
	ID                 string     `json:"id"`
	Hkey               int64      `json:"hkey"`
	NamespaceID        string     `json:"namespace_id"`
	NamespaceName      string     `json:"namespace_name"`
	TenantID           string     `json:"tenant_id"`
	Name               string     `json:"name"`
	DisplayName        string     `json:"display_name"`
	Description        string     `json:"description"`
	Clients            []string   `json:"clients"`
	Paused             bool       `json:"paused"`
	PausedReason       string     `json:"paused_reason"`
	PausedAt           *time.Time `json:"paused_at"`
	CreatedAt          time.Time  `json:"created_at"`
	UpdatedAt          time.Time  `json:"updated_at"`
	EndpointGroupCount int32      `json:"endpoint_group_count"`
	IdentityCount      int32      `json:"identity_count"`
}

// SiteList returns one page of sites ordered by name. When all_sites is false
// only the listed site IDs are returned.
func (q *Queries) SiteList(ctx context.Context, arg SiteListParams) ([]SiteListRow, error) {
	rows, err := q.db.Query(ctx, siteList,
		arg.NamespaceID,
		arg.AllSites,
		arg.SiteIds,
		arg.AfterName,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SiteListRow{}
	for rows.Next() {
		var i SiteListRow
		if err := rows.Scan(
			&i.ID,
			&i.Hkey,
			&i.NamespaceID,
			&i.NamespaceName,
			&i.TenantID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.Clients,
			&i.Paused,
			&i.PausedReason,
			&i.PausedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EndpointGroupCount,
			&i.IdentityCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const siteLock = `-- name: SiteLock :one
SELECT id, hkey, namespace_id, name, clients
FROM sites
WHERE id = $1
FOR UPDATE
`

type SiteLockRow struct {
	ID          string   `json:"id"`
	Hkey        int64    `json:"hkey"`
	NamespaceID string   `json:"namespace_id"`
	Name        string   `json:"name"`
	Clients     []string `json:"clients"`
}

// SiteLock locks the site row for the rest of the transaction.
func (q *Queries) SiteLock(ctx context.Context, id string) (SiteLockRow, error) {
	row := q.db.QueryRow(ctx, siteLock, id)
	var i SiteLockRow
	err := row.Scan(
		&i.ID,
		&i.Hkey,
		&i.NamespaceID,
		&i.Name,
		&i.Clients,
	)
	return i, err
}

const siteUpdate = `-- name: SiteUpdate :exec
UPDATE sites
SET display_name = $1,
    description  = $2,
    clients      = $3::text[],
    updated_at   = now()
WHERE id = $4
`

type SiteUpdateParams struct {
	DisplayName string   `json:"display_name"`
	Description string   `json:"description"`
	Clients     []string `json:"clients"`
	ID          string   `json:"id"`
}

func (q *Queries) SiteUpdate(ctx context.Context, arg SiteUpdateParams) error {
	_, err := q.db.Exec(ctx, siteUpdate,
		arg.DisplayName,
		arg.Description,
		arg.Clients,
		arg.ID,
	)
	return err
}

const uRIRuleCount = `-- name: URIRuleCount :one
SELECT count(*)::integer
FROM uri_rules
WHERE endpoint_group_id = $1
`

func (q *Queries) URIRuleCount(ctx context.Context, endpointGroupID string) (int32, error) {
	row := q.db.QueryRow(ctx, uRIRuleCount, endpointGroupID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const uRIRuleDeleteByGroup = `-- name: URIRuleDeleteByGroup :execrows
DELETE FROM uri_rules
WHERE endpoint_group_id = $1
`

func (q *Queries) URIRuleDeleteByGroup(ctx context.Context, endpointGroupID string) (int64, error) {
	result, err := q.db.Exec(ctx, uRIRuleDeleteByGroup, endpointGroupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const uRIRuleInsertBatch = `-- name: URIRuleInsertBatch :execrows
INSERT INTO uri_rules (id, endpoint_group_id, kind, pattern, position)
SELECT unnest($1::text[]), $2::text, unnest($3::text[]),
       unnest($4::text[]), unnest($5::integer[])
`

type URIRuleInsertBatchParams struct {
	Ids             []string `json:"ids"`
	EndpointGroupID string   `json:"endpoint_group_id"`
	Kinds           []string `json:"kinds"`
	Patterns        []string `json:"patterns"`
	Positions       []int32  `json:"positions"`
}

func (q *Queries) URIRuleInsertBatch(ctx context.Context, arg URIRuleInsertBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, uRIRuleInsertBatch,
		arg.Ids,
		arg.EndpointGroupID,
		arg.Kinds,
		arg.Patterns,
		arg.Positions,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const uRIRuleListByGroups = `-- name: URIRuleListByGroups :many
SELECT id, endpoint_group_id, kind, pattern, position
FROM uri_rules
WHERE endpoint_group_id = ANY ($1::text[])
ORDER BY endpoint_group_id, position, id
`

type URIRuleListByGroupsRow struct {
	ID              string `json:"id"`
	EndpointGroupID string `json:"endpoint_group_id"`
	Kind            string `json:"kind"`
	Pattern         string `json:"pattern"`
	Position        int32  `json:"position"`
}

func (q *Queries) URIRuleListByGroups(ctx context.Context, groupIds []string) ([]URIRuleListByGroupsRow, error) {
	rows, err := q.db.Query(ctx, uRIRuleListByGroups, groupIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []URIRuleListByGroupsRow{}
	for rows.Next() {
		var i URIRuleListByGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.EndpointGroupID,
			&i.Kind,
			&i.Pattern,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uRIRuleListBySiteClient = `-- name: URIRuleListBySiteClient :many
SELECT r.id, r.endpoint_group_id, eg.name AS group_name, r.kind, r.pattern, r.position
FROM uri_rules r
JOIN endpoint_groups eg ON eg.id = r.endpoint_group_id
WHERE eg.site_id = $1 AND eg.client = $2
ORDER BY r.endpoint_group_id, r.position, r.id
`

type URIRuleListBySiteClientParams struct {
	SiteID string `json:"site_id"`
	Client string `json:"client"`
}

type URIRuleListBySiteClientRow struct {
	ID              string `json:"id"`
	EndpointGroupID string `json:"endpoint_group_id"`
	GroupName       string `json:"group_name"`
	Kind            string `json:"kind"`
	Pattern         string `json:"pattern"`
	Position        int32  `json:"position"`
}

// URIRuleListBySiteClient returns the rules of every endpoint group of a site
// client, with their group names.
func (q *Queries) URIRuleListBySiteClient(ctx context.Context, arg URIRuleListBySiteClientParams) ([]URIRuleListBySiteClientRow, error) {
	rows, err := q.db.Query(ctx, uRIRuleListBySiteClient, arg.SiteID, arg.Client)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []URIRuleListBySiteClientRow{}
	for rows.Next() {
		var i URIRuleListBySiteClientRow
		if err := rows.Scan(
			&i.ID,
			&i.EndpointGroupID,
			&i.GroupName,
			&i.Kind,
			&i.Pattern,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uRIRuleListPage = `-- name: URIRuleListPage :many
SELECT id, endpoint_group_id, kind, pattern, position
FROM uri_rules
WHERE endpoint_group_id = $1
  AND (position, id) > ($2::integer, $3::text)
ORDER BY position, id
LIMIT $4
`

type URIRuleListPageParams struct {
	EndpointGroupID string `json:"endpoint_group_id"`
	AfterPosition   int32  `json:"after_position"`
	AfterID         string `json:"after_id"`
	MaxRows         int32  `json:"max_rows"`
}

type URIRuleListPageRow struct {
	ID              string `json:"id"`
	EndpointGroupID string `json:"endpoint_group_id"`
	Kind            string `json:"kind"`
	Pattern         string `json:"pattern"`
	Position        int32  `json:"position"`
}

func (q *Queries) URIRuleListPage(ctx context.Context, arg URIRuleListPageParams) ([]URIRuleListPageRow, error) {
	rows, err := q.db.Query(ctx, uRIRuleListPage,
		arg.EndpointGroupID,
		arg.AfterPosition,
		arg.AfterID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []URIRuleListPageRow{}
	for rows.Next() {
		var i URIRuleListPageRow
		if err := rows.Scan(
			&i.ID,
			&i.EndpointGroupID,
			&i.Kind,
			&i.Pattern,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
