// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package identitysvcdb

import (
	"context"
	"time"
)

const accountCount = `-- name: AccountCount :one
SELECT count(*)::bigint AS n
FROM accounts a
WHERE a.site_id = ANY ($1::text[])
  AND ($2::text = '' OR strpos(lower(a.external_ref), lower($2::text)) > 0)
  AND ($3::text = '' OR a.state = $3::text)
`

type AccountCountParams struct {
	SiteIds []string `json:"site_ids"`
	Search  string   `json:"search"`
	State   string   `json:"state"`
}

func (q *Queries) AccountCount(ctx context.Context, arg AccountCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, accountCount, arg.SiteIds, arg.Search, arg.State)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const accountGet = `-- name: AccountGet :one
SELECT a.id, a.site_id, a.external_ref, a.region, a.tags, a.state, a.ban_until, a.cooldown_until, a.notes,
       a.created_at, a.updated_at,
       (SELECT count(*) FROM identities i WHERE i.account_id = a.id)::integer AS identity_count
FROM accounts a
WHERE a.id = $1
`

type AccountGetRow struct {
	ID            string     `json:"id"`
	SiteID        string     `json:"site_id"`
	ExternalRef   string     `json:"external_ref"`
	Region        string     `json:"region"`
	Tags          []string   `json:"tags"`
	State         string     `json:"state"`
	BanUntil      *time.Time `json:"ban_until"`
	CooldownUntil *time.Time `json:"cooldown_until"`
	Notes         string     `json:"notes"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
	IdentityCount int32      `json:"identity_count"`
}

func (q *Queries) AccountGet(ctx context.Context, id string) (AccountGetRow, error) {
	row := q.db.QueryRow(ctx, accountGet, id)
	var i AccountGetRow
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ExternalRef,
		&i.Region,
		&i.Tags,
		&i.State,
		&i.BanUntil,
		&i.CooldownUntil,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdentityCount,
	)
	return i, err
}

const accountIDsByRefs = `-- name: AccountIDsByRefs :many
SELECT id, external_ref
FROM accounts
WHERE site_id = $1
  AND external_ref = ANY ($2::text[])
`

type AccountIDsByRefsParams struct {
	SiteID string   `json:"site_id"`
	Refs   []string `json:"refs"`
}

type AccountIDsByRefsRow struct {
	ID          string `json:"id"`
	ExternalRef string `json:"external_ref"`
}

func (q *Queries) AccountIDsByRefs(ctx context.Context, arg AccountIDsByRefsParams) ([]AccountIDsByRefsRow, error) {
	rows, err := q.db.Query(ctx, accountIDsByRefs, arg.SiteID, arg.Refs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountIDsByRefsRow{}
	for rows.Next() {
		var i AccountIDsByRefsRow
		if err := rows.Scan(&i.ID, &i.ExternalRef); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accountInsert = `-- name: AccountInsert :one
INSERT INTO accounts (id, site_id, external_ref, region, tags, notes)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (site_id, external_ref) DO NOTHING
RETURNING id
`

type AccountInsertParams struct {
	ID          string   `json:"id"`
	SiteID      string   `json:"site_id"`
	ExternalRef string   `json:"external_ref"`
	Region      string   `json:"region"`
	Tags        []string `json:"tags"`
	Notes       string   `json:"notes"`
}

func (q *Queries) AccountInsert(ctx context.Context, arg AccountInsertParams) (string, error) {
	row := q.db.QueryRow(ctx, accountInsert,
		arg.ID,
		arg.SiteID,
		arg.ExternalRef,
		arg.Region,
		arg.Tags,
		arg.Notes,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const accountInsertRefs = `-- name: AccountInsertRefs :many
INSERT INTO accounts (id, site_id, external_ref)
SELECT u.id, $1::text, u.external_ref
FROM (SELECT unnest($2::text[]) AS id, unnest($3::text[]) AS external_ref) u
ON CONFLICT (site_id, external_ref) DO NOTHING
RETURNING id, external_ref
`

type AccountInsertRefsParams struct {
	SiteID string   `json:"site_id"`
	Ids    []string `json:"ids"`
	Refs   []string `json:"refs"`
}

type AccountInsertRefsRow struct {
	ID          string `json:"id"`
	ExternalRef string `json:"external_ref"`
}

// AccountInsertRefs creates the accounts that do not exist yet and returns
// only the created rows.
func (q *Queries) AccountInsertRefs(ctx context.Context, arg AccountInsertRefsParams) ([]AccountInsertRefsRow, error) {
	rows, err := q.db.Query(ctx, accountInsertRefs, arg.SiteID, arg.Ids, arg.Refs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountInsertRefsRow{}
	for rows.Next() {
		var i AccountInsertRefsRow
		if err := rows.Scan(&i.ID, &i.ExternalRef); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accountList = `-- name: AccountList :many
SELECT a.id, a.site_id, a.external_ref, a.region, a.tags, a.state, a.ban_until, a.cooldown_until, a.notes,
       a.created_at, a.updated_at,
       (SELECT count(*) FROM identities i WHERE i.account_id = a.id)::integer AS identity_count
FROM accounts a
WHERE a.site_id = ANY ($1::text[])
  AND ($2::text = '' OR strpos(lower(a.external_ref), lower($2::text)) > 0)
  AND ($3::text = '' OR a.state = $3::text)
  AND a.id > $4::text
ORDER BY a.id
LIMIT $5::integer
`

type AccountListParams struct {
	SiteIds []string `json:"site_ids"`
	Search  string   `json:"search"`
	State   string   `json:"state"`
	AfterID string   `json:"after_id"`
	MaxRows int32    `json:"max_rows"`
}

type AccountListRow struct {
	ID            string     `json:"id"`
	SiteID        string     `json:"site_id"`
	ExternalRef   string     `json:"external_ref"`
	Region        string     `json:"region"`
	Tags          []string   `json:"tags"`
	State         string     `json:"state"`
	BanUntil      *time.Time `json:"ban_until"`
	CooldownUntil *time.Time `json:"cooldown_until"`
	Notes         string     `json:"notes"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
	IdentityCount int32      `json:"identity_count"`
}

func (q *Queries) AccountList(ctx context.Context, arg AccountListParams) ([]AccountListRow, error) {
	rows, err := q.db.Query(ctx, accountList,
		arg.SiteIds,
		arg.Search,
		arg.State,
		arg.AfterID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountListRow{}
	for rows.Next() {
		var i AccountListRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.ExternalRef,
			&i.Region,
			&i.Tags,
			&i.State,
			&i.BanUntil,
			&i.CooldownUntil,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IdentityCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accountUpdateByRef = `-- name: AccountUpdateByRef :one
UPDATE accounts
SET region = $1,
    tags = $2,
    notes = $3,
    updated_at = now()
WHERE site_id = $4
  AND external_ref = $5
RETURNING id
`

type AccountUpdateByRefParams struct {
	Region      string   `json:"region"`
	Tags        []string `json:"tags"`
	Notes       string   `json:"notes"`
	SiteID      string   `json:"site_id"`
	ExternalRef string   `json:"external_ref"`
}

func (q *Queries) AccountUpdateByRef(ctx context.Context, arg AccountUpdateByRefParams) (string, error) {
	row := q.db.QueryRow(ctx, accountUpdateByRef,
		arg.Region,
		arg.Tags,
		arg.Notes,
		arg.SiteID,
		arg.ExternalRef,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
