// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package identitysvcdb

import (
	"context"
	"encoding/json"
	"errors"
	"time"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const identityWrite = `-- name: IdentityWrite :batchexec
UPDATE identities
SET account_id = $1,
    state = $2,
    state_reason = $3,
    state_changed_at = $4,
    quarantine_until = $5,
    region = $6,
    tags = $7,
    labels = $8,
    unique_hash = $9,
    payload_hash = $10,
    payload_version = $11,
    activated_at = $12,
    updated_at = now()
WHERE id = $13
`

type IdentityWriteBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type IdentityWriteParams struct {
	AccountID       *string         `json:"account_id"`
	State           string          `json:"state"`
	StateReason     string          `json:"state_reason"`
	StateChangedAt  time.Time       `json:"state_changed_at"`
	QuarantineUntil *time.Time      `json:"quarantine_until"`
	Region          string          `json:"region"`
	Tags            []string        `json:"tags"`
	Labels          json.RawMessage `json:"labels"`
	UniqueHash      []byte          `json:"unique_hash"`
	PayloadHash     []byte          `json:"payload_hash"`
	PayloadVersion  int32           `json:"payload_version"`
	ActivatedAt     *time.Time      `json:"activated_at"`
	ID              string          `json:"id"`
}

// IdentityWrite stores the mutable columns of an identity computed by the
// service from a locked row.
func (q *Queries) IdentityWrite(ctx context.Context, arg []IdentityWriteParams) *IdentityWriteBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.AccountID,
			a.State,
			a.StateReason,
			a.StateChangedAt,
			a.QuarantineUntil,
			a.Region,
			a.Tags,
			a.Labels,
			a.UniqueHash,
			a.PayloadHash,
			a.PayloadVersion,
			a.ActivatedAt,
			a.ID,
		}
		batch.Queue(identityWrite, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &IdentityWriteBatchResults{br, len(arg), false}
}

func (b *IdentityWriteBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *IdentityWriteBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
