// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package identitysvcdb

import (
	"context"
)

// iteratorForIdentityCopy implements pgx.CopyFromSource.
type iteratorForIdentityCopy struct {
	rows                 []IdentityCopyParams
	skippedFirstNextCall bool
}

func (r *iteratorForIdentityCopy) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForIdentityCopy) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].SiteID,
		r.rows[0].Client,
		r.rows[0].TypeID,
		r.rows[0].AccountID,
		r.rows[0].State,
		r.rows[0].StateReason,
		r.rows[0].Region,
		r.rows[0].Tags,
		r.rows[0].Labels,
		r.rows[0].UniqueHash,
		r.rows[0].PayloadHash,
		r.rows[0].PayloadVersion,
		r.rows[0].ActivatedAt,
		r.rows[0].CreatedBy,
	}, nil
}

func (r iteratorForIdentityCopy) Err() error {
	return nil
}

func (q *Queries) IdentityCopy(ctx context.Context, arg []IdentityCopyParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"identities"}, []string{"id", "site_id", "client", "type_id", "account_id", "state", "state_reason", "region", "tags", "labels", "unique_hash", "payload_hash", "payload_version", "activated_at", "created_by"}, &iteratorForIdentityCopy{rows: arg})
}

// iteratorForIdentityPayloadCopy implements pgx.CopyFromSource.
type iteratorForIdentityPayloadCopy struct {
	rows                 []IdentityPayloadCopyParams
	skippedFirstNextCall bool
}

func (r *iteratorForIdentityPayloadCopy) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForIdentityPayloadCopy) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].IdentityID,
		r.rows[0].Version,
		r.rows[0].Ciphertext,
		r.rows[0].WrappedDek,
		r.rows[0].KekID,
		r.rows[0].CreatedBy,
	}, nil
}

func (r iteratorForIdentityPayloadCopy) Err() error {
	return nil
}

func (q *Queries) IdentityPayloadCopy(ctx context.Context, arg []IdentityPayloadCopyParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"identity_payloads"}, []string{"identity_id", "version", "ciphertext", "wrapped_dek", "kek_id", "created_by"}, &iteratorForIdentityPayloadCopy{rows: arg})
}

// iteratorForStateEventCopy implements pgx.CopyFromSource.
type iteratorForStateEventCopy struct {
	rows                 []StateEventCopyParams
	skippedFirstNextCall bool
}

func (r *iteratorForStateEventCopy) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForStateEventCopy) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].CreatedAt,
		r.rows[0].TenantID,
		r.rows[0].NamespaceID,
		r.rows[0].SiteID,
		r.rows[0].SubjectKind,
		r.rows[0].SubjectID,
		r.rows[0].FromState,
		r.rows[0].ToState,
		r.rows[0].Action,
		r.rows[0].Actor,
		r.rows[0].Reason,
	}, nil
}

func (r iteratorForStateEventCopy) Err() error {
	return nil
}

func (q *Queries) StateEventCopy(ctx context.Context, arg []StateEventCopyParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"state_events"}, []string{"id", "created_at", "tenant_id", "namespace_id", "site_id", "subject_kind", "subject_id", "from_state", "to_state", "action", "actor", "reason"}, &iteratorForStateEventCopy{rows: arg})
}
