// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identities.sql

package identitysvcdb

import (
	"context"
	"encoding/json"
	"time"
)

type IdentityCopyParams struct {
	ID             string          `json:"id"`
	SiteID         string          `json:"site_id"`
	Client         string          `json:"client"`
	TypeID         string          `json:"type_id"`
	AccountID      *string         `json:"account_id"`
	State          string          `json:"state"`
	StateReason    string          `json:"state_reason"`
	Region         string          `json:"region"`
	Tags           []string        `json:"tags"`
	Labels         json.RawMessage `json:"labels"`
	UniqueHash     []byte          `json:"unique_hash"`
	PayloadHash    []byte          `json:"payload_hash"`
	PayloadVersion int32           `json:"payload_version"`
	ActivatedAt    *time.Time      `json:"activated_at"`
	CreatedBy      string          `json:"created_by"`
}

const identityFindByHashes = `-- name: IdentityFindByHashes :many
SELECT id, site_id, client, type_id, account_id, state, state_reason, state_changed_at, quarantine_until,
       region, tags, labels, unique_hash, payload_hash, payload_version, activated_at
FROM identities
WHERE type_id = $1
  AND unique_hash = ANY ($2::bytea[])
`

type IdentityFindByHashesParams struct {
	TypeID string   `json:"type_id"`
	Hashes [][]byte `json:"hashes"`
}

type IdentityFindByHashesRow struct {
	ID              string          `json:"id"`
	SiteID          string          `json:"site_id"`
	Client          string          `json:"client"`
	TypeID          string          `json:"type_id"`
	AccountID       *string         `json:"account_id"`
	State           string          `json:"state"`
	StateReason     string          `json:"state_reason"`
	StateChangedAt  time.Time       `json:"state_changed_at"`
	QuarantineUntil *time.Time      `json:"quarantine_until"`
	Region          string          `json:"region"`
	Tags            []string        `json:"tags"`
	Labels          json.RawMessage `json:"labels"`
	UniqueHash      []byte          `json:"unique_hash"`
	PayloadHash     []byte          `json:"payload_hash"`
	PayloadVersion  int32           `json:"payload_version"`
	ActivatedAt     *time.Time      `json:"activated_at"`
}

func (q *Queries) IdentityFindByHashes(ctx context.Context, arg IdentityFindByHashesParams) ([]IdentityFindByHashesRow, error) {
	rows, err := q.db.Query(ctx, identityFindByHashes, arg.TypeID, arg.Hashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityFindByHashesRow{}
	for rows.Next() {
		var i IdentityFindByHashesRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Client,
			&i.TypeID,
			&i.AccountID,
			&i.State,
			&i.StateReason,
			&i.StateChangedAt,
			&i.QuarantineUntil,
			&i.Region,
			&i.Tags,
			&i.Labels,
			&i.UniqueHash,
			&i.PayloadHash,
			&i.PayloadVersion,
			&i.ActivatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const identityGet = `-- name: IdentityGet :one
SELECT i.id, i.site_id, i.client, i.type_id, t.name AS type_name, i.account_id,
       coalesce(a.external_ref, '')::text AS account_ref,
       i.state, i.state_reason, i.state_changed_at, i.ban_until, i.quarantine_until, i.region, i.tags, i.labels,
       i.payload_version, i.activated_at, i.last_used_at,
       coalesce(h.score, 70)::double precision AS global_score,
       coalesce(h.samples, 0)::integer AS global_samples,
       coalesce(pb.proxy_id, '')::text AS bound_proxy_id,
       i.created_at, i.updated_at
FROM identities i
JOIN identity_types t ON t.id = i.type_id
LEFT JOIN accounts a ON a.id = i.account_id
LEFT JOIN hot_state_snapshots h
       ON h.site_id = i.site_id AND h.subject = 'ig' AND h.subject_id = i.id AND h.endpoint_group_id = ''
LEFT JOIN proxy_bindings pb ON pb.identity_id = i.id
WHERE i.id = $1
`

type IdentityGetRow struct {
	ID              string          `json:"id"`
	SiteID          string          `json:"site_id"`
	Client          string          `json:"client"`
	TypeID          string          `json:"type_id"`
	TypeName        string          `json:"type_name"`
	AccountID       *string         `json:"account_id"`
	AccountRef      string          `json:"account_ref"`
	State           string          `json:"state"`
	StateReason     string          `json:"state_reason"`
	StateChangedAt  time.Time       `json:"state_changed_at"`
	BanUntil        *time.Time      `json:"ban_until"`
	QuarantineUntil *time.Time      `json:"quarantine_until"`
	Region          string          `json:"region"`
	Tags            []string        `json:"tags"`
	Labels          json.RawMessage `json:"labels"`
	PayloadVersion  int32           `json:"payload_version"`
	ActivatedAt     *time.Time      `json:"activated_at"`
	LastUsedAt      *time.Time      `json:"last_used_at"`
	GlobalScore     float64         `json:"global_score"`
	GlobalSamples   int32           `json:"global_samples"`
	BoundProxyID    string          `json:"bound_proxy_id"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

// IdentityGet returns one identity with its type name, account reference, the
// last hot-state snapshot of its global score (default baseline 70 when no
// snapshot exists) and its bound proxy.
func (q *Queries) IdentityGet(ctx context.Context, id string) (IdentityGetRow, error) {
	row := q.db.QueryRow(ctx, identityGet, id)
	var i IdentityGetRow
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Client,
		&i.TypeID,
		&i.TypeName,
		&i.AccountID,
		&i.AccountRef,
		&i.State,
		&i.StateReason,
		&i.StateChangedAt,
		&i.BanUntil,
		&i.QuarantineUntil,
		&i.Region,
		&i.Tags,
		&i.Labels,
		&i.PayloadVersion,
		&i.ActivatedAt,
		&i.LastUsedAt,
		&i.GlobalScore,
		&i.GlobalSamples,
		&i.BoundProxyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const identityLocate = `-- name: IdentityLocate :one
SELECT id, site_id, type_id, account_id
FROM identities
WHERE id = $1
`

type IdentityLocateRow struct {
	ID        string  `json:"id"`
	SiteID    string  `json:"site_id"`
	TypeID    string  `json:"type_id"`
	AccountID *string `json:"account_id"`
}

func (q *Queries) IdentityLocate(ctx context.Context, id string) (IdentityLocateRow, error) {
	row := q.db.QueryRow(ctx, identityLocate, id)
	var i IdentityLocateRow
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.TypeID,
		&i.AccountID,
	)
	return i, err
}

const identityLocateMany = `-- name: IdentityLocateMany :many
SELECT id, site_id
FROM identities
WHERE id = ANY ($1::text[])
`

type IdentityLocateManyRow struct {
	ID     string `json:"id"`
	SiteID string `json:"site_id"`
}

func (q *Queries) IdentityLocateMany(ctx context.Context, ids []string) ([]IdentityLocateManyRow, error) {
	rows, err := q.db.Query(ctx, identityLocateMany, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityLocateManyRow{}
	for rows.Next() {
		var i IdentityLocateManyRow
		if err := rows.Scan(&i.ID, &i.SiteID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const identityLock = `-- name: IdentityLock :one
SELECT id, site_id, client, type_id, account_id, state, state_reason, state_changed_at, quarantine_until,
       region, tags, labels, unique_hash, payload_hash, payload_version, activated_at
FROM identities
WHERE id = $1
FOR UPDATE
`

type IdentityLockRow struct {
	ID              string          `json:"id"`
	SiteID          string          `json:"site_id"`
	Client          string          `json:"client"`
	TypeID          string          `json:"type_id"`
	AccountID       *string         `json:"account_id"`
	State           string          `json:"state"`
	StateReason     string          `json:"state_reason"`
	StateChangedAt  time.Time       `json:"state_changed_at"`
	QuarantineUntil *time.Time      `json:"quarantine_until"`
	Region          string          `json:"region"`
	Tags            []string        `json:"tags"`
	Labels          json.RawMessage `json:"labels"`
	UniqueHash      []byte          `json:"unique_hash"`
	PayloadHash     []byte          `json:"payload_hash"`
	PayloadVersion  int32           `json:"payload_version"`
	ActivatedAt     *time.Time      `json:"activated_at"`
}

// IdentityLock locks one identity and returns every column a payload or
// attribute update needs to compute the new row.
func (q *Queries) IdentityLock(ctx context.Context, id string) (IdentityLockRow, error) {
	row := q.db.QueryRow(ctx, identityLock, id)
	var i IdentityLockRow
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Client,
		&i.TypeID,
		&i.AccountID,
		&i.State,
		&i.StateReason,
		&i.StateChangedAt,
		&i.QuarantineUntil,
		&i.Region,
		&i.Tags,
		&i.Labels,
		&i.UniqueHash,
		&i.PayloadHash,
		&i.PayloadVersion,
		&i.ActivatedAt,
	)
	return i, err
}

const identityLockByHashes = `-- name: IdentityLockByHashes :many
SELECT id, site_id, client, type_id, account_id, state, state_reason, state_changed_at, quarantine_until,
       region, tags, labels, unique_hash, payload_hash, payload_version, activated_at
FROM identities
WHERE type_id = $1
  AND unique_hash = ANY ($2::bytea[])
ORDER BY id
FOR UPDATE
`

type IdentityLockByHashesParams struct {
	TypeID string   `json:"type_id"`
	Hashes [][]byte `json:"hashes"`
}

type IdentityLockByHashesRow struct {
	ID              string          `json:"id"`
	SiteID          string          `json:"site_id"`
	Client          string          `json:"client"`
	TypeID          string          `json:"type_id"`
	AccountID       *string         `json:"account_id"`
	State           string          `json:"state"`
	StateReason     string          `json:"state_reason"`
	StateChangedAt  time.Time       `json:"state_changed_at"`
	QuarantineUntil *time.Time      `json:"quarantine_until"`
	Region          string          `json:"region"`
	Tags            []string        `json:"tags"`
	Labels          json.RawMessage `json:"labels"`
	UniqueHash      []byte          `json:"unique_hash"`
	PayloadHash     []byte          `json:"payload_hash"`
	PayloadVersion  int32           `json:"payload_version"`
	ActivatedAt     *time.Time      `json:"activated_at"`
}

// IdentityLockByHashes locks identities in ID order, so concurrent writers
// that also lock in ID order cannot deadlock.
func (q *Queries) IdentityLockByHashes(ctx context.Context, arg IdentityLockByHashesParams) ([]IdentityLockByHashesRow, error) {
	rows, err := q.db.Query(ctx, identityLockByHashes, arg.TypeID, arg.Hashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityLockByHashesRow{}
	for rows.Next() {
		var i IdentityLockByHashesRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Client,
			&i.TypeID,
			&i.AccountID,
			&i.State,
			&i.StateReason,
			&i.StateChangedAt,
			&i.QuarantineUntil,
			&i.Region,
			&i.Tags,
			&i.Labels,
			&i.UniqueHash,
			&i.PayloadHash,
			&i.PayloadVersion,
			&i.ActivatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type IdentityPayloadCopyParams struct {
	IdentityID string `json:"identity_id"`
	Version    int32  `json:"version"`
	Ciphertext []byte `json:"ciphertext"`
	WrappedDek []byte `json:"wrapped_dek"`
	KekID      string `json:"kek_id"`
	CreatedBy  string `json:"created_by"`
}

const identityPayloadGet = `-- name: IdentityPayloadGet :one
SELECT ciphertext, wrapped_dek, kek_id
FROM identity_payloads
WHERE identity_id = $1
  AND version = $2
`

type IdentityPayloadGetParams struct {
	IdentityID string `json:"identity_id"`
	Version    int32  `json:"version"`
}

type IdentityPayloadGetRow struct {
	Ciphertext []byte `json:"ciphertext"`
	WrappedDek []byte `json:"wrapped_dek"`
	KekID      string `json:"kek_id"`
}

func (q *Queries) IdentityPayloadGet(ctx context.Context, arg IdentityPayloadGetParams) (IdentityPayloadGetRow, error) {
	row := q.db.QueryRow(ctx, identityPayloadGet, arg.IdentityID, arg.Version)
	var i IdentityPayloadGetRow
	err := row.Scan(&i.Ciphertext, &i.WrappedDek, &i.KekID)
	return i, err
}

const identityPayloadPrune = `-- name: IdentityPayloadPrune :execrows
DELETE FROM identity_payloads p
USING (SELECT unnest($1::text[]) AS identity_id,
              unnest($2::integer[]) AS min_version) u
WHERE p.identity_id = u.identity_id
  AND p.version < u.min_version
`

type IdentityPayloadPruneParams struct {
	IdentityIds []string `json:"identity_ids"`
	MinVersions []int32  `json:"min_versions"`
}

// IdentityPayloadPrune deletes payload versions older than min_version for
// each (identity_id, min_version) pair.
func (q *Queries) IdentityPayloadPrune(ctx context.Context, arg IdentityPayloadPruneParams) (int64, error) {
	result, err := q.db.Exec(ctx, identityPayloadPrune, arg.IdentityIds, arg.MinVersions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const identityPayloadVersions = `-- name: IdentityPayloadVersions :many
SELECT version
FROM identity_payloads
WHERE identity_id = $1
ORDER BY version
`

func (q *Queries) IdentityPayloadVersions(ctx context.Context, identityID string) ([]int32, error) {
	rows, err := q.db.Query(ctx, identityPayloadVersions, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var version int32
		if err := rows.Scan(&version); err != nil {
			return nil, err
		}
		items = append(items, version)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const identityRehashBatch = `-- name: IdentityRehashBatch :many
SELECT i.id, i.payload_version, p.ciphertext, p.wrapped_dek, p.kek_id
FROM identities i
LEFT JOIN identity_payloads p ON p.identity_id = i.id AND p.version = i.payload_version
WHERE i.type_id = $1
  AND i.id > $2::text
ORDER BY i.id
LIMIT $3::integer
FOR UPDATE OF i
`

type IdentityRehashBatchParams struct {
	TypeID  string `json:"type_id"`
	AfterID string `json:"after_id"`
	MaxRows int32  `json:"max_rows"`
}

type IdentityRehashBatchRow struct {
	ID             string  `json:"id"`
	PayloadVersion int32   `json:"payload_version"`
	Ciphertext     []byte  `json:"ciphertext"`
	WrappedDek     []byte  `json:"wrapped_dek"`
	KekID          *string `json:"kek_id"`
}

// IdentityRehashBatch returns a page (in ID order) of identities of a type
// with their current sealed payload, locking the identities.
func (q *Queries) IdentityRehashBatch(ctx context.Context, arg IdentityRehashBatchParams) ([]IdentityRehashBatchRow, error) {
	rows, err := q.db.Query(ctx, identityRehashBatch, arg.TypeID, arg.AfterID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityRehashBatchRow{}
	for rows.Next() {
		var i IdentityRehashBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.PayloadVersion,
			&i.Ciphertext,
			&i.WrappedDek,
			&i.KekID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const identityScrambleUniqueHashes = `-- name: IdentityScrambleUniqueHashes :execrows
UPDATE identities
SET unique_hash = sha256(convert_to('spinneret:rehash:' || id, 'UTF8'))
WHERE type_id = $1
`

// IdentityScrambleUniqueHashes replaces the unique hashes of every identity of
// a type with per-identity placeholders, so a following rehash cannot collide
// with hashes that are about to be replaced.
func (q *Queries) IdentityScrambleUniqueHashes(ctx context.Context, typeID string) (int64, error) {
	result, err := q.db.Exec(ctx, identityScrambleUniqueHashes, typeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const identitySetUniqueHashes = `-- name: IdentitySetUniqueHashes :execrows
UPDATE identities i
SET unique_hash = u.unique_hash
FROM (SELECT unnest($1::text[]) AS id, unnest($2::bytea[]) AS unique_hash) u
WHERE i.id = u.id
`

type IdentitySetUniqueHashesParams struct {
	Ids    []string `json:"ids"`
	Hashes [][]byte `json:"hashes"`
}

func (q *Queries) IdentitySetUniqueHashes(ctx context.Context, arg IdentitySetUniqueHashesParams) (int64, error) {
	result, err := q.db.Exec(ctx, identitySetUniqueHashes, arg.Ids, arg.Hashes)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const identityTypeAdvisoryLock = `-- name: IdentityTypeAdvisoryLock :exec
SELECT pg_advisory_xact_lock(hashtextextended('spinneret:identity-type:' || $1::text, 0))
`

// IdentityTypeAdvisoryLock serializes payload writes of one identity type
// (imports and payload updates) until the end of the transaction, so unique
// key decisions never race.
func (q *Queries) IdentityTypeAdvisoryLock(ctx context.Context, typeID string) error {
	_, err := q.db.Exec(ctx, identityTypeAdvisoryLock, typeID)
	return err
}

const secretPathsExisting = `-- name: SecretPathsExisting :many
SELECT path
FROM secrets
WHERE namespace_id = $1
  AND path = ANY ($2::text[])
`

type SecretPathsExistingParams struct {
	NamespaceID string   `json:"namespace_id"`
	Paths       []string `json:"paths"`
}

// Paths of the given secret paths that exist in a namespace (write-time check
// of secret_ref payload fields).
func (q *Queries) SecretPathsExisting(ctx context.Context, arg SecretPathsExistingParams) ([]string, error) {
	rows, err := q.db.Query(ctx, secretPathsExisting, arg.NamespaceID, arg.Paths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
