// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity_types.sql

package identitysvcdb

import (
	"context"
	"encoding/json"
	"time"
)

const identityTypeCount = `-- name: IdentityTypeCount :one
SELECT count(*)::bigint AS n
FROM identity_types t
WHERE t.site_id = ANY ($1::text[])
  AND ($2::text = '' OR t.client = $2::text)
  AND ($3::text = '' OR strpos(lower(t.name), lower($3::text)) > 0)
`

type IdentityTypeCountParams struct {
	SiteIds []string `json:"site_ids"`
	Client  string   `json:"client"`
	Search  string   `json:"search"`
}

func (q *Queries) IdentityTypeCount(ctx context.Context, arg IdentityTypeCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, identityTypeCount, arg.SiteIds, arg.Client, arg.Search)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const identityTypeCountIdentities = `-- name: IdentityTypeCountIdentities :one
SELECT count(*)::bigint AS n
FROM identities
WHERE type_id = $1
`

func (q *Queries) IdentityTypeCountIdentities(ctx context.Context, typeID string) (int64, error) {
	row := q.db.QueryRow(ctx, identityTypeCountIdentities, typeID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const identityTypeDelete = `-- name: IdentityTypeDelete :execrows
DELETE FROM identity_types
WHERE id = $1
`

func (q *Queries) IdentityTypeDelete(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, identityTypeDelete, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const identityTypeGet = `-- name: IdentityTypeGet :one
SELECT t.id, t.site_id, t.client, t.name, t.description, t.spec, t.spec_yaml, t.json_schema, t.version,
       t.created_at, t.updated_at,
       (SELECT count(*) FROM identities i WHERE i.type_id = t.id AND i.state <> 'retired')::integer AS identity_count
FROM identity_types t
WHERE t.id = $1
`

type IdentityTypeGetRow struct {
	ID            string          `json:"id"`
	SiteID        string          `json:"site_id"`
	Client        string          `json:"client"`
	Name          string          `json:"name"`
	Description   string          `json:"description"`
	Spec          json.RawMessage `json:"spec"`
	SpecYaml      string          `json:"spec_yaml"`
	JsonSchema    json.RawMessage `json:"json_schema"`
	Version       int32           `json:"version"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
	IdentityCount int32           `json:"identity_count"`
}

func (q *Queries) IdentityTypeGet(ctx context.Context, id string) (IdentityTypeGetRow, error) {
	row := q.db.QueryRow(ctx, identityTypeGet, id)
	var i IdentityTypeGetRow
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Client,
		&i.Name,
		&i.Description,
		&i.Spec,
		&i.SpecYaml,
		&i.JsonSchema,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdentityCount,
	)
	return i, err
}

const identityTypeInsert = `-- name: IdentityTypeInsert :one
INSERT INTO identity_types (id, site_id, client, name, description, spec, spec_yaml, json_schema, version)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, 1)
RETURNING created_at, updated_at
`

type IdentityTypeInsertParams struct {
	ID          string          `json:"id"`
	SiteID      string          `json:"site_id"`
	Client      string          `json:"client"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Spec        json.RawMessage `json:"spec"`
	SpecYaml    string          `json:"spec_yaml"`
	JsonSchema  json.RawMessage `json:"json_schema"`
}

type IdentityTypeInsertRow struct {
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) IdentityTypeInsert(ctx context.Context, arg IdentityTypeInsertParams) (IdentityTypeInsertRow, error) {
	row := q.db.QueryRow(ctx, identityTypeInsert,
		arg.ID,
		arg.SiteID,
		arg.Client,
		arg.Name,
		arg.Description,
		arg.Spec,
		arg.SpecYaml,
		arg.JsonSchema,
	)
	var i IdentityTypeInsertRow
	err := row.Scan(&i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const identityTypeList = `-- name: IdentityTypeList :many
SELECT t.id, t.site_id, t.client, t.name, t.description, t.spec, t.spec_yaml, t.json_schema, t.version,
       t.created_at, t.updated_at,
       (SELECT count(*) FROM identities i WHERE i.type_id = t.id AND i.state <> 'retired')::integer AS identity_count
FROM identity_types t
WHERE t.site_id = ANY ($1::text[])
  AND ($2::text = '' OR t.client = $2::text)
  AND ($3::text = '' OR strpos(lower(t.name), lower($3::text)) > 0)
  AND t.id > $4::text
ORDER BY t.id
LIMIT $5::integer
`

type IdentityTypeListParams struct {
	SiteIds []string `json:"site_ids"`
	Client  string   `json:"client"`
	Search  string   `json:"search"`
	AfterID string   `json:"after_id"`
	MaxRows int32    `json:"max_rows"`
}

type IdentityTypeListRow struct {
	ID            string          `json:"id"`
	SiteID        string          `json:"site_id"`
	Client        string          `json:"client"`
	Name          string          `json:"name"`
	Description   string          `json:"description"`
	Spec          json.RawMessage `json:"spec"`
	SpecYaml      string          `json:"spec_yaml"`
	JsonSchema    json.RawMessage `json:"json_schema"`
	Version       int32           `json:"version"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
	IdentityCount int32           `json:"identity_count"`
}

// IdentityTypeList returns a page of identity types ordered by ID (UUIDv7,
// i.e. creation order) after the given ID.
func (q *Queries) IdentityTypeList(ctx context.Context, arg IdentityTypeListParams) ([]IdentityTypeListRow, error) {
	rows, err := q.db.Query(ctx, identityTypeList,
		arg.SiteIds,
		arg.Client,
		arg.Search,
		arg.AfterID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityTypeListRow{}
	for rows.Next() {
		var i IdentityTypeListRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Client,
			&i.Name,
			&i.Description,
			&i.Spec,
			&i.SpecYaml,
			&i.JsonSchema,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IdentityCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const identityTypeLock = `-- name: IdentityTypeLock :one
SELECT id, site_id, client, name, version
FROM identity_types
WHERE id = $1
FOR UPDATE
`

type IdentityTypeLockRow struct {
	ID      string `json:"id"`
	SiteID  string `json:"site_id"`
	Client  string `json:"client"`
	Name    string `json:"name"`
	Version int32  `json:"version"`
}

func (q *Queries) IdentityTypeLock(ctx context.Context, id string) (IdentityTypeLockRow, error) {
	row := q.db.QueryRow(ctx, identityTypeLock, id)
	var i IdentityTypeLockRow
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Client,
		&i.Name,
		&i.Version,
	)
	return i, err
}

const identityTypeLockSpec = `-- name: IdentityTypeLockSpec :one
SELECT id, site_id, client, name, version, spec
FROM identity_types
WHERE id = $1
FOR NO KEY UPDATE
`

type IdentityTypeLockSpecRow struct {
	ID      string          `json:"id"`
	SiteID  string          `json:"site_id"`
	Client  string          `json:"client"`
	Name    string          `json:"name"`
	Version int32           `json:"version"`
	Spec    json.RawMessage `json:"spec"`
}

// IdentityTypeLockSpec locks an identity type for a spec update. FOR NO KEY
// UPDATE does not block concurrent identity inserts (their foreign key checks
// take KEY SHARE locks).
func (q *Queries) IdentityTypeLockSpec(ctx context.Context, id string) (IdentityTypeLockSpecRow, error) {
	row := q.db.QueryRow(ctx, identityTypeLockSpec, id)
	var i IdentityTypeLockSpecRow
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Client,
		&i.Name,
		&i.Version,
		&i.Spec,
	)
	return i, err
}

const identityTypeSpecByID = `-- name: IdentityTypeSpecByID :one
SELECT id, site_id, spec, version
FROM identity_types
WHERE id = $1
`

type IdentityTypeSpecByIDRow struct {
	ID      string          `json:"id"`
	SiteID  string          `json:"site_id"`
	Spec    json.RawMessage `json:"spec"`
	Version int32           `json:"version"`
}

func (q *Queries) IdentityTypeSpecByID(ctx context.Context, id string) (IdentityTypeSpecByIDRow, error) {
	row := q.db.QueryRow(ctx, identityTypeSpecByID, id)
	var i IdentityTypeSpecByIDRow
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Spec,
		&i.Version,
	)
	return i, err
}

const identityTypeSpecByName = `-- name: IdentityTypeSpecByName :one
SELECT id, site_id, spec, version
FROM identity_types
WHERE site_id = $1
  AND name = $2
`

type IdentityTypeSpecByNameParams struct {
	SiteID string `json:"site_id"`
	Name   string `json:"name"`
}

type IdentityTypeSpecByNameRow struct {
	ID      string          `json:"id"`
	SiteID  string          `json:"site_id"`
	Spec    json.RawMessage `json:"spec"`
	Version int32           `json:"version"`
}

func (q *Queries) IdentityTypeSpecByName(ctx context.Context, arg IdentityTypeSpecByNameParams) (IdentityTypeSpecByNameRow, error) {
	row := q.db.QueryRow(ctx, identityTypeSpecByName, arg.SiteID, arg.Name)
	var i IdentityTypeSpecByNameRow
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Spec,
		&i.Version,
	)
	return i, err
}

const identityTypeUpdate = `-- name: IdentityTypeUpdate :one
UPDATE identity_types
SET description = $1,
    spec = $2,
    spec_yaml = $3,
    json_schema = $4,
    version = version + 1,
    updated_at = now()
WHERE id = $5
RETURNING version, created_at, updated_at
`

type IdentityTypeUpdateParams struct {
	Description string          `json:"description"`
	Spec        json.RawMessage `json:"spec"`
	SpecYaml    string          `json:"spec_yaml"`
	JsonSchema  json.RawMessage `json:"json_schema"`
	ID          string          `json:"id"`
}

type IdentityTypeUpdateRow struct {
	Version   int32     `json:"version"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) IdentityTypeUpdate(ctx context.Context, arg IdentityTypeUpdateParams) (IdentityTypeUpdateRow, error) {
	row := q.db.QueryRow(ctx, identityTypeUpdate,
		arg.Description,
		arg.Spec,
		arg.SpecYaml,
		arg.JsonSchema,
		arg.ID,
	)
	var i IdentityTypeUpdateRow
	err := row.Scan(&i.Version, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const identityTypeVersion = `-- name: IdentityTypeVersion :one
SELECT version
FROM identity_types
WHERE id = $1
`

func (q *Queries) IdentityTypeVersion(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRow(ctx, identityTypeVersion, id)
	var version int32
	err := row.Scan(&version)
	return version, err
}
