// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identitysvcdb

import (
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID            string     `json:"id"`
	Hkey          int64      `json:"hkey"`
	SiteID        string     `json:"site_id"`
	ExternalRef   string     `json:"external_ref"`
	Region        string     `json:"region"`
	Tags          []string   `json:"tags"`
	State         string     `json:"state"`
	BanUntil      *time.Time `json:"ban_until"`
	CooldownUntil *time.Time `json:"cooldown_until"`
	Notes         string     `json:"notes"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
}

type AcquireStatsMinutely struct {
	Bucket          time.Time `json:"bucket"`
	NamespaceID     string    `json:"namespace_id"`
	SiteID          string    `json:"site_id"`
	EndpointGroupID string    `json:"endpoint_group_id"`
	Result          string    `json:"result"`
	Count           int64     `json:"count"`
	DurationUsSum   int64     `json:"duration_us_sum"`
}

type AlertEvent struct {
	ID          string          `json:"id"`
	CreatedAt   time.Time       `json:"created_at"`
	TenantID    string          `json:"tenant_id"`
	NamespaceID string          `json:"namespace_id"`
	SiteID      string          `json:"site_id"`
	Kind        string          `json:"kind"`
	Severity    string          `json:"severity"`
	Title       string          `json:"title"`
	Message     string          `json:"message"`
	Details     json.RawMessage `json:"details"`
	DedupKey    string          `json:"dedup_key"`
	Deliveries  json.RawMessage `json:"deliveries"`
}

type ApiToken struct {
	ID           string     `json:"id"`
	TenantID     string     `json:"tenant_id"`
	NamespaceID  string     `json:"namespace_id"`
	Name         string     `json:"name"`
	Description  string     `json:"description"`
	TokenPrefix  string     `json:"token_prefix"`
	TokenHash    []byte     `json:"token_hash"`
	Scopes       []string   `json:"scopes"`
	IpAllowlist  []string   `json:"ip_allowlist"`
	RateLimitRps int32      `json:"rate_limit_rps"`
	ExpiresAt    *time.Time `json:"expires_at"`
	RevokedAt    *time.Time `json:"revoked_at"`
	LastUsedAt   *time.Time `json:"last_used_at"`
	LastUsedIp   string     `json:"last_used_ip"`
	CreatedBy    string     `json:"created_by"`
	CreatedAt    time.Time  `json:"created_at"`
}

type AuditLog struct {
	ID           string          `json:"id"`
	CreatedAt    time.Time       `json:"created_at"`
	TenantID     string          `json:"tenant_id"`
	NamespaceID  string          `json:"namespace_id"`
	ActorKind    string          `json:"actor_kind"`
	ActorID      string          `json:"actor_id"`
	ActorName    string          `json:"actor_name"`
	Action       string          `json:"action"`
	ResourceKind string          `json:"resource_kind"`
	ResourceID   string          `json:"resource_id"`
	ResourceName string          `json:"resource_name"`
	Result       string          `json:"result"`
	Ip           string          `json:"ip"`
	UserAgent    string          `json:"user_agent"`
	Details      json.RawMessage `json:"details"`
}

type BreakerEvent struct {
	ID              string          `json:"id"`
	CreatedAt       time.Time       `json:"created_at"`
	TenantID        string          `json:"tenant_id"`
	NamespaceID     string          `json:"namespace_id"`
	SiteID          string          `json:"site_id"`
	EndpointGroupID string          `json:"endpoint_group_id"`
	FromState       string          `json:"from_state"`
	ToState         string          `json:"to_state"`
	Trigger         string          `json:"trigger"`
	Reason          string          `json:"reason"`
	OpenUntil       *time.Time      `json:"open_until"`
	Metrics         json.RawMessage `json:"metrics"`
	Actor           string          `json:"actor"`
}

type ConfigItem struct {
	ID             string          `json:"id"`
	NamespaceID    string          `json:"namespace_id"`
	GroupName      string          `json:"group_name"`
	Key            string          `json:"key"`
	Format         string          `json:"format"`
	Schema         json.RawMessage `json:"schema"`
	Description    string          `json:"description"`
	CurrentVersion int32           `json:"current_version"`
	DraftContent   *string         `json:"draft_content"`
	DraftUpdatedBy *string         `json:"draft_updated_by"`
	DraftUpdatedAt *time.Time      `json:"draft_updated_at"`
	CreatedBy      string          `json:"created_by"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type ConfigVersion struct {
	ItemID        string    `json:"item_id"`
	Version       int32     `json:"version"`
	Content       string    `json:"content"`
	Comment       string    `json:"comment"`
	SourceVersion *int32    `json:"source_version"`
	PublishedBy   string    `json:"published_by"`
	PublishedAt   time.Time `json:"published_at"`
}

type ConfigVersionFloor struct {
	NamespaceID string    `json:"namespace_id"`
	GroupName   string    `json:"group_name"`
	Key         string    `json:"key"`
	LastVersion int32     `json:"last_version"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type EndpointGroup struct {
	ID           string    `json:"id"`
	Hkey         int64     `json:"hkey"`
	SiteID       string    `json:"site_id"`
	Client       string    `json:"client"`
	Name         string    `json:"name"`
	Description  string    `json:"description"`
	LowWatermark int32     `json:"low_watermark"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type HotStateSnapshot struct {
	SiteID              string     `json:"site_id"`
	Subject             string     `json:"subject"`
	SubjectID           string     `json:"subject_id"`
	EndpointGroupID     string     `json:"endpoint_group_id"`
	Score               float64    `json:"score"`
	Samples             int32      `json:"samples"`
	ConsecutiveFailures int32      `json:"consecutive_failures"`
	LastFailureAt       *time.Time `json:"last_failure_at"`
	CooldownUntil       *time.Time `json:"cooldown_until"`
	ReuseUntil          *time.Time `json:"reuse_until"`
	LastUsedAt          *time.Time `json:"last_used_at"`
	UpdatedAt           time.Time  `json:"updated_at"`
}

type Identity struct {
	ID              string          `json:"id"`
	Hkey            int64           `json:"hkey"`
	SiteID          string          `json:"site_id"`
	Client          string          `json:"client"`
	TypeID          string          `json:"type_id"`
	AccountID       *string         `json:"account_id"`
	State           string          `json:"state"`
	StateReason     string          `json:"state_reason"`
	StateChangedAt  time.Time       `json:"state_changed_at"`
	BanUntil        *time.Time      `json:"ban_until"`
	QuarantineUntil *time.Time      `json:"quarantine_until"`
	Region          string          `json:"region"`
	Tags            []string        `json:"tags"`
	Labels          json.RawMessage `json:"labels"`
	UniqueHash      []byte          `json:"unique_hash"`
	PayloadHash     []byte          `json:"payload_hash"`
	PayloadVersion  int32           `json:"payload_version"`
	ActivatedAt     *time.Time      `json:"activated_at"`
	LastUsedAt      *time.Time      `json:"last_used_at"`
	CreatedBy       string          `json:"created_by"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

type IdentityPayload struct {
	IdentityID string    `json:"identity_id"`
	Version    int32     `json:"version"`
	Ciphertext []byte    `json:"ciphertext"`
	WrappedDek []byte    `json:"wrapped_dek"`
	KekID      string    `json:"kek_id"`
	CreatedBy  string    `json:"created_by"`
	CreatedAt  time.Time `json:"created_at"`
}

type IdentityStatsHourly struct {
	Bucket          time.Time `json:"bucket"`
	SiteID          string    `json:"site_id"`
	IdentityID      string    `json:"identity_id"`
	EndpointGroupID string    `json:"endpoint_group_id"`
	Outcome         string    `json:"outcome"`
	Count           int64     `json:"count"`
}

type IdentityType struct {
	ID          string          `json:"id"`
	SiteID      string          `json:"site_id"`
	Client      string          `json:"client"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Spec        json.RawMessage `json:"spec"`
	SpecYaml    string          `json:"spec_yaml"`
	JsonSchema  json.RawMessage `json:"json_schema"`
	Version     int32           `json:"version"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type Namespace struct {
	ID          string    `json:"id"`
	TenantID    string    `json:"tenant_id"`
	Name        string    `json:"name"`
	DisplayName string    `json:"display_name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type NodeStatsMinutely struct {
	Bucket      time.Time `json:"bucket"`
	NamespaceID string    `json:"namespace_id"`
	Node        string    `json:"node"`
	Acquires    int64     `json:"acquires"`
	Reports     int64     `json:"reports"`
	Abandoned   int64     `json:"abandoned"`
	Rejected    int64     `json:"rejected"`
}

type NotificationChannel struct {
	ID                 string     `json:"id"`
	TenantID           string     `json:"tenant_id"`
	NamespaceID        *string    `json:"namespace_id"`
	Name               string     `json:"name"`
	Kind               string     `json:"kind"`
	ConfigCiphertext   []byte     `json:"config_ciphertext"`
	ConfigWrappedDek   []byte     `json:"config_wrapped_dek"`
	ConfigKekID        string     `json:"config_kek_id"`
	EventTypes         []string   `json:"event_types"`
	SiteIds            []string   `json:"site_ids"`
	MinSeverity        string     `json:"min_severity"`
	Enabled            bool       `json:"enabled"`
	LastDeliveryAt     *time.Time `json:"last_delivery_at"`
	LastDeliveryStatus string     `json:"last_delivery_status"`
	CreatedBy          string     `json:"created_by"`
	CreatedAt          time.Time  `json:"created_at"`
	UpdatedAt          time.Time  `json:"updated_at"`
}

type OutcomeStatsMinutely struct {
	Bucket           time.Time `json:"bucket"`
	NamespaceID      string    `json:"namespace_id"`
	SiteID           string    `json:"site_id"`
	EndpointGroupID  string    `json:"endpoint_group_id"`
	ProxyID          string    `json:"proxy_id"`
	Outcome          string    `json:"outcome"`
	Count            int64     `json:"count"`
	LatencyMsSum     int64     `json:"latency_ms_sum"`
	ResponseBytesSum int64     `json:"response_bytes_sum"`
}

type PayloadAccessMinutely struct {
	Bucket         time.Time `json:"bucket"`
	NamespaceID    string    `json:"namespace_id"`
	TokenID        string    `json:"token_id"`
	IdentityTypeID string    `json:"identity_type_id"`
	Count          int64     `json:"count"`
}

type Policy struct {
	ID             string     `json:"id"`
	NamespaceID    string     `json:"namespace_id"`
	Kind           string     `json:"kind"`
	Name           string     `json:"name"`
	Description    string     `json:"description"`
	CurrentVersion int32      `json:"current_version"`
	DraftYaml      *string    `json:"draft_yaml"`
	DraftUpdatedBy *string    `json:"draft_updated_by"`
	DraftUpdatedAt *time.Time `json:"draft_updated_at"`
	CreatedBy      string     `json:"created_by"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

type PolicyBinding struct {
	ID              string    `json:"id"`
	PolicyID        string    `json:"policy_id"`
	Kind            string    `json:"kind"`
	NamespaceID     string    `json:"namespace_id"`
	SiteID          *string   `json:"site_id"`
	Client          *string   `json:"client"`
	EndpointGroupID *string   `json:"endpoint_group_id"`
	CreatedBy       string    `json:"created_by"`
	CreatedAt       time.Time `json:"created_at"`
}

type PolicyVersion struct {
	PolicyID  string          `json:"policy_id"`
	Version   int32           `json:"version"`
	Spec      json.RawMessage `json:"spec"`
	SpecYaml  string          `json:"spec_yaml"`
	Comment   string          `json:"comment"`
	CreatedBy string          `json:"created_by"`
	CreatedAt time.Time       `json:"created_at"`
}

type Proxy struct {
	ID                       string     `json:"id"`
	Hkey                     int64      `json:"hkey"`
	NamespaceID              string     `json:"namespace_id"`
	Scheme                   string     `json:"scheme"`
	Host                     string     `json:"host"`
	Port                     int32      `json:"port"`
	UsernameHint             string     `json:"username_hint"`
	DisplayUrl               string     `json:"display_url"`
	UrlHash                  []byte     `json:"url_hash"`
	UrlCiphertext            []byte     `json:"url_ciphertext"`
	UrlWrappedDek            []byte     `json:"url_wrapped_dek"`
	UrlKekID                 string     `json:"url_kek_id"`
	UrlVersion               int32      `json:"url_version"`
	Kind                     string     `json:"kind"`
	Region                   string     `json:"region"`
	City                     string     `json:"city"`
	Provider                 string     `json:"provider"`
	MaxConcurrency           int32      `json:"max_concurrency"`
	Tags                     []string   `json:"tags"`
	SessionTemplate          string     `json:"session_template"`
	State                    string     `json:"state"`
	StateReason              string     `json:"state_reason"`
	StateChangedAt           time.Time  `json:"state_changed_at"`
	BanUntil                 *time.Time `json:"ban_until"`
	CooldownUntil            *time.Time `json:"cooldown_until"`
	ConsecutiveCheckFailures int32      `json:"consecutive_check_failures"`
	LastCheckAt              *time.Time `json:"last_check_at"`
	LastCheckOk              *bool      `json:"last_check_ok"`
	LastLatencyMs            *int32     `json:"last_latency_ms"`
	ExitIp                   string     `json:"exit_ip"`
	NextCheckAt              time.Time  `json:"next_check_at"`
	CreatedAt                time.Time  `json:"created_at"`
	UpdatedAt                time.Time  `json:"updated_at"`
}

type ProxyBinding struct {
	IdentityID   string      `json:"identity_id"`
	ProxyID      string      `json:"proxy_id"`
	BoundAt      time.Time   `json:"bound_at"`
	RebindDay    pgtype.Date `json:"rebind_day"`
	RebindsToday int32       `json:"rebinds_today"`
}

type RiskEvent struct {
	ID              string     `json:"id"`
	CreatedAt       time.Time  `json:"created_at"`
	TenantID        string     `json:"tenant_id"`
	NamespaceID     string     `json:"namespace_id"`
	SiteID          string     `json:"site_id"`
	EndpointGroupID string     `json:"endpoint_group_id"`
	IdentityID      string     `json:"identity_id"`
	ProxyID         string     `json:"proxy_id"`
	LeaseID         string     `json:"lease_id"`
	ReportID        string     `json:"report_id"`
	Node            string     `json:"node"`
	TokenID         string     `json:"token_id"`
	Uri             string     `json:"uri"`
	Method          string     `json:"method"`
	HttpStatus      int32      `json:"http_status"`
	BusinessCode    string     `json:"business_code"`
	ErrorKind       string     `json:"error_kind"`
	Markers         []string   `json:"markers"`
	Outcome         string     `json:"outcome"`
	Blame           string     `json:"blame"`
	Rule            string     `json:"rule"`
	LatencyMs       int32      `json:"latency_ms"`
	ResponseBytes   int64      `json:"response_bytes"`
	StartedAt       *time.Time `json:"started_at"`
	FinishedAt      *time.Time `json:"finished_at"`
}

type RoleBinding struct {
	ID               string    `json:"id"`
	UserID           string    `json:"user_id"`
	TenantID         string    `json:"tenant_id"`
	Role             string    `json:"role"`
	NamespaceID      *string   `json:"namespace_id"`
	SiteIds          []string  `json:"site_ids"`
	ExtraPermissions []string  `json:"extra_permissions"`
	CreatedBy        string    `json:"created_by"`
	CreatedAt        time.Time `json:"created_at"`
}

type Secret struct {
	ID             string     `json:"id"`
	NamespaceID    string     `json:"namespace_id"`
	Path           string     `json:"path"`
	Description    string     `json:"description"`
	Tags           []string   `json:"tags"`
	CurrentVersion int32      `json:"current_version"`
	ExpiresAt      *time.Time `json:"expires_at"`
	LastAccessedAt *time.Time `json:"last_accessed_at"`
	CreatedBy      string     `json:"created_by"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

type SecretVersion struct {
	SecretID   string    `json:"secret_id"`
	Version    int32     `json:"version"`
	Ciphertext []byte    `json:"ciphertext"`
	WrappedDek []byte    `json:"wrapped_dek"`
	KekID      string    `json:"kek_id"`
	CreatedBy  string    `json:"created_by"`
	CreatedAt  time.Time `json:"created_at"`
}

type Site struct {
	ID           string     `json:"id"`
	Hkey         int64      `json:"hkey"`
	NamespaceID  string     `json:"namespace_id"`
	Name         string     `json:"name"`
	DisplayName  string     `json:"display_name"`
	Description  string     `json:"description"`
	Clients      []string   `json:"clients"`
	Paused       bool       `json:"paused"`
	PausedReason string     `json:"paused_reason"`
	PausedAt     *time.Time `json:"paused_at"`
	PausedBy     string     `json:"paused_by"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}

type StateEvent struct {
	ID              string          `json:"id"`
	CreatedAt       time.Time       `json:"created_at"`
	TenantID        string          `json:"tenant_id"`
	NamespaceID     string          `json:"namespace_id"`
	SiteID          string          `json:"site_id"`
	SubjectKind     string          `json:"subject_kind"`
	SubjectID       string          `json:"subject_id"`
	EndpointGroupID string          `json:"endpoint_group_id"`
	FromState       string          `json:"from_state"`
	ToState         string          `json:"to_state"`
	Action          string          `json:"action"`
	Scope           string          `json:"scope"`
	Until           *time.Time      `json:"until"`
	Permanent       bool            `json:"permanent"`
	Outcome         string          `json:"outcome"`
	PolicyID        string          `json:"policy_id"`
	PolicyVersion   int32           `json:"policy_version"`
	Rule            string          `json:"rule"`
	ReportID        string          `json:"report_id"`
	LeaseID         string          `json:"lease_id"`
	Actor           string          `json:"actor"`
	Reason          string          `json:"reason"`
	Shadow          bool            `json:"shadow"`
	Details         json.RawMessage `json:"details"`
}

type SystemKey struct {
	Name       string    `json:"name"`
	Ciphertext []byte    `json:"ciphertext"`
	WrappedDek []byte    `json:"wrapped_dek"`
	KekID      string    `json:"kek_id"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type SystemSetting struct {
	Key       string          `json:"key"`
	Value     json.RawMessage `json:"value"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type Tenant struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	DisplayName string    `json:"display_name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type UriRule struct {
	ID              string    `json:"id"`
	EndpointGroupID string    `json:"endpoint_group_id"`
	Kind            string    `json:"kind"`
	Pattern         string    `json:"pattern"`
	Position        int32     `json:"position"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type User struct {
	ID                string     `json:"id"`
	Username          string     `json:"username"`
	DisplayName       string     `json:"display_name"`
	Email             string     `json:"email"`
	PasswordHash      string     `json:"password_hash"`
	IsPlatformAdmin   bool       `json:"is_platform_admin"`
	Disabled          bool       `json:"disabled"`
	Locale            string     `json:"locale"`
	LastLoginAt       *time.Time `json:"last_login_at"`
	LastLoginIp       string     `json:"last_login_ip"`
	PasswordChangedAt *time.Time `json:"password_changed_at"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
}
