// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: state_events.sql

package identitysvcdb

import (
	"context"
	"time"
)

type StateEventCopyParams struct {
	ID          string    `json:"id"`
	CreatedAt   time.Time `json:"created_at"`
	TenantID    string    `json:"tenant_id"`
	NamespaceID string    `json:"namespace_id"`
	SiteID      string    `json:"site_id"`
	SubjectKind string    `json:"subject_kind"`
	SubjectID   string    `json:"subject_id"`
	FromState   string    `json:"from_state"`
	ToState     string    `json:"to_state"`
	Action      string    `json:"action"`
	Actor       string    `json:"actor"`
	Reason      string    `json:"reason"`
}

const stateEventsRecentBySubject = `-- name: StateEventsRecentBySubject :many
SELECT id, created_at, site_id, subject_kind, subject_id, endpoint_group_id, from_state, to_state, action, scope,
       until, permanent, outcome, policy_id, policy_version, rule, report_id, lease_id, actor, reason, shadow
FROM state_events
WHERE namespace_id = $1
  AND subject_kind = $2
  AND subject_id = $3
ORDER BY created_at DESC, id DESC
LIMIT $4::integer
`

type StateEventsRecentBySubjectParams struct {
	NamespaceID string `json:"namespace_id"`
	SubjectKind string `json:"subject_kind"`
	SubjectID   string `json:"subject_id"`
	MaxRows     int32  `json:"max_rows"`
}

type StateEventsRecentBySubjectRow struct {
	ID              string     `json:"id"`
	CreatedAt       time.Time  `json:"created_at"`
	SiteID          string     `json:"site_id"`
	SubjectKind     string     `json:"subject_kind"`
	SubjectID       string     `json:"subject_id"`
	EndpointGroupID string     `json:"endpoint_group_id"`
	FromState       string     `json:"from_state"`
	ToState         string     `json:"to_state"`
	Action          string     `json:"action"`
	Scope           string     `json:"scope"`
	Until           *time.Time `json:"until"`
	Permanent       bool       `json:"permanent"`
	Outcome         string     `json:"outcome"`
	PolicyID        string     `json:"policy_id"`
	PolicyVersion   int32      `json:"policy_version"`
	Rule            string     `json:"rule"`
	ReportID        string     `json:"report_id"`
	LeaseID         string     `json:"lease_id"`
	Actor           string     `json:"actor"`
	Reason          string     `json:"reason"`
	Shadow          bool       `json:"shadow"`
}

func (q *Queries) StateEventsRecentBySubject(ctx context.Context, arg StateEventsRecentBySubjectParams) ([]StateEventsRecentBySubjectRow, error) {
	rows, err := q.db.Query(ctx, stateEventsRecentBySubject,
		arg.NamespaceID,
		arg.SubjectKind,
		arg.SubjectID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StateEventsRecentBySubjectRow{}
	for rows.Next() {
		var i StateEventsRecentBySubjectRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.SiteID,
			&i.SubjectKind,
			&i.SubjectID,
			&i.EndpointGroupID,
			&i.FromState,
			&i.ToState,
			&i.Action,
			&i.Scope,
			&i.Until,
			&i.Permanent,
			&i.Outcome,
			&i.PolicyID,
			&i.PolicyVersion,
			&i.Rule,
			&i.ReportID,
			&i.LeaseID,
			&i.Actor,
			&i.Reason,
			&i.Shadow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
