// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: binding.sql

package policysvcdb

import (
	"context"
	"time"
)

const bindingDelete = `-- name: BindingDelete :execrows
DELETE FROM policy_bindings WHERE id = $1 AND policy_id = $2
`

type BindingDeleteParams struct {
	ID       string `json:"id"`
	PolicyID string `json:"policy_id"`
}

// Deletes a binding only while it still binds the expected policy (a binding
// keeps its id when the policy at its target is replaced).
func (q *Queries) BindingDelete(ctx context.Context, arg BindingDeleteParams) (int64, error) {
	result, err := q.db.Exec(ctx, bindingDelete, arg.ID, arg.PolicyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bindingGet = `-- name: BindingGet :one
SELECT b.id, b.policy_id, b.kind, b.namespace_id, b.site_id, b.client, b.endpoint_group_id,
       b.created_by, b.created_at, p.name AS policy_name
FROM policy_bindings b
JOIN policies p ON p.id = b.policy_id
WHERE b.id = $1
`

type BindingGetRow struct {
	ID              string    `json:"id"`
	PolicyID        string    `json:"policy_id"`
	Kind            string    `json:"kind"`
	NamespaceID     string    `json:"namespace_id"`
	SiteID          *string   `json:"site_id"`
	Client          *string   `json:"client"`
	EndpointGroupID *string   `json:"endpoint_group_id"`
	CreatedBy       string    `json:"created_by"`
	CreatedAt       time.Time `json:"created_at"`
	PolicyName      string    `json:"policy_name"`
}

func (q *Queries) BindingGet(ctx context.Context, id string) (BindingGetRow, error) {
	row := q.db.QueryRow(ctx, bindingGet, id)
	var i BindingGetRow
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.Kind,
		&i.NamespaceID,
		&i.SiteID,
		&i.Client,
		&i.EndpointGroupID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PolicyName,
	)
	return i, err
}

const bindingGetByTarget = `-- name: BindingGetByTarget :one
SELECT id, policy_id
FROM policy_bindings
WHERE namespace_id = $1
  AND kind = $2
  AND coalesce(site_id, '') = $3::text
  AND coalesce(client, '') = $4::text
  AND coalesce(endpoint_group_id, '') = $5::text
FOR UPDATE
`

type BindingGetByTargetParams struct {
	NamespaceID     string `json:"namespace_id"`
	Kind            string `json:"kind"`
	SiteID          string `json:"site_id"`
	Client          string `json:"client"`
	EndpointGroupID string `json:"endpoint_group_id"`
}

type BindingGetByTargetRow struct {
	ID       string `json:"id"`
	PolicyID string `json:"policy_id"`
}

func (q *Queries) BindingGetByTarget(ctx context.Context, arg BindingGetByTargetParams) (BindingGetByTargetRow, error) {
	row := q.db.QueryRow(ctx, bindingGetByTarget,
		arg.NamespaceID,
		arg.Kind,
		arg.SiteID,
		arg.Client,
		arg.EndpointGroupID,
	)
	var i BindingGetByTargetRow
	err := row.Scan(&i.ID, &i.PolicyID)
	return i, err
}

const bindingInsertIfAbsent = `-- name: BindingInsertIfAbsent :execrows
INSERT INTO policy_bindings (id, policy_id, kind, namespace_id, created_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (namespace_id, kind, coalesce(site_id, ''), coalesce(client, ''), coalesce(endpoint_group_id, ''))
DO NOTHING
`

type BindingInsertIfAbsentParams struct {
	ID          string `json:"id"`
	PolicyID    string `json:"policy_id"`
	Kind        string `json:"kind"`
	NamespaceID string `json:"namespace_id"`
	CreatedBy   string `json:"created_by"`
}

func (q *Queries) BindingInsertIfAbsent(ctx context.Context, arg BindingInsertIfAbsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, bindingInsertIfAbsent,
		arg.ID,
		arg.PolicyID,
		arg.Kind,
		arg.NamespaceID,
		arg.CreatedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bindingListByNamespace = `-- name: BindingListByNamespace :many

SELECT b.id, b.policy_id, b.kind, b.namespace_id, b.site_id, b.client, b.endpoint_group_id,
       b.created_by, b.created_at, p.name AS policy_name
FROM policy_bindings b
JOIN policies p ON p.id = b.policy_id
WHERE b.namespace_id = $1
  AND ($2::text = '' OR b.kind = $2::text)
  AND ($3::text = '' OR b.site_id IS NULL OR b.site_id = $3::text)
ORDER BY b.kind, b.site_id NULLS FIRST, b.client NULLS FIRST, b.endpoint_group_id NULLS FIRST
LIMIT $4
`

type BindingListByNamespaceParams struct {
	NamespaceID string `json:"namespace_id"`
	Kind        string `json:"kind"`
	SiteID      string `json:"site_id"`
	RowLimit    int32  `json:"row_limit"`
}

type BindingListByNamespaceRow struct {
	ID              string    `json:"id"`
	PolicyID        string    `json:"policy_id"`
	Kind            string    `json:"kind"`
	NamespaceID     string    `json:"namespace_id"`
	SiteID          *string   `json:"site_id"`
	Client          *string   `json:"client"`
	EndpointGroupID *string   `json:"endpoint_group_id"`
	CreatedBy       string    `json:"created_by"`
	CreatedAt       time.Time `json:"created_at"`
	PolicyName      string    `json:"policy_name"`
}

// Policy binding queries of the policy administration service.
// Lists the bindings of a namespace. site_id ” selects every binding,
// otherwise the namespace-level bindings and those of that site.
func (q *Queries) BindingListByNamespace(ctx context.Context, arg BindingListByNamespaceParams) ([]BindingListByNamespaceRow, error) {
	rows, err := q.db.Query(ctx, bindingListByNamespace,
		arg.NamespaceID,
		arg.Kind,
		arg.SiteID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BindingListByNamespaceRow{}
	for rows.Next() {
		var i BindingListByNamespaceRow
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.Kind,
			&i.NamespaceID,
			&i.SiteID,
			&i.Client,
			&i.EndpointGroupID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.PolicyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bindingListByPolicies = `-- name: BindingListByPolicies :many
SELECT b.id, b.policy_id, b.kind, b.namespace_id, b.site_id, b.client, b.endpoint_group_id,
       b.created_by, b.created_at, p.name AS policy_name
FROM policy_bindings b
JOIN policies p ON p.id = b.policy_id
WHERE b.policy_id = ANY ($1::text[])
ORDER BY b.policy_id, b.site_id NULLS FIRST, b.client NULLS FIRST, b.endpoint_group_id NULLS FIRST
LIMIT $2
`

type BindingListByPoliciesParams struct {
	PolicyIds []string `json:"policy_ids"`
	RowLimit  int32    `json:"row_limit"`
}

type BindingListByPoliciesRow struct {
	ID              string    `json:"id"`
	PolicyID        string    `json:"policy_id"`
	Kind            string    `json:"kind"`
	NamespaceID     string    `json:"namespace_id"`
	SiteID          *string   `json:"site_id"`
	Client          *string   `json:"client"`
	EndpointGroupID *string   `json:"endpoint_group_id"`
	CreatedBy       string    `json:"created_by"`
	CreatedAt       time.Time `json:"created_at"`
	PolicyName      string    `json:"policy_name"`
}

func (q *Queries) BindingListByPolicies(ctx context.Context, arg BindingListByPoliciesParams) ([]BindingListByPoliciesRow, error) {
	rows, err := q.db.Query(ctx, bindingListByPolicies, arg.PolicyIds, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BindingListByPoliciesRow{}
	for rows.Next() {
		var i BindingListByPoliciesRow
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.Kind,
			&i.NamespaceID,
			&i.SiteID,
			&i.Client,
			&i.EndpointGroupID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.PolicyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bindingListEffective = `-- name: BindingListEffective :many
SELECT b.policy_id, b.kind, b.site_id, b.client, b.endpoint_group_id,
       p.name AS policy_name, p.current_version
FROM policy_bindings b
JOIN policies p ON p.id = b.policy_id AND p.kind = b.kind
WHERE b.namespace_id = $1
  AND p.current_version > 0
  AND (b.site_id IS NULL OR b.site_id = $2::text)
ORDER BY b.created_at, b.id
LIMIT $3
`

type BindingListEffectiveParams struct {
	NamespaceID string `json:"namespace_id"`
	SiteID      string `json:"site_id"`
	RowLimit    int32  `json:"row_limit"`
}

type BindingListEffectiveRow struct {
	PolicyID        string  `json:"policy_id"`
	Kind            string  `json:"kind"`
	SiteID          *string `json:"site_id"`
	Client          *string `json:"client"`
	EndpointGroupID *string `json:"endpoint_group_id"`
	PolicyName      string  `json:"policy_name"`
	CurrentVersion  int32   `json:"current_version"`
}

// Lists the bindings in effect for resolution below a site (site_id ” =
// namespace level only): namespace-level bindings and those of the site whose
// policy has a published version of the binding kind, mirroring the catalog.
func (q *Queries) BindingListEffective(ctx context.Context, arg BindingListEffectiveParams) ([]BindingListEffectiveRow, error) {
	rows, err := q.db.Query(ctx, bindingListEffective, arg.NamespaceID, arg.SiteID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BindingListEffectiveRow{}
	for rows.Next() {
		var i BindingListEffectiveRow
		if err := rows.Scan(
			&i.PolicyID,
			&i.Kind,
			&i.SiteID,
			&i.Client,
			&i.EndpointGroupID,
			&i.PolicyName,
			&i.CurrentVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bindingNamespaceLevelExists = `-- name: BindingNamespaceLevelExists :one
SELECT EXISTS (
    SELECT 1 FROM policy_bindings
    WHERE policy_id = $1 AND site_id IS NULL AND client IS NULL AND endpoint_group_id IS NULL
)::boolean
`

func (q *Queries) BindingNamespaceLevelExists(ctx context.Context, policyID string) (bool, error) {
	row := q.db.QueryRow(ctx, bindingNamespaceLevelExists, policyID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const bindingUpsert = `-- name: BindingUpsert :one
INSERT INTO policy_bindings (id, policy_id, kind, namespace_id, site_id, client, endpoint_group_id, created_by)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8)
ON CONFLICT (namespace_id, kind, coalesce(site_id, ''), coalesce(client, ''), coalesce(endpoint_group_id, ''))
DO UPDATE SET policy_id = EXCLUDED.policy_id, created_by = EXCLUDED.created_by, created_at = now()
RETURNING id, policy_id, kind, namespace_id, site_id, client, endpoint_group_id, created_by, created_at
`

type BindingUpsertParams struct {
	ID              string  `json:"id"`
	PolicyID        string  `json:"policy_id"`
	Kind            string  `json:"kind"`
	NamespaceID     string  `json:"namespace_id"`
	SiteID          *string `json:"site_id"`
	Client          *string `json:"client"`
	EndpointGroupID *string `json:"endpoint_group_id"`
	CreatedBy       string  `json:"created_by"`
}

func (q *Queries) BindingUpsert(ctx context.Context, arg BindingUpsertParams) (PolicyBinding, error) {
	row := q.db.QueryRow(ctx, bindingUpsert,
		arg.ID,
		arg.PolicyID,
		arg.Kind,
		arg.NamespaceID,
		arg.SiteID,
		arg.Client,
		arg.EndpointGroupID,
		arg.CreatedBy,
	)
	var i PolicyBinding
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.Kind,
		&i.NamespaceID,
		&i.SiteID,
		&i.Client,
		&i.EndpointGroupID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
