// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policy.sql

package policysvcdb

import (
	"context"
	"encoding/json"
	"time"
)

const policyCount = `-- name: PolicyCount :one
SELECT count(*)
FROM policies p
WHERE p.namespace_id = $1
  AND ($2::text = '' OR p.kind = $2::text)
  AND ($3::text = '' OR strpos(p.name, $3::text) > 0)
  AND ($4::boolean OR EXISTS (
        SELECT 1 FROM policy_bindings b
        WHERE b.policy_id = p.id
          AND (b.site_id IS NULL OR b.site_id = ANY ($5::text[]))))
`

type PolicyCountParams struct {
	NamespaceID string   `json:"namespace_id"`
	Kind        string   `json:"kind"`
	Search      string   `json:"search"`
	AllSites    bool     `json:"all_sites"`
	SiteIds     []string `json:"site_ids"`
}

func (q *Queries) PolicyCount(ctx context.Context, arg PolicyCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, policyCount,
		arg.NamespaceID,
		arg.Kind,
		arg.Search,
		arg.AllSites,
		arg.SiteIds,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const policyDelete = `-- name: PolicyDelete :execrows
DELETE FROM policies WHERE id = $1
`

func (q *Queries) PolicyDelete(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, policyDelete, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const policyGet = `-- name: PolicyGet :one

SELECT id, namespace_id, kind, name, description, current_version, draft_yaml, draft_updated_by, draft_updated_at, created_by, created_at, updated_at FROM policies WHERE id = $1
`

// Queries of the policy administration service (internal/policysvc).
// Regenerate with: sqlc generate -f internal/policysvc/sqlc.yaml
func (q *Queries) PolicyGet(ctx context.Context, id string) (Policy, error) {
	row := q.db.QueryRow(ctx, policyGet, id)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.NamespaceID,
		&i.Kind,
		&i.Name,
		&i.Description,
		&i.CurrentVersion,
		&i.DraftYaml,
		&i.DraftUpdatedBy,
		&i.DraftUpdatedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const policyGetByName = `-- name: PolicyGetByName :one
SELECT id, current_version
FROM policies
WHERE namespace_id = $1 AND kind = $2 AND name = $3
`

type PolicyGetByNameParams struct {
	NamespaceID string `json:"namespace_id"`
	Kind        string `json:"kind"`
	Name        string `json:"name"`
}

type PolicyGetByNameRow struct {
	ID             string `json:"id"`
	CurrentVersion int32  `json:"current_version"`
}

func (q *Queries) PolicyGetByName(ctx context.Context, arg PolicyGetByNameParams) (PolicyGetByNameRow, error) {
	row := q.db.QueryRow(ctx, policyGetByName, arg.NamespaceID, arg.Kind, arg.Name)
	var i PolicyGetByNameRow
	err := row.Scan(&i.ID, &i.CurrentVersion)
	return i, err
}

const policyGetForUpdate = `-- name: PolicyGetForUpdate :one
SELECT id, namespace_id, kind, name, description, current_version, draft_yaml, draft_updated_by, draft_updated_at, created_by, created_at, updated_at FROM policies WHERE id = $1 FOR UPDATE
`

func (q *Queries) PolicyGetForUpdate(ctx context.Context, id string) (Policy, error) {
	row := q.db.QueryRow(ctx, policyGetForUpdate, id)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.NamespaceID,
		&i.Kind,
		&i.Name,
		&i.Description,
		&i.CurrentVersion,
		&i.DraftYaml,
		&i.DraftUpdatedBy,
		&i.DraftUpdatedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const policyInsert = `-- name: PolicyInsert :one
INSERT INTO policies (id, namespace_id, kind, name, description, draft_yaml, draft_updated_by, draft_updated_at, created_by)
VALUES ($1, $2, $3, $4, $5,
        $6::text, $7::text, now(), $7::text)
RETURNING id, namespace_id, kind, name, description, current_version, draft_yaml, draft_updated_by, draft_updated_at, created_by, created_at, updated_at
`

type PolicyInsertParams struct {
	ID          string `json:"id"`
	NamespaceID string `json:"namespace_id"`
	Kind        string `json:"kind"`
	Name        string `json:"name"`
	Description string `json:"description"`
	DraftYaml   string `json:"draft_yaml"`
	CreatedBy   string `json:"created_by"`
}

func (q *Queries) PolicyInsert(ctx context.Context, arg PolicyInsertParams) (Policy, error) {
	row := q.db.QueryRow(ctx, policyInsert,
		arg.ID,
		arg.NamespaceID,
		arg.Kind,
		arg.Name,
		arg.Description,
		arg.DraftYaml,
		arg.CreatedBy,
	)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.NamespaceID,
		&i.Kind,
		&i.Name,
		&i.Description,
		&i.CurrentVersion,
		&i.DraftYaml,
		&i.DraftUpdatedBy,
		&i.DraftUpdatedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const policyInsertIfAbsent = `-- name: PolicyInsertIfAbsent :many
INSERT INTO policies (id, namespace_id, kind, name, description, current_version, created_by)
VALUES ($1, $2, $3, $4, $5, 1, $6)
ON CONFLICT (namespace_id, kind, name) DO NOTHING
RETURNING id
`

type PolicyInsertIfAbsentParams struct {
	ID          string `json:"id"`
	NamespaceID string `json:"namespace_id"`
	Kind        string `json:"kind"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CreatedBy   string `json:"created_by"`
}

func (q *Queries) PolicyInsertIfAbsent(ctx context.Context, arg PolicyInsertIfAbsentParams) ([]string, error) {
	rows, err := q.db.Query(ctx, policyInsertIfAbsent,
		arg.ID,
		arg.NamespaceID,
		arg.Kind,
		arg.Name,
		arg.Description,
		arg.CreatedBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const policyList = `-- name: PolicyList :many
SELECT p.id, p.namespace_id, p.kind, p.name, p.description, p.current_version,
       (p.draft_yaml IS NOT NULL)::boolean AS has_draft,
       p.draft_updated_by, p.draft_updated_at, p.created_by, p.created_at, p.updated_at
FROM policies p
WHERE p.namespace_id = $1
  AND ($2::text = '' OR p.kind = $2::text)
  AND ($3::text = '' OR strpos(p.name, $3::text) > 0)
  AND ($4::boolean OR EXISTS (
        SELECT 1 FROM policy_bindings b
        WHERE b.policy_id = p.id
          AND (b.site_id IS NULL OR b.site_id = ANY ($5::text[]))))
  AND ($6::text = ''
       OR (p.kind, p.name) > ($6::text, $7::text))
ORDER BY p.kind, p.name
LIMIT $8
`

type PolicyListParams struct {
	NamespaceID string   `json:"namespace_id"`
	Kind        string   `json:"kind"`
	Search      string   `json:"search"`
	AllSites    bool     `json:"all_sites"`
	SiteIds     []string `json:"site_ids"`
	AfterKind   string   `json:"after_kind"`
	AfterName   string   `json:"after_name"`
	PageLimit   int32    `json:"page_limit"`
}

type PolicyListRow struct {
	ID             string     `json:"id"`
	NamespaceID    string     `json:"namespace_id"`
	Kind           string     `json:"kind"`
	Name           string     `json:"name"`
	Description    string     `json:"description"`
	CurrentVersion int32      `json:"current_version"`
	HasDraft       bool       `json:"has_draft"`
	DraftUpdatedBy *string    `json:"draft_updated_by"`
	DraftUpdatedAt *time.Time `json:"draft_updated_at"`
	CreatedBy      string     `json:"created_by"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

// Lists policies without their YAML bodies. Site-restricted callers
// (all_sites = false) only see policies bound at namespace level or on one of
// site_ids. Keyset pagination on (kind, name).
func (q *Queries) PolicyList(ctx context.Context, arg PolicyListParams) ([]PolicyListRow, error) {
	rows, err := q.db.Query(ctx, policyList,
		arg.NamespaceID,
		arg.Kind,
		arg.Search,
		arg.AllSites,
		arg.SiteIds,
		arg.AfterKind,
		arg.AfterName,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PolicyListRow{}
	for rows.Next() {
		var i PolicyListRow
		if err := rows.Scan(
			&i.ID,
			&i.NamespaceID,
			&i.Kind,
			&i.Name,
			&i.Description,
			&i.CurrentVersion,
			&i.HasDraft,
			&i.DraftUpdatedBy,
			&i.DraftUpdatedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const policyLockKind = `-- name: PolicyLockKind :exec
SELECT pg_advisory_xact_lock(hashtextextended('spinneret:policy:' || $1::text || ':' || $2::text, 0))
`

type PolicyLockKindParams struct {
	NamespaceID string `json:"namespace_id"`
	Kind        string `json:"kind"`
}

// Serializes publish, rollback and delete operations of one namespace and
// kind so extends chains are validated against a stable set of policies.
func (q *Queries) PolicyLockKind(ctx context.Context, arg PolicyLockKindParams) error {
	_, err := q.db.Exec(ctx, policyLockKind, arg.NamespaceID, arg.Kind)
	return err
}

const policyMarkPublished = `-- name: PolicyMarkPublished :exec
UPDATE policies SET current_version = 1, updated_at = now() WHERE id = $1 AND current_version = 0
`

func (q *Queries) PolicyMarkPublished(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, policyMarkPublished, id)
	return err
}

const policyPublishedChildren = `-- name: PolicyPublishedChildren :many
SELECT p.name
FROM policies p
JOIN policy_versions v ON v.policy_id = p.id AND v.version = p.current_version
WHERE p.namespace_id = $1 AND p.kind = $2
  AND v.spec ->> 'extends' = $3::text
  AND p.id <> $4
ORDER BY p.name
LIMIT 10
`

type PolicyPublishedChildrenParams struct {
	NamespaceID string `json:"namespace_id"`
	Kind        string `json:"kind"`
	Name        string `json:"name"`
	ID          string `json:"id"`
}

func (q *Queries) PolicyPublishedChildren(ctx context.Context, arg PolicyPublishedChildrenParams) ([]string, error) {
	rows, err := q.db.Query(ctx, policyPublishedChildren,
		arg.NamespaceID,
		arg.Kind,
		arg.Name,
		arg.ID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const policyPublishedExtends = `-- name: PolicyPublishedExtends :many
SELECT p.name, coalesce(v.spec ->> 'extends', '')::text AS extends
FROM policies p
JOIN policy_versions v ON v.policy_id = p.id AND v.version = p.current_version
WHERE p.namespace_id = $1 AND p.kind = $2
ORDER BY p.name
LIMIT $3
`

type PolicyPublishedExtendsParams struct {
	NamespaceID string `json:"namespace_id"`
	Kind        string `json:"kind"`
	RowLimit    int32  `json:"row_limit"`
}

type PolicyPublishedExtendsRow struct {
	Name    string `json:"name"`
	Extends string `json:"extends"`
}

// Lists (name, extends) of every published policy of a kind, bounded by
// row_limit, for extends depth checks of descendants.
func (q *Queries) PolicyPublishedExtends(ctx context.Context, arg PolicyPublishedExtendsParams) ([]PolicyPublishedExtendsRow, error) {
	rows, err := q.db.Query(ctx, policyPublishedExtends, arg.NamespaceID, arg.Kind, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PolicyPublishedExtendsRow{}
	for rows.Next() {
		var i PolicyPublishedExtendsRow
		if err := rows.Scan(&i.Name, &i.Extends); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const policyPublishedSpecByName = `-- name: PolicyPublishedSpecByName :one
SELECT p.id, p.name, p.current_version, v.spec
FROM policies p
JOIN policy_versions v ON v.policy_id = p.id AND v.version = p.current_version
WHERE p.namespace_id = $1 AND p.kind = $2 AND p.name = $3
`

type PolicyPublishedSpecByNameParams struct {
	NamespaceID string `json:"namespace_id"`
	Kind        string `json:"kind"`
	Name        string `json:"name"`
}

type PolicyPublishedSpecByNameRow struct {
	ID             string          `json:"id"`
	Name           string          `json:"name"`
	CurrentVersion int32           `json:"current_version"`
	Spec           json.RawMessage `json:"spec"`
}

func (q *Queries) PolicyPublishedSpecByName(ctx context.Context, arg PolicyPublishedSpecByNameParams) (PolicyPublishedSpecByNameRow, error) {
	row := q.db.QueryRow(ctx, policyPublishedSpecByName, arg.NamespaceID, arg.Kind, arg.Name)
	var i PolicyPublishedSpecByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CurrentVersion,
		&i.Spec,
	)
	return i, err
}

const policySaveDraft = `-- name: PolicySaveDraft :one
UPDATE policies
SET draft_yaml       = $1::text,
    draft_updated_by = $2::text,
    draft_updated_at = now(),
    description      = CASE WHEN current_version = 0 THEN $3::text ELSE description END,
    updated_at       = now()
WHERE id = $4
RETURNING id, namespace_id, kind, name, description, current_version, draft_yaml, draft_updated_by, draft_updated_at, created_by, created_at, updated_at
`

type PolicySaveDraftParams struct {
	DraftYaml   string `json:"draft_yaml"`
	Actor       string `json:"actor"`
	Description string `json:"description"`
	ID          string `json:"id"`
}

func (q *Queries) PolicySaveDraft(ctx context.Context, arg PolicySaveDraftParams) (Policy, error) {
	row := q.db.QueryRow(ctx, policySaveDraft,
		arg.DraftYaml,
		arg.Actor,
		arg.Description,
		arg.ID,
	)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.NamespaceID,
		&i.Kind,
		&i.Name,
		&i.Description,
		&i.CurrentVersion,
		&i.DraftYaml,
		&i.DraftUpdatedBy,
		&i.DraftUpdatedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const policySetPublished = `-- name: PolicySetPublished :one
UPDATE policies
SET current_version  = $1::integer,
    description      = $2::text,
    draft_yaml       = CASE WHEN $3::boolean THEN NULL ELSE draft_yaml END,
    draft_updated_by = CASE WHEN $3::boolean THEN NULL ELSE draft_updated_by END,
    draft_updated_at = CASE WHEN $3::boolean THEN NULL ELSE draft_updated_at END,
    updated_at       = now()
WHERE id = $4
RETURNING id, namespace_id, kind, name, description, current_version, draft_yaml, draft_updated_by, draft_updated_at, created_by, created_at, updated_at
`

type PolicySetPublishedParams struct {
	Version     int32  `json:"version"`
	Description string `json:"description"`
	ClearDraft  bool   `json:"clear_draft"`
	ID          string `json:"id"`
}

func (q *Queries) PolicySetPublished(ctx context.Context, arg PolicySetPublishedParams) (Policy, error) {
	row := q.db.QueryRow(ctx, policySetPublished,
		arg.Version,
		arg.Description,
		arg.ClearDraft,
		arg.ID,
	)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.NamespaceID,
		&i.Kind,
		&i.Name,
		&i.Description,
		&i.CurrentVersion,
		&i.DraftYaml,
		&i.DraftUpdatedBy,
		&i.DraftUpdatedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const policyVersionCount = `-- name: PolicyVersionCount :one
SELECT count(*) FROM policy_versions WHERE policy_id = $1
`

func (q *Queries) PolicyVersionCount(ctx context.Context, policyID string) (int64, error) {
	row := q.db.QueryRow(ctx, policyVersionCount, policyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const policyVersionGet = `-- name: PolicyVersionGet :one
SELECT policy_id, version, spec, spec_yaml, comment, created_by, created_at FROM policy_versions WHERE policy_id = $1 AND version = $2
`

type PolicyVersionGetParams struct {
	PolicyID string `json:"policy_id"`
	Version  int32  `json:"version"`
}

func (q *Queries) PolicyVersionGet(ctx context.Context, arg PolicyVersionGetParams) (PolicyVersion, error) {
	row := q.db.QueryRow(ctx, policyVersionGet, arg.PolicyID, arg.Version)
	var i PolicyVersion
	err := row.Scan(
		&i.PolicyID,
		&i.Version,
		&i.Spec,
		&i.SpecYaml,
		&i.Comment,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const policyVersionInsert = `-- name: PolicyVersionInsert :exec
INSERT INTO policy_versions (policy_id, version, spec, spec_yaml, comment, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
`

type PolicyVersionInsertParams struct {
	PolicyID  string          `json:"policy_id"`
	Version   int32           `json:"version"`
	Spec      json.RawMessage `json:"spec"`
	SpecYaml  string          `json:"spec_yaml"`
	Comment   string          `json:"comment"`
	CreatedBy string          `json:"created_by"`
}

func (q *Queries) PolicyVersionInsert(ctx context.Context, arg PolicyVersionInsertParams) error {
	_, err := q.db.Exec(ctx, policyVersionInsert,
		arg.PolicyID,
		arg.Version,
		arg.Spec,
		arg.SpecYaml,
		arg.Comment,
		arg.CreatedBy,
	)
	return err
}

const policyVersionInsertIfAbsent = `-- name: PolicyVersionInsertIfAbsent :execrows
INSERT INTO policy_versions (policy_id, version, spec, spec_yaml, comment, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (policy_id, version) DO NOTHING
`

type PolicyVersionInsertIfAbsentParams struct {
	PolicyID  string          `json:"policy_id"`
	Version   int32           `json:"version"`
	Spec      json.RawMessage `json:"spec"`
	SpecYaml  string          `json:"spec_yaml"`
	Comment   string          `json:"comment"`
	CreatedBy string          `json:"created_by"`
}

func (q *Queries) PolicyVersionInsertIfAbsent(ctx context.Context, arg PolicyVersionInsertIfAbsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, policyVersionInsertIfAbsent,
		arg.PolicyID,
		arg.Version,
		arg.Spec,
		arg.SpecYaml,
		arg.Comment,
		arg.CreatedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const policyVersionList = `-- name: PolicyVersionList :many
SELECT policy_id, version, spec, spec_yaml, comment, created_by, created_at FROM policy_versions
WHERE policy_id = $1
  AND ($2::integer = 0 OR version < $2::integer)
ORDER BY version DESC
LIMIT $3
`

type PolicyVersionListParams struct {
	PolicyID      string `json:"policy_id"`
	BeforeVersion int32  `json:"before_version"`
	PageLimit     int32  `json:"page_limit"`
}

func (q *Queries) PolicyVersionList(ctx context.Context, arg PolicyVersionListParams) ([]PolicyVersion, error) {
	rows, err := q.db.Query(ctx, policyVersionList, arg.PolicyID, arg.BeforeVersion, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PolicyVersion{}
	for rows.Next() {
		var i PolicyVersion
		if err := rows.Scan(
			&i.PolicyID,
			&i.Version,
			&i.Spec,
			&i.SpecYaml,
			&i.Comment,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
