// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package analyticsdb

import (
	"context"
	"time"
)

const analyticsAcquireSeries = `-- name: AnalyticsAcquireSeries :many
SELECT date_bin(make_interval(secs => $1::double precision), bucket, 'epoch'::timestamptz)::timestamptz AS ts,
       result,
       sum(count)::bigint AS count
FROM acquire_stats_minutely
WHERE namespace_id = $2
  AND bucket >= $3
  AND bucket < $4
  AND ($5::boolean OR site_id = ANY($6::text[]))
  AND (cardinality($7::text[]) = 0 OR endpoint_group_id = ANY($7::text[]))
GROUP BY 1, 2
ORDER BY 1, 2
`

type AnalyticsAcquireSeriesParams struct {
	StepSeconds      float64   `json:"step_seconds"`
	NamespaceID      string    `json:"namespace_id"`
	FromBucket       time.Time `json:"from_bucket"`
	ToBucket         time.Time `json:"to_bucket"`
	AllSites         bool      `json:"all_sites"`
	SiteIds          []string  `json:"site_ids"`
	EndpointGroupIds []string  `json:"endpoint_group_ids"`
}

type AnalyticsAcquireSeriesRow struct {
	Ts     time.Time `json:"ts"`
	Result string    `json:"result"`
	Count  int64     `json:"count"`
}

// AnalyticsAcquireSeries buckets acquire results by a fixed step aligned to
// the Unix epoch. all_sites disables the site filter; an empty
// endpoint_group_ids array disables the endpoint group filter.
func (q *Queries) AnalyticsAcquireSeries(ctx context.Context, arg AnalyticsAcquireSeriesParams) ([]AnalyticsAcquireSeriesRow, error) {
	rows, err := q.db.Query(ctx, analyticsAcquireSeries,
		arg.StepSeconds,
		arg.NamespaceID,
		arg.FromBucket,
		arg.ToBucket,
		arg.AllSites,
		arg.SiteIds,
		arg.EndpointGroupIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsAcquireSeriesRow{}
	for rows.Next() {
		var i AnalyticsAcquireSeriesRow
		if err := rows.Scan(&i.Ts, &i.Result, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsAcquireTotalsBySite = `-- name: AnalyticsAcquireTotalsBySite :many
SELECT site_id, result, sum(count)::bigint AS count
FROM acquire_stats_minutely
WHERE namespace_id = $1
  AND bucket >= $2
  AND bucket < $3
  AND site_id = ANY($4::text[])
GROUP BY site_id, result
`

type AnalyticsAcquireTotalsBySiteParams struct {
	NamespaceID string    `json:"namespace_id"`
	FromBucket  time.Time `json:"from_bucket"`
	ToBucket    time.Time `json:"to_bucket"`
	SiteIds     []string  `json:"site_ids"`
}

type AnalyticsAcquireTotalsBySiteRow struct {
	SiteID string `json:"site_id"`
	Result string `json:"result"`
	Count  int64  `json:"count"`
}

// AnalyticsAcquireTotalsBySite sums acquire results per site over a bucket range.
func (q *Queries) AnalyticsAcquireTotalsBySite(ctx context.Context, arg AnalyticsAcquireTotalsBySiteParams) ([]AnalyticsAcquireTotalsBySiteRow, error) {
	rows, err := q.db.Query(ctx, analyticsAcquireTotalsBySite,
		arg.NamespaceID,
		arg.FromBucket,
		arg.ToBucket,
		arg.SiteIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsAcquireTotalsBySiteRow{}
	for rows.Next() {
		var i AnalyticsAcquireTotalsBySiteRow
		if err := rows.Scan(&i.SiteID, &i.Result, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsHeatmapIdentities = `-- name: AnalyticsHeatmapIdentities :many
SELECT i.id,
       i.hkey,
       i.state,
       i.region,
       i.ban_until,
       COALESCE(a.external_ref, '')::text AS account_ref,
       COALESCE(a.hkey, 0)::bigint AS account_hkey
FROM identities i
LEFT JOIN accounts a ON a.id = i.account_id
WHERE i.site_id = $1
  AND i.client = $2
  AND i.state = ANY($3::text[])
  AND i.id > $4
ORDER BY i.id
LIMIT $5
`

type AnalyticsHeatmapIdentitiesParams struct {
	SiteID  string   `json:"site_id"`
	Client  string   `json:"client"`
	States  []string `json:"states"`
	AfterID string   `json:"after_id"`
	MaxRows int32    `json:"max_rows"`
}

type AnalyticsHeatmapIdentitiesRow struct {
	ID          string     `json:"id"`
	Hkey        int64      `json:"hkey"`
	State       string     `json:"state"`
	Region      string     `json:"region"`
	BanUntil    *time.Time `json:"ban_until"`
	AccountRef  string     `json:"account_ref"`
	AccountHkey int64      `json:"account_hkey"`
}

// AnalyticsHeatmapIdentities pages the identities of a site client (keyset on id).
func (q *Queries) AnalyticsHeatmapIdentities(ctx context.Context, arg AnalyticsHeatmapIdentitiesParams) ([]AnalyticsHeatmapIdentitiesRow, error) {
	rows, err := q.db.Query(ctx, analyticsHeatmapIdentities,
		arg.SiteID,
		arg.Client,
		arg.States,
		arg.AfterID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsHeatmapIdentitiesRow{}
	for rows.Next() {
		var i AnalyticsHeatmapIdentitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Hkey,
			&i.State,
			&i.Region,
			&i.BanUntil,
			&i.AccountRef,
			&i.AccountHkey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsHeatmapIdentityCount = `-- name: AnalyticsHeatmapIdentityCount :one
SELECT count(*)::bigint AS count
FROM identities
WHERE site_id = $1
  AND client = $2
  AND state = ANY($3::text[])
`

type AnalyticsHeatmapIdentityCountParams struct {
	SiteID string   `json:"site_id"`
	Client string   `json:"client"`
	States []string `json:"states"`
}

// AnalyticsHeatmapIdentityCount counts the identities matched by AnalyticsHeatmapIdentities.
func (q *Queries) AnalyticsHeatmapIdentityCount(ctx context.Context, arg AnalyticsHeatmapIdentityCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, analyticsHeatmapIdentityCount, arg.SiteID, arg.Client, arg.States)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const analyticsIdentityStateCounts = `-- name: AnalyticsIdentityStateCounts :many

SELECT site_id, state, count(*)::bigint AS count
FROM identities
WHERE site_id = ANY($1::text[])
GROUP BY site_id, state
`

type AnalyticsIdentityStateCountsRow struct {
	SiteID string `json:"site_id"`
	State  string `json:"state"`
	Count  int64  `json:"count"`
}

// Dashboard read queries (analytics track). Every query is read-only.
// AnalyticsIdentityStateCounts counts identities per site and lifecycle state.
func (q *Queries) AnalyticsIdentityStateCounts(ctx context.Context, siteIds []string) ([]AnalyticsIdentityStateCountsRow, error) {
	rows, err := q.db.Query(ctx, analyticsIdentityStateCounts, siteIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsIdentityStateCountsRow{}
	for rows.Next() {
		var i AnalyticsIdentityStateCountsRow
		if err := rows.Scan(&i.SiteID, &i.State, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsNodeStats = `-- name: AnalyticsNodeStats :many
SELECT node,
       sum(acquires)::bigint AS acquires,
       sum(reports)::bigint AS reports,
       sum(abandoned)::bigint AS abandoned,
       sum(rejected)::bigint AS rejected
FROM node_stats_minutely
WHERE namespace_id = $1
  AND bucket >= $2
  AND bucket < $3
GROUP BY node
ORDER BY acquires DESC, node
LIMIT $4
`

type AnalyticsNodeStatsParams struct {
	NamespaceID string    `json:"namespace_id"`
	FromBucket  time.Time `json:"from_bucket"`
	ToBucket    time.Time `json:"to_bucket"`
	MaxRows     int32     `json:"max_rows"`
}

type AnalyticsNodeStatsRow struct {
	Node      string `json:"node"`
	Acquires  int64  `json:"acquires"`
	Reports   int64  `json:"reports"`
	Abandoned int64  `json:"abandoned"`
	Rejected  int64  `json:"rejected"`
}

// AnalyticsNodeStats sums node counters over a bucket range, busiest nodes first.
func (q *Queries) AnalyticsNodeStats(ctx context.Context, arg AnalyticsNodeStatsParams) ([]AnalyticsNodeStatsRow, error) {
	rows, err := q.db.Query(ctx, analyticsNodeStats,
		arg.NamespaceID,
		arg.FromBucket,
		arg.ToBucket,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsNodeStatsRow{}
	for rows.Next() {
		var i AnalyticsNodeStatsRow
		if err := rows.Scan(
			&i.Node,
			&i.Acquires,
			&i.Reports,
			&i.Abandoned,
			&i.Rejected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsOutcomeSeries = `-- name: AnalyticsOutcomeSeries :many
SELECT date_bin(make_interval(secs => $1::double precision), bucket, 'epoch'::timestamptz)::timestamptz AS ts,
       outcome,
       sum(count)::bigint AS count,
       sum(latency_ms_sum)::bigint AS latency_ms_sum
FROM outcome_stats_minutely
WHERE namespace_id = $2
  AND bucket >= $3
  AND bucket < $4
  AND ($5::boolean OR site_id = ANY($6::text[]))
  AND (cardinality($7::text[]) = 0 OR endpoint_group_id = ANY($7::text[]))
GROUP BY 1, 2
ORDER BY 1, 2
`

type AnalyticsOutcomeSeriesParams struct {
	StepSeconds      float64   `json:"step_seconds"`
	NamespaceID      string    `json:"namespace_id"`
	FromBucket       time.Time `json:"from_bucket"`
	ToBucket         time.Time `json:"to_bucket"`
	AllSites         bool      `json:"all_sites"`
	SiteIds          []string  `json:"site_ids"`
	EndpointGroupIds []string  `json:"endpoint_group_ids"`
}

type AnalyticsOutcomeSeriesRow struct {
	Ts           time.Time `json:"ts"`
	Outcome      string    `json:"outcome"`
	Count        int64     `json:"count"`
	LatencyMsSum int64     `json:"latency_ms_sum"`
}

// AnalyticsOutcomeSeries buckets report outcomes (count and latency sum) by a
// fixed step aligned to the Unix epoch, with the filters of AnalyticsAcquireSeries.
func (q *Queries) AnalyticsOutcomeSeries(ctx context.Context, arg AnalyticsOutcomeSeriesParams) ([]AnalyticsOutcomeSeriesRow, error) {
	rows, err := q.db.Query(ctx, analyticsOutcomeSeries,
		arg.StepSeconds,
		arg.NamespaceID,
		arg.FromBucket,
		arg.ToBucket,
		arg.AllSites,
		arg.SiteIds,
		arg.EndpointGroupIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsOutcomeSeriesRow{}
	for rows.Next() {
		var i AnalyticsOutcomeSeriesRow
		if err := rows.Scan(
			&i.Ts,
			&i.Outcome,
			&i.Count,
			&i.LatencyMsSum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsOutcomeTotalsBySite = `-- name: AnalyticsOutcomeTotalsBySite :many
SELECT site_id, outcome, sum(count)::bigint AS count
FROM outcome_stats_minutely
WHERE namespace_id = $1
  AND bucket >= $2
  AND bucket < $3
  AND site_id = ANY($4::text[])
GROUP BY site_id, outcome
`

type AnalyticsOutcomeTotalsBySiteParams struct {
	NamespaceID string    `json:"namespace_id"`
	FromBucket  time.Time `json:"from_bucket"`
	ToBucket    time.Time `json:"to_bucket"`
	SiteIds     []string  `json:"site_ids"`
}

type AnalyticsOutcomeTotalsBySiteRow struct {
	SiteID  string `json:"site_id"`
	Outcome string `json:"outcome"`
	Count   int64  `json:"count"`
}

// AnalyticsOutcomeTotalsBySite sums report outcomes per site over a bucket range.
func (q *Queries) AnalyticsOutcomeTotalsBySite(ctx context.Context, arg AnalyticsOutcomeTotalsBySiteParams) ([]AnalyticsOutcomeTotalsBySiteRow, error) {
	rows, err := q.db.Query(ctx, analyticsOutcomeTotalsBySite,
		arg.NamespaceID,
		arg.FromBucket,
		arg.ToBucket,
		arg.SiteIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsOutcomeTotalsBySiteRow{}
	for rows.Next() {
		var i AnalyticsOutcomeTotalsBySiteRow
		if err := rows.Scan(&i.SiteID, &i.Outcome, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsProxyStateCounts = `-- name: AnalyticsProxyStateCounts :many
SELECT state, count(*)::bigint AS count
FROM proxies
WHERE namespace_id = $1
GROUP BY state
`

type AnalyticsProxyStateCountsRow struct {
	State string `json:"state"`
	Count int64  `json:"count"`
}

// AnalyticsProxyStateCounts counts the proxies of a namespace per state.
func (q *Queries) AnalyticsProxyStateCounts(ctx context.Context, namespaceID string) ([]AnalyticsProxyStateCountsRow, error) {
	rows, err := q.db.Query(ctx, analyticsProxyStateCounts, namespaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsProxyStateCountsRow{}
	for rows.Next() {
		var i AnalyticsProxyStateCountsRow
		if err := rows.Scan(&i.State, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsRiskEvents = `-- name: AnalyticsRiskEvents :many
SELECT e.id,
       e.created_at,
       e.site_id,
       e.endpoint_group_id,
       e.identity_id,
       e.proxy_id,
       e.lease_id,
       e.report_id,
       e.node,
       e.token_id,
       e.uri,
       e.method,
       e.http_status,
       e.business_code,
       e.error_kind,
       e.markers,
       e.outcome,
       e.blame,
       e.rule,
       e.latency_ms,
       e.response_bytes,
       e.started_at,
       e.finished_at
FROM unnest($1::text[]) AS s (site_id)
CROSS JOIN LATERAL (
    SELECT r.id, r.created_at, r.site_id, r.endpoint_group_id, r.identity_id, r.proxy_id, r.lease_id, r.report_id,
           r.node, r.token_id, r.uri, r.method, r.http_status, r.business_code, r.error_kind, r.markers, r.outcome,
           r.blame, r.rule, r.latency_ms, r.response_bytes, r.started_at, r.finished_at
    FROM risk_events r
    WHERE r.namespace_id = $2
      AND r.site_id = s.site_id
      AND r.created_at >= $3
      AND r.created_at <= $4
      AND (r.created_at < $4 OR r.id < $5::text)
      AND ($6::text = '' OR r.endpoint_group_id = $6::text)
      AND ($7::text = '' OR r.outcome = $7::text)
      AND ($8::text = '' OR r.identity_id = $8::text)
      AND ($9::text = '' OR r.proxy_id = $9::text)
      AND ($10::text = '' OR r.node = $10::text)
    ORDER BY r.created_at DESC, r.id DESC
    LIMIT $11
) e
ORDER BY e.created_at DESC, e.id DESC
LIMIT $11
`

type AnalyticsRiskEventsParams struct {
	SiteIds         []string  `json:"site_ids"`
	NamespaceID     string    `json:"namespace_id"`
	FromAt          time.Time `json:"from_at"`
	BeforeAt        time.Time `json:"before_at"`
	BeforeID        string    `json:"before_id"`
	EndpointGroupID string    `json:"endpoint_group_id"`
	Outcome         string    `json:"outcome"`
	IdentityID      string    `json:"identity_id"`
	ProxyID         string    `json:"proxy_id"`
	Node            string    `json:"node"`
	MaxRows         int32     `json:"max_rows"`
}

type AnalyticsRiskEventsRow struct {
	ID              string     `json:"id"`
	CreatedAt       time.Time  `json:"created_at"`
	SiteID          string     `json:"site_id"`
	EndpointGroupID string     `json:"endpoint_group_id"`
	IdentityID      string     `json:"identity_id"`
	ProxyID         string     `json:"proxy_id"`
	LeaseID         string     `json:"lease_id"`
	ReportID        string     `json:"report_id"`
	Node            string     `json:"node"`
	TokenID         string     `json:"token_id"`
	Uri             string     `json:"uri"`
	Method          string     `json:"method"`
	HttpStatus      int32      `json:"http_status"`
	BusinessCode    string     `json:"business_code"`
	ErrorKind       string     `json:"error_kind"`
	Markers         []string   `json:"markers"`
	Outcome         string     `json:"outcome"`
	Blame           string     `json:"blame"`
	Rule            string     `json:"rule"`
	LatencyMs       int32      `json:"latency_ms"`
	ResponseBytes   int64      `json:"response_bytes"`
	StartedAt       *time.Time `json:"started_at"`
	FinishedAt      *time.Time `json:"finished_at"`
}

// AnalyticsRiskEvents pages risk events newest first over a set of sites. The
// page of every site is read through the (namespace_id, site_id, created_at)
// index and the pages are merged. The keyset cursor is (before_at, before_id):
// rows strictly before it in (created_at DESC, id DESC) order are returned;
// without a cursor before_at is the exclusive range end and before_id is the
// empty string. Empty string filters are disabled.
func (q *Queries) AnalyticsRiskEvents(ctx context.Context, arg AnalyticsRiskEventsParams) ([]AnalyticsRiskEventsRow, error) {
	rows, err := q.db.Query(ctx, analyticsRiskEvents,
		arg.SiteIds,
		arg.NamespaceID,
		arg.FromAt,
		arg.BeforeAt,
		arg.BeforeID,
		arg.EndpointGroupID,
		arg.Outcome,
		arg.IdentityID,
		arg.ProxyID,
		arg.Node,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsRiskEventsRow{}
	for rows.Next() {
		var i AnalyticsRiskEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.SiteID,
			&i.EndpointGroupID,
			&i.IdentityID,
			&i.ProxyID,
			&i.LeaseID,
			&i.ReportID,
			&i.Node,
			&i.TokenID,
			&i.Uri,
			&i.Method,
			&i.HttpStatus,
			&i.BusinessCode,
			&i.ErrorKind,
			&i.Markers,
			&i.Outcome,
			&i.Blame,
			&i.Rule,
			&i.LatencyMs,
			&i.ResponseBytes,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
