// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenancy.sql

package tenancydb

import (
	"context"
)

const tenancyNamespaceDelete = `-- name: TenancyNamespaceDelete :execrows
DELETE FROM namespaces
WHERE id = $1
`

func (q *Queries) TenancyNamespaceDelete(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, tenancyNamespaceDelete, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const tenancyNamespaceGet = `-- name: TenancyNamespaceGet :one
SELECT id, tenant_id, name, display_name, description, created_at, updated_at
FROM namespaces
WHERE id = $1
`

func (q *Queries) TenancyNamespaceGet(ctx context.Context, id string) (Namespace, error) {
	row := q.db.QueryRow(ctx, tenancyNamespaceGet, id)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const tenancyNamespaceInsert = `-- name: TenancyNamespaceInsert :one
INSERT INTO namespaces (id, tenant_id, name, display_name, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, name, display_name, description, created_at, updated_at
`

type TenancyNamespaceInsertParams struct {
	ID          string `json:"id"`
	TenantID    string `json:"tenant_id"`
	Name        string `json:"name"`
	DisplayName string `json:"display_name"`
	Description string `json:"description"`
}

func (q *Queries) TenancyNamespaceInsert(ctx context.Context, arg TenancyNamespaceInsertParams) (Namespace, error) {
	row := q.db.QueryRow(ctx, tenancyNamespaceInsert,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.DisplayName,
		arg.Description,
	)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const tenancyNamespaceLock = `-- name: TenancyNamespaceLock :one
SELECT id, tenant_id, name, display_name, description, created_at, updated_at
FROM namespaces
WHERE id = $1
FOR UPDATE
`

func (q *Queries) TenancyNamespaceLock(ctx context.Context, id string) (Namespace, error) {
	row := q.db.QueryRow(ctx, tenancyNamespaceLock, id)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const tenancyNamespaceUpdate = `-- name: TenancyNamespaceUpdate :one
UPDATE namespaces
SET display_name = coalesce($1::text, display_name),
    description = coalesce($2::text, description),
    updated_at = now()
WHERE id = $3
RETURNING id, tenant_id, name, display_name, description, created_at, updated_at
`

type TenancyNamespaceUpdateParams struct {
	DisplayName *string `json:"display_name"`
	Description *string `json:"description"`
	ID          string  `json:"id"`
}

func (q *Queries) TenancyNamespaceUpdate(ctx context.Context, arg TenancyNamespaceUpdateParams) (Namespace, error) {
	row := q.db.QueryRow(ctx, tenancyNamespaceUpdate, arg.DisplayName, arg.Description, arg.ID)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const tenancyNamespaceUsage = `-- name: TenancyNamespaceUsage :one
SELECT (SELECT count(*) FROM sites s WHERE s.namespace_id = $1::text)::integer AS sites,
       (SELECT count(*) FROM proxies p WHERE p.namespace_id = $1::text)::integer AS proxies,
       (SELECT count(*) FROM config_items c WHERE c.namespace_id = $1::text)::integer AS config_items,
       (SELECT count(*) FROM secrets x WHERE x.namespace_id = $1::text)::integer AS secrets,
       -- Revoked and expired tokens can never authenticate again and are deleted with the namespace (there is
       -- no API to delete them), so only usable tokens block the deletion.
       (SELECT count(*) FROM api_tokens t
        WHERE t.namespace_id = $1::text
          AND t.revoked_at IS NULL
          AND (t.expires_at IS NULL OR t.expires_at > now()))::integer AS tokens
`

type TenancyNamespaceUsageRow struct {
	Sites       int32 `json:"sites"`
	Proxies     int32 `json:"proxies"`
	ConfigItems int32 `json:"config_items"`
	Secrets     int32 `json:"secrets"`
	Tokens      int32 `json:"tokens"`
}

func (q *Queries) TenancyNamespaceUsage(ctx context.Context, namespaceID string) (TenancyNamespaceUsageRow, error) {
	row := q.db.QueryRow(ctx, tenancyNamespaceUsage, namespaceID)
	var i TenancyNamespaceUsageRow
	err := row.Scan(
		&i.Sites,
		&i.Proxies,
		&i.ConfigItems,
		&i.Secrets,
		&i.Tokens,
	)
	return i, err
}

const tenancyNamespacesOfTenant = `-- name: TenancyNamespacesOfTenant :many
SELECT id, tenant_id, name, display_name, description, created_at, updated_at
FROM namespaces
WHERE tenant_id = $1
ORDER BY name
LIMIT $2
`

type TenancyNamespacesOfTenantParams struct {
	TenantID  string `json:"tenant_id"`
	PageLimit int32  `json:"page_limit"`
}

func (q *Queries) TenancyNamespacesOfTenant(ctx context.Context, arg TenancyNamespacesOfTenantParams) ([]Namespace, error) {
	rows, err := q.db.Query(ctx, tenancyNamespacesOfTenant, arg.TenantID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Namespace{}
	for rows.Next() {
		var i Namespace
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tenancyOwnerBindingInsert = `-- name: TenancyOwnerBindingInsert :exec
INSERT INTO role_bindings (id, user_id, tenant_id, role, created_by)
VALUES ($1, $2, $3, 'owner', $4)
`

type TenancyOwnerBindingInsertParams struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	TenantID  string `json:"tenant_id"`
	CreatedBy string `json:"created_by"`
}

func (q *Queries) TenancyOwnerBindingInsert(ctx context.Context, arg TenancyOwnerBindingInsertParams) error {
	_, err := q.db.Exec(ctx, tenancyOwnerBindingInsert,
		arg.ID,
		arg.UserID,
		arg.TenantID,
		arg.CreatedBy,
	)
	return err
}

const tenancyTenantCount = `-- name: TenancyTenantCount :one
SELECT count(*)::integer AS total
FROM tenants
WHERE ($1::boolean OR id = ANY($2::text[]))
`

type TenancyTenantCountParams struct {
	AllTenants bool     `json:"all_tenants"`
	Ids        []string `json:"ids"`
}

func (q *Queries) TenancyTenantCount(ctx context.Context, arg TenancyTenantCountParams) (int32, error) {
	row := q.db.QueryRow(ctx, tenancyTenantCount, arg.AllTenants, arg.Ids)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const tenancyTenantDelete = `-- name: TenancyTenantDelete :execrows
DELETE FROM tenants
WHERE id = $1
`

func (q *Queries) TenancyTenantDelete(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, tenancyTenantDelete, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const tenancyTenantGet = `-- name: TenancyTenantGet :one
SELECT id, name, display_name, description, created_at, updated_at
FROM tenants
WHERE id = $1
`

func (q *Queries) TenancyTenantGet(ctx context.Context, id string) (Tenant, error) {
	row := q.db.QueryRow(ctx, tenancyTenantGet, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const tenancyTenantInsert = `-- name: TenancyTenantInsert :one
INSERT INTO tenants (id, name, display_name, description)
VALUES ($1, $2, $3, $4)
RETURNING id, name, display_name, description, created_at, updated_at
`

type TenancyTenantInsertParams struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	DisplayName string `json:"display_name"`
	Description string `json:"description"`
}

func (q *Queries) TenancyTenantInsert(ctx context.Context, arg TenancyTenantInsertParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, tenancyTenantInsert,
		arg.ID,
		arg.Name,
		arg.DisplayName,
		arg.Description,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const tenancyTenantList = `-- name: TenancyTenantList :many

SELECT id, name, display_name, description, created_at, updated_at
FROM tenants
WHERE ($1::boolean OR id = ANY($2::text[]))
  AND name > $3::text
ORDER BY name
LIMIT $4
`

type TenancyTenantListParams struct {
	AllTenants bool     `json:"all_tenants"`
	Ids        []string `json:"ids"`
	AfterName  string   `json:"after_name"`
	PageLimit  int32    `json:"page_limit"`
}

// Tenant and namespace queries of the tenancy service.
func (q *Queries) TenancyTenantList(ctx context.Context, arg TenancyTenantListParams) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, tenancyTenantList,
		arg.AllTenants,
		arg.Ids,
		arg.AfterName,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tenancyTenantLock = `-- name: TenancyTenantLock :one
SELECT id, name, display_name, description, created_at, updated_at
FROM tenants
WHERE id = $1
FOR UPDATE
`

func (q *Queries) TenancyTenantLock(ctx context.Context, id string) (Tenant, error) {
	row := q.db.QueryRow(ctx, tenancyTenantLock, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const tenancyTenantNamespaceCount = `-- name: TenancyTenantNamespaceCount :one
SELECT count(*)::integer AS total
FROM namespaces
WHERE tenant_id = $1
`

func (q *Queries) TenancyTenantNamespaceCount(ctx context.Context, tenantID string) (int32, error) {
	row := q.db.QueryRow(ctx, tenancyTenantNamespaceCount, tenantID)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const tenancyTenantUpdate = `-- name: TenancyTenantUpdate :one
UPDATE tenants
SET display_name = coalesce($1::text, display_name),
    description = coalesce($2::text, description),
    updated_at = now()
WHERE id = $3
RETURNING id, name, display_name, description, created_at, updated_at
`

type TenancyTenantUpdateParams struct {
	DisplayName *string `json:"display_name"`
	Description *string `json:"description"`
	ID          string  `json:"id"`
}

func (q *Queries) TenancyTenantUpdate(ctx context.Context, arg TenancyTenantUpdateParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, tenancyTenantUpdate, arg.DisplayName, arg.Description, arg.ID)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const tenancyUserExists = `-- name: TenancyUserExists :one
SELECT EXISTS (SELECT 1 FROM users WHERE id = $1) AS present
`

func (q *Queries) TenancyUserExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, tenancyUserExists, id)
	var present bool
	err := row.Scan(&present)
	return present, err
}
