// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	GetSystemKey(ctx context.Context, name string) (SystemKey, error)
	GetSystemSetting(ctx context.Context, key string) (SystemSetting, error)
	// InsertSystemKeyIfAbsent returns pgx.ErrNoRows when a key with the same name
	// already exists; callers then load the existing key with GetSystemKey.
	InsertSystemKeyIfAbsent(ctx context.Context, arg InsertSystemKeyIfAbsentParams) (SystemKey, error)
	ListSystemKeysByKEK(ctx context.Context, kekID string) ([]SystemKey, error)
	ListSystemKeysNotOnKEK(ctx context.Context, kekID string) ([]SystemKey, error)
	// Ping is a trivial round trip used by readiness checks.
	Ping(ctx context.Context) (int32, error)
	// UpdateSystemKeyWrap replaces the wrapped DEK of a key only while it is still
	// wrapped by old_kek_id (compare-and-swap), so concurrent rewraps cannot
	// overwrite each other. It returns the number of updated rows (0 or 1).
	UpdateSystemKeyWrap(ctx context.Context, arg UpdateSystemKeyWrapParams) (int64, error)
	UpsertSystemSetting(ctx context.Context, arg UpsertSystemSettingParams) (SystemSetting, error)
}

var _ Querier = (*Queries)(nil)
