// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system.sql

package db

import (
	"context"
	"encoding/json"
)

const getSystemKey = `-- name: GetSystemKey :one
SELECT name, ciphertext, wrapped_dek, kek_id, created_at, updated_at
FROM system_keys
WHERE name = $1
`

func (q *Queries) GetSystemKey(ctx context.Context, name string) (SystemKey, error) {
	row := q.db.QueryRow(ctx, getSystemKey, name)
	var i SystemKey
	err := row.Scan(
		&i.Name,
		&i.Ciphertext,
		&i.WrappedDek,
		&i.KekID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSystemSetting = `-- name: GetSystemSetting :one
SELECT key, value, updated_at
FROM system_settings
WHERE key = $1
`

func (q *Queries) GetSystemSetting(ctx context.Context, key string) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, getSystemSetting, key)
	var i SystemSetting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const insertSystemKeyIfAbsent = `-- name: InsertSystemKeyIfAbsent :one
INSERT INTO system_keys (name, ciphertext, wrapped_dek, kek_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (name) DO NOTHING
RETURNING name, ciphertext, wrapped_dek, kek_id, created_at, updated_at
`

type InsertSystemKeyIfAbsentParams struct {
	Name       string `json:"name"`
	Ciphertext []byte `json:"ciphertext"`
	WrappedDek []byte `json:"wrapped_dek"`
	KekID      string `json:"kek_id"`
}

// InsertSystemKeyIfAbsent returns pgx.ErrNoRows when a key with the same name
// already exists; callers then load the existing key with GetSystemKey.
func (q *Queries) InsertSystemKeyIfAbsent(ctx context.Context, arg InsertSystemKeyIfAbsentParams) (SystemKey, error) {
	row := q.db.QueryRow(ctx, insertSystemKeyIfAbsent,
		arg.Name,
		arg.Ciphertext,
		arg.WrappedDek,
		arg.KekID,
	)
	var i SystemKey
	err := row.Scan(
		&i.Name,
		&i.Ciphertext,
		&i.WrappedDek,
		&i.KekID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSystemKeysByKEK = `-- name: ListSystemKeysByKEK :many
SELECT name, ciphertext, wrapped_dek, kek_id, created_at, updated_at
FROM system_keys
WHERE kek_id = $1
ORDER BY name
`

func (q *Queries) ListSystemKeysByKEK(ctx context.Context, kekID string) ([]SystemKey, error) {
	rows, err := q.db.Query(ctx, listSystemKeysByKEK, kekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemKey{}
	for rows.Next() {
		var i SystemKey
		if err := rows.Scan(
			&i.Name,
			&i.Ciphertext,
			&i.WrappedDek,
			&i.KekID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemKeysNotOnKEK = `-- name: ListSystemKeysNotOnKEK :many
SELECT name, ciphertext, wrapped_dek, kek_id, created_at, updated_at
FROM system_keys
WHERE kek_id <> $1
ORDER BY name
`

func (q *Queries) ListSystemKeysNotOnKEK(ctx context.Context, kekID string) ([]SystemKey, error) {
	rows, err := q.db.Query(ctx, listSystemKeysNotOnKEK, kekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemKey{}
	for rows.Next() {
		var i SystemKey
		if err := rows.Scan(
			&i.Name,
			&i.Ciphertext,
			&i.WrappedDek,
			&i.KekID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ping = `-- name: Ping :one
SELECT 1::integer AS ok
`

// Ping is a trivial round trip used by readiness checks.
func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}

const updateSystemKeyWrap = `-- name: UpdateSystemKeyWrap :execrows
UPDATE system_keys
SET wrapped_dek = $1,
    kek_id = $2,
    updated_at = now()
WHERE name = $3
  AND kek_id = $4
`

type UpdateSystemKeyWrapParams struct {
	WrappedDek []byte `json:"wrapped_dek"`
	KekID      string `json:"kek_id"`
	Name       string `json:"name"`
	OldKekID   string `json:"old_kek_id"`
}

// UpdateSystemKeyWrap replaces the wrapped DEK of a key only while it is still
// wrapped by old_kek_id (compare-and-swap), so concurrent rewraps cannot
// overwrite each other. It returns the number of updated rows (0 or 1).
func (q *Queries) UpdateSystemKeyWrap(ctx context.Context, arg UpdateSystemKeyWrapParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSystemKeyWrap,
		arg.WrappedDek,
		arg.KekID,
		arg.Name,
		arg.OldKekID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertSystemSetting = `-- name: UpsertSystemSetting :one
INSERT INTO system_settings (key, value, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value,
    updated_at = EXCLUDED.updated_at
RETURNING key, value, updated_at
`

type UpsertSystemSettingParams struct {
	Key   string          `json:"key"`
	Value json.RawMessage `json:"value"`
}

func (q *Queries) UpsertSystemSetting(ctx context.Context, arg UpsertSystemSettingParams) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, upsertSystemSetting, arg.Key, arg.Value)
	var i SystemSetting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}
