// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: config.sql

package configdb

import (
	"context"
	"encoding/json"
	"time"
)

const configCountItems = `-- name: ConfigCountItems :one
SELECT count(*)
FROM config_items i
WHERE i.namespace_id = $1
  AND ($2::text IS NULL OR i.group_name = $2::text)
  AND ($3::text[] IS NULL OR i.group_name = ANY ($3::text[]))
  AND ($4::text IS NULL
       OR i.key ILIKE $4::text ESCAPE '\'
       OR i.description ILIKE $4::text ESCAPE '\')
`

type ConfigCountItemsParams struct {
	NamespaceID   string   `json:"namespace_id"`
	GroupName     *string  `json:"group_name"`
	AllowedGroups []string `json:"allowed_groups"`
	Search        *string  `json:"search"`
}

func (q *Queries) ConfigCountItems(ctx context.Context, arg ConfigCountItemsParams) (int64, error) {
	row := q.db.QueryRow(ctx, configCountItems,
		arg.NamespaceID,
		arg.GroupName,
		arg.AllowedGroups,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const configCountVersions = `-- name: ConfigCountVersions :one
SELECT count(*)
FROM config_versions
WHERE item_id = $1
`

func (q *Queries) ConfigCountVersions(ctx context.Context, itemID string) (int64, error) {
	row := q.db.QueryRow(ctx, configCountVersions, itemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const configCurrentVersions = `-- name: ConfigCurrentVersions :many
SELECT i.group_name, i.key, i.id, i.current_version
FROM config_items i
JOIN (SELECT unnest($1::text[]) AS group_name, unnest($2::text[]) AS item_key) AS r
  ON i.group_name = r.group_name AND i.key = r.item_key
WHERE i.namespace_id = $3
`

type ConfigCurrentVersionsParams struct {
	GroupNames  []string `json:"group_names"`
	ItemKeys    []string `json:"item_keys"`
	NamespaceID string   `json:"namespace_id"`
}

type ConfigCurrentVersionsRow struct {
	GroupName      string `json:"group_name"`
	Key            string `json:"key"`
	ID             string `json:"id"`
	CurrentVersion int32  `json:"current_version"`
}

func (q *Queries) ConfigCurrentVersions(ctx context.Context, arg ConfigCurrentVersionsParams) ([]ConfigCurrentVersionsRow, error) {
	rows, err := q.db.Query(ctx, configCurrentVersions, arg.GroupNames, arg.ItemKeys, arg.NamespaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigCurrentVersionsRow{}
	for rows.Next() {
		var i ConfigCurrentVersionsRow
		if err := rows.Scan(
			&i.GroupName,
			&i.Key,
			&i.ID,
			&i.CurrentVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const configDeleteItem = `-- name: ConfigDeleteItem :execrows
DELETE FROM config_items
WHERE id = $1
`

func (q *Queries) ConfigDeleteItem(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, configDeleteItem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const configExistingSecretPaths = `-- name: ConfigExistingSecretPaths :many
SELECT path
FROM secrets
WHERE namespace_id = $1 AND path = ANY ($2::text[])
`

type ConfigExistingSecretPathsParams struct {
	NamespaceID string   `json:"namespace_id"`
	Paths       []string `json:"paths"`
}

func (q *Queries) ConfigExistingSecretPaths(ctx context.Context, arg ConfigExistingSecretPathsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, configExistingSecretPaths, arg.NamespaceID, arg.Paths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const configExistingSecretVersions = `-- name: ConfigExistingSecretVersions :many
SELECT s.path, sv.version
FROM secrets s
JOIN secret_versions sv ON sv.secret_id = s.id
JOIN (SELECT unnest($1::text[]) AS path, unnest($2::integer[]) AS version) AS r
  ON s.path = r.path AND sv.version = r.version
WHERE s.namespace_id = $3
`

type ConfigExistingSecretVersionsParams struct {
	Paths       []string `json:"paths"`
	Versions    []int32  `json:"versions"`
	NamespaceID string   `json:"namespace_id"`
}

type ConfigExistingSecretVersionsRow struct {
	Path    string `json:"path"`
	Version int32  `json:"version"`
}

func (q *Queries) ConfigExistingSecretVersions(ctx context.Context, arg ConfigExistingSecretVersionsParams) ([]ConfigExistingSecretVersionsRow, error) {
	rows, err := q.db.Query(ctx, configExistingSecretVersions, arg.Paths, arg.Versions, arg.NamespaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigExistingSecretVersionsRow{}
	for rows.Next() {
		var i ConfigExistingSecretVersionsRow
		if err := rows.Scan(&i.Path, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const configGetItemHeader = `-- name: ConfigGetItemHeader :one
SELECT id, namespace_id, group_name, key, format
FROM config_items
WHERE id = $1
`

type ConfigGetItemHeaderRow struct {
	ID          string `json:"id"`
	NamespaceID string `json:"namespace_id"`
	GroupName   string `json:"group_name"`
	Key         string `json:"key"`
	Format      string `json:"format"`
}

func (q *Queries) ConfigGetItemHeader(ctx context.Context, id string) (ConfigGetItemHeaderRow, error) {
	row := q.db.QueryRow(ctx, configGetItemHeader, id)
	var i ConfigGetItemHeaderRow
	err := row.Scan(
		&i.ID,
		&i.NamespaceID,
		&i.GroupName,
		&i.Key,
		&i.Format,
	)
	return i, err
}

const configGetItemIDByLocator = `-- name: ConfigGetItemIDByLocator :one
SELECT id
FROM config_items
WHERE namespace_id = $1 AND group_name = $2 AND key = $3
`

type ConfigGetItemIDByLocatorParams struct {
	NamespaceID string `json:"namespace_id"`
	GroupName   string `json:"group_name"`
	Key         string `json:"key"`
}

func (q *Queries) ConfigGetItemIDByLocator(ctx context.Context, arg ConfigGetItemIDByLocatorParams) (string, error) {
	row := q.db.QueryRow(ctx, configGetItemIDByLocator, arg.NamespaceID, arg.GroupName, arg.Key)
	var id string
	err := row.Scan(&id)
	return id, err
}

const configGetItemView = `-- name: ConfigGetItemView :one
SELECT i.id, i.namespace_id, i.group_name, i.key, i.format, i.schema, i.description, i.current_version,
       i.draft_content, i.draft_updated_by, i.draft_updated_at, i.created_by, i.created_at, i.updated_at,
       v.content AS published_content, v.published_by, v.published_at
FROM config_items i
LEFT JOIN config_versions v ON v.item_id = i.id AND v.version = i.current_version
WHERE i.id = $1
`

type ConfigGetItemViewRow struct {
	ID               string          `json:"id"`
	NamespaceID      string          `json:"namespace_id"`
	GroupName        string          `json:"group_name"`
	Key              string          `json:"key"`
	Format           string          `json:"format"`
	Schema           json.RawMessage `json:"schema"`
	Description      string          `json:"description"`
	CurrentVersion   int32           `json:"current_version"`
	DraftContent     *string         `json:"draft_content"`
	DraftUpdatedBy   *string         `json:"draft_updated_by"`
	DraftUpdatedAt   *time.Time      `json:"draft_updated_at"`
	CreatedBy        string          `json:"created_by"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
	PublishedContent *string         `json:"published_content"`
	PublishedBy      *string         `json:"published_by"`
	PublishedAt      *time.Time      `json:"published_at"`
}

func (q *Queries) ConfigGetItemView(ctx context.Context, id string) (ConfigGetItemViewRow, error) {
	row := q.db.QueryRow(ctx, configGetItemView, id)
	var i ConfigGetItemViewRow
	err := row.Scan(
		&i.ID,
		&i.NamespaceID,
		&i.GroupName,
		&i.Key,
		&i.Format,
		&i.Schema,
		&i.Description,
		&i.CurrentVersion,
		&i.DraftContent,
		&i.DraftUpdatedBy,
		&i.DraftUpdatedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedContent,
		&i.PublishedBy,
		&i.PublishedAt,
	)
	return i, err
}

const configGetVersion = `-- name: ConfigGetVersion :one
SELECT item_id, version, content, comment, source_version, published_by, published_at
FROM config_versions
WHERE item_id = $1 AND version = $2
`

type ConfigGetVersionParams struct {
	ItemID  string `json:"item_id"`
	Version int32  `json:"version"`
}

func (q *Queries) ConfigGetVersion(ctx context.Context, arg ConfigGetVersionParams) (ConfigVersion, error) {
	row := q.db.QueryRow(ctx, configGetVersion, arg.ItemID, arg.Version)
	var i ConfigVersion
	err := row.Scan(
		&i.ItemID,
		&i.Version,
		&i.Content,
		&i.Comment,
		&i.SourceVersion,
		&i.PublishedBy,
		&i.PublishedAt,
	)
	return i, err
}

const configInsertItem = `-- name: ConfigInsertItem :exec

INSERT INTO config_items (
    id, namespace_id, group_name, key, format, schema, description,
    draft_content, draft_updated_by, draft_updated_at, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11
)
`

type ConfigInsertItemParams struct {
	ID             string          `json:"id"`
	NamespaceID    string          `json:"namespace_id"`
	GroupName      string          `json:"group_name"`
	Key            string          `json:"key"`
	Format         string          `json:"format"`
	Schema         json.RawMessage `json:"schema"`
	Description    string          `json:"description"`
	DraftContent   *string         `json:"draft_content"`
	DraftUpdatedBy *string         `json:"draft_updated_by"`
	DraftUpdatedAt *time.Time      `json:"draft_updated_at"`
	CreatedBy      string          `json:"created_by"`
}

// Config center queries (private sqlc package configdb).
func (q *Queries) ConfigInsertItem(ctx context.Context, arg ConfigInsertItemParams) error {
	_, err := q.db.Exec(ctx, configInsertItem,
		arg.ID,
		arg.NamespaceID,
		arg.GroupName,
		arg.Key,
		arg.Format,
		arg.Schema,
		arg.Description,
		arg.DraftContent,
		arg.DraftUpdatedBy,
		arg.DraftUpdatedAt,
		arg.CreatedBy,
	)
	return err
}

const configInsertVersion = `-- name: ConfigInsertVersion :one
INSERT INTO config_versions (item_id, version, content, comment, source_version, published_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING published_at
`

type ConfigInsertVersionParams struct {
	ItemID        string `json:"item_id"`
	Version       int32  `json:"version"`
	Content       string `json:"content"`
	Comment       string `json:"comment"`
	SourceVersion *int32 `json:"source_version"`
	PublishedBy   string `json:"published_by"`
}

func (q *Queries) ConfigInsertVersion(ctx context.Context, arg ConfigInsertVersionParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, configInsertVersion,
		arg.ItemID,
		arg.Version,
		arg.Content,
		arg.Comment,
		arg.SourceVersion,
		arg.PublishedBy,
	)
	var published_at time.Time
	err := row.Scan(&published_at)
	return published_at, err
}

const configListGroups = `-- name: ConfigListGroups :many
SELECT DISTINCT group_name
FROM config_items
WHERE namespace_id = $1
ORDER BY group_name
LIMIT $2
`

type ConfigListGroupsParams struct {
	NamespaceID string `json:"namespace_id"`
	MaxGroups   int32  `json:"max_groups"`
}

func (q *Queries) ConfigListGroups(ctx context.Context, arg ConfigListGroupsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, configListGroups, arg.NamespaceID, arg.MaxGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var group_name string
		if err := rows.Scan(&group_name); err != nil {
			return nil, err
		}
		items = append(items, group_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const configListItems = `-- name: ConfigListItems :many
SELECT i.id, i.group_name, i.key, i.format, i.description, i.current_version,
       (i.draft_content IS NOT NULL)::boolean AS has_draft, i.draft_updated_by, i.draft_updated_at,
       i.created_at, i.updated_at, v.published_by, v.published_at
FROM config_items i
LEFT JOIN config_versions v ON v.item_id = i.id AND v.version = i.current_version
WHERE i.namespace_id = $1
  AND ($2::text IS NULL OR i.group_name = $2::text)
  AND ($3::text[] IS NULL OR i.group_name = ANY ($3::text[]))
  AND ($4::text IS NULL
       OR i.key ILIKE $4::text ESCAPE '\'
       OR i.description ILIKE $4::text ESCAPE '\')
  AND ($5::text IS NULL
       OR (i.group_name, i.key) > ($5::text, $6::text))
ORDER BY i.group_name, i.key
LIMIT $7
`

type ConfigListItemsParams struct {
	NamespaceID   string   `json:"namespace_id"`
	GroupName     *string  `json:"group_name"`
	AllowedGroups []string `json:"allowed_groups"`
	Search        *string  `json:"search"`
	AfterGroup    *string  `json:"after_group"`
	AfterKey      string   `json:"after_key"`
	PageLimit     int32    `json:"page_limit"`
}

type ConfigListItemsRow struct {
	ID             string     `json:"id"`
	GroupName      string     `json:"group_name"`
	Key            string     `json:"key"`
	Format         string     `json:"format"`
	Description    string     `json:"description"`
	CurrentVersion int32      `json:"current_version"`
	HasDraft       bool       `json:"has_draft"`
	DraftUpdatedBy *string    `json:"draft_updated_by"`
	DraftUpdatedAt *time.Time `json:"draft_updated_at"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	PublishedBy    *string    `json:"published_by"`
	PublishedAt    *time.Time `json:"published_at"`
}

func (q *Queries) ConfigListItems(ctx context.Context, arg ConfigListItemsParams) ([]ConfigListItemsRow, error) {
	rows, err := q.db.Query(ctx, configListItems,
		arg.NamespaceID,
		arg.GroupName,
		arg.AllowedGroups,
		arg.Search,
		arg.AfterGroup,
		arg.AfterKey,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigListItemsRow{}
	for rows.Next() {
		var i ConfigListItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupName,
			&i.Key,
			&i.Format,
			&i.Description,
			&i.CurrentVersion,
			&i.HasDraft,
			&i.DraftUpdatedBy,
			&i.DraftUpdatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedBy,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const configListVersions = `-- name: ConfigListVersions :many
SELECT item_id, version, comment, source_version, published_by, published_at,
       octet_length(content)::bigint AS content_bytes
FROM config_versions
WHERE item_id = $1
  AND ($2::integer = 0 OR version < $2::integer)
ORDER BY version DESC
LIMIT $3
`

type ConfigListVersionsParams struct {
	ItemID        string `json:"item_id"`
	BeforeVersion int32  `json:"before_version"`
	PageLimit     int32  `json:"page_limit"`
}

type ConfigListVersionsRow struct {
	ItemID        string    `json:"item_id"`
	Version       int32     `json:"version"`
	Comment       string    `json:"comment"`
	SourceVersion *int32    `json:"source_version"`
	PublishedBy   string    `json:"published_by"`
	PublishedAt   time.Time `json:"published_at"`
	ContentBytes  int64     `json:"content_bytes"`
}

func (q *Queries) ConfigListVersions(ctx context.Context, arg ConfigListVersionsParams) ([]ConfigListVersionsRow, error) {
	rows, err := q.db.Query(ctx, configListVersions, arg.ItemID, arg.BeforeVersion, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigListVersionsRow{}
	for rows.Next() {
		var i ConfigListVersionsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Version,
			&i.Comment,
			&i.SourceVersion,
			&i.PublishedBy,
			&i.PublishedAt,
			&i.ContentBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const configLockItem = `-- name: ConfigLockItem :one
SELECT id, namespace_id, group_name, key, format, schema, description, current_version,
       draft_content, draft_updated_by, draft_updated_at, created_by, created_at, updated_at
FROM config_items
WHERE id = $1
FOR UPDATE
`

func (q *Queries) ConfigLockItem(ctx context.Context, id string) (ConfigItem, error) {
	row := q.db.QueryRow(ctx, configLockItem, id)
	var i ConfigItem
	err := row.Scan(
		&i.ID,
		&i.NamespaceID,
		&i.GroupName,
		&i.Key,
		&i.Format,
		&i.Schema,
		&i.Description,
		&i.CurrentVersion,
		&i.DraftContent,
		&i.DraftUpdatedBy,
		&i.DraftUpdatedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const configRaiseVersionFloor = `-- name: ConfigRaiseVersionFloor :exec
INSERT INTO config_version_floors (namespace_id, group_name, key, last_version)
VALUES ($1, $2, $3, $4)
ON CONFLICT (namespace_id, group_name, key) DO UPDATE
SET last_version = GREATEST(config_version_floors.last_version, EXCLUDED.last_version),
    updated_at   = now()
`

type ConfigRaiseVersionFloorParams struct {
	NamespaceID string `json:"namespace_id"`
	GroupName   string `json:"group_name"`
	Key         string `json:"key"`
	LastVersion int32  `json:"last_version"`
}

// ConfigRaiseVersionFloor records the last version of an item that is being
// deleted; floors never decrease.
func (q *Queries) ConfigRaiseVersionFloor(ctx context.Context, arg ConfigRaiseVersionFloorParams) error {
	_, err := q.db.Exec(ctx, configRaiseVersionFloor,
		arg.NamespaceID,
		arg.GroupName,
		arg.Key,
		arg.LastVersion,
	)
	return err
}

const configSetCurrentVersion = `-- name: ConfigSetCurrentVersion :exec
UPDATE config_items
SET current_version  = $1,
    draft_content    = CASE WHEN $2::boolean THEN NULL ELSE draft_content END,
    draft_updated_by = CASE WHEN $2::boolean THEN NULL ELSE draft_updated_by END,
    draft_updated_at = CASE WHEN $2::boolean THEN NULL ELSE draft_updated_at END,
    updated_at       = now()
WHERE id = $3
`

type ConfigSetCurrentVersionParams struct {
	Version    int32  `json:"version"`
	ClearDraft bool   `json:"clear_draft"`
	ID         string `json:"id"`
}

func (q *Queries) ConfigSetCurrentVersion(ctx context.Context, arg ConfigSetCurrentVersionParams) error {
	_, err := q.db.Exec(ctx, configSetCurrentVersion, arg.Version, arg.ClearDraft, arg.ID)
	return err
}

const configUpdateDraft = `-- name: ConfigUpdateDraft :exec
UPDATE config_items
SET draft_content    = $1,
    draft_updated_by = $2,
    draft_updated_at = $3,
    schema           = $4,
    description      = $5,
    updated_at       = now()
WHERE id = $6
`

type ConfigUpdateDraftParams struct {
	DraftContent   *string         `json:"draft_content"`
	DraftUpdatedBy *string         `json:"draft_updated_by"`
	DraftUpdatedAt *time.Time      `json:"draft_updated_at"`
	Schema         json.RawMessage `json:"schema"`
	Description    string          `json:"description"`
	ID             string          `json:"id"`
}

func (q *Queries) ConfigUpdateDraft(ctx context.Context, arg ConfigUpdateDraftParams) error {
	_, err := q.db.Exec(ctx, configUpdateDraft,
		arg.DraftContent,
		arg.DraftUpdatedBy,
		arg.DraftUpdatedAt,
		arg.Schema,
		arg.Description,
		arg.ID,
	)
	return err
}

const configVersionContents = `-- name: ConfigVersionContents :many
SELECT v.item_id, v.version, i.format, v.content, v.published_at
FROM config_versions v
JOIN config_items i ON i.id = v.item_id
JOIN (SELECT unnest($1::text[]) AS item_id, unnest($2::integer[]) AS version) AS r
  ON v.item_id = r.item_id AND v.version = r.version
`

type ConfigVersionContentsParams struct {
	ItemIds  []string `json:"item_ids"`
	Versions []int32  `json:"versions"`
}

type ConfigVersionContentsRow struct {
	ItemID      string    `json:"item_id"`
	Version     int32     `json:"version"`
	Format      string    `json:"format"`
	Content     string    `json:"content"`
	PublishedAt time.Time `json:"published_at"`
}

func (q *Queries) ConfigVersionContents(ctx context.Context, arg ConfigVersionContentsParams) ([]ConfigVersionContentsRow, error) {
	rows, err := q.db.Query(ctx, configVersionContents, arg.ItemIds, arg.Versions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigVersionContentsRow{}
	for rows.Next() {
		var i ConfigVersionContentsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Version,
			&i.Format,
			&i.Content,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const configVersionFloor = `-- name: ConfigVersionFloor :one
SELECT coalesce(max(last_version), 0)::integer AS last_version
FROM config_version_floors
WHERE namespace_id = $1 AND group_name = $2 AND key = $3
`

type ConfigVersionFloorParams struct {
	NamespaceID string `json:"namespace_id"`
	GroupName   string `json:"group_name"`
	Key         string `json:"key"`
}

// ConfigVersionFloor returns the highest version ever published by a deleted
// item of the same namespace, group and key (0 when none).
func (q *Queries) ConfigVersionFloor(ctx context.Context, arg ConfigVersionFloorParams) (int32, error) {
	row := q.db.QueryRow(ctx, configVersionFloor, arg.NamespaceID, arg.GroupName, arg.Key)
	var last_version int32
	err := row.Scan(&last_version)
	return last_version, err
}

const configVersionSizes = `-- name: ConfigVersionSizes :many
SELECT v.item_id, v.version, octet_length(v.content)::bigint AS content_bytes
FROM config_versions v
JOIN (SELECT unnest($1::text[]) AS item_id, unnest($2::integer[]) AS version) AS r
  ON v.item_id = r.item_id AND v.version = r.version
`

type ConfigVersionSizesParams struct {
	ItemIds  []string `json:"item_ids"`
	Versions []int32  `json:"versions"`
}

type ConfigVersionSizesRow struct {
	ItemID       string `json:"item_id"`
	Version      int32  `json:"version"`
	ContentBytes int64  `json:"content_bytes"`
}

func (q *Queries) ConfigVersionSizes(ctx context.Context, arg ConfigVersionSizesParams) ([]ConfigVersionSizesRow, error) {
	rows, err := q.db.Query(ctx, configVersionSizes, arg.ItemIds, arg.Versions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigVersionSizesRow{}
	for rows.Next() {
		var i ConfigVersionSizesRow
		if err := rows.Scan(&i.ItemID, &i.Version, &i.ContentBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
