// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package authdb

import (
	"context"
	"time"
)

const authAuditList = `-- name: AuthAuditList :many

SELECT id, created_at, tenant_id, namespace_id, actor_kind, actor_id, actor_name, action, resource_kind, resource_id,
       resource_name, result, ip, user_agent, details
FROM audit_logs
WHERE tenant_id = $1::text
  AND created_at >= $2::timestamptz
  AND created_at < $3::timestamptz
  AND ($4::text = '' OR namespace_id = $4::text)
  AND ($5::boolean OR namespace_id = ANY($6::text[]))
  AND ($7::text = '' OR actor_id = $7::text OR actor_name = $7::text)
  AND ($8::text = '' OR action = $8::text)
  AND ($9::text = '' OR resource_kind = $9::text)
  AND ($10::text = '' OR resource_id = $10::text)
  AND ($11::text = '' OR result = $11::text)
  AND (NOT $12::boolean OR (created_at, id) < ($13::timestamptz, $14::text))
ORDER BY created_at DESC, id DESC
LIMIT $15
`

type AuthAuditListParams struct {
	TenantID        string    `json:"tenant_id"`
	StartAt         time.Time `json:"start_at"`
	EndAt           time.Time `json:"end_at"`
	NamespaceID     string    `json:"namespace_id"`
	AllNamespaces   bool      `json:"all_namespaces"`
	NamespaceIds    []string  `json:"namespace_ids"`
	Actor           string    `json:"actor"`
	Action          string    `json:"action"`
	ResourceKind    string    `json:"resource_kind"`
	ResourceID      string    `json:"resource_id"`
	Result          string    `json:"result"`
	HasCursor       bool      `json:"has_cursor"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        string    `json:"cursor_id"`
	PageLimit       int32     `json:"page_limit"`
}

// Audit log reads of the auth track (writes are done by internal/audit).
func (q *Queries) AuthAuditList(ctx context.Context, arg AuthAuditListParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, authAuditList,
		arg.TenantID,
		arg.StartAt,
		arg.EndAt,
		arg.NamespaceID,
		arg.AllNamespaces,
		arg.NamespaceIds,
		arg.Actor,
		arg.Action,
		arg.ResourceKind,
		arg.ResourceID,
		arg.Result,
		arg.HasCursor,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.TenantID,
			&i.NamespaceID,
			&i.ActorKind,
			&i.ActorID,
			&i.ActorName,
			&i.Action,
			&i.ResourceKind,
			&i.ResourceID,
			&i.ResourceName,
			&i.Result,
			&i.Ip,
			&i.UserAgent,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const authNamespaceNames = `-- name: AuthNamespaceNames :many
SELECT id, name
FROM namespaces
WHERE id = ANY($1::text[])
`

type AuthNamespaceNamesRow struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) AuthNamespaceNames(ctx context.Context, ids []string) ([]AuthNamespaceNamesRow, error) {
	rows, err := q.db.Query(ctx, authNamespaceNames, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthNamespaceNamesRow{}
	for rows.Next() {
		var i AuthNamespaceNamesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
