// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bindings.sql

package authdb

import (
	"context"
	"time"
)

const authBindingCount = `-- name: AuthBindingCount :one
SELECT count(*)::integer AS total
FROM role_bindings rb
WHERE rb.tenant_id = $1::text
  AND ($2::text = '' OR rb.user_id = $2::text)
`

type AuthBindingCountParams struct {
	TenantID string `json:"tenant_id"`
	UserID   string `json:"user_id"`
}

func (q *Queries) AuthBindingCount(ctx context.Context, arg AuthBindingCountParams) (int32, error) {
	row := q.db.QueryRow(ctx, authBindingCount, arg.TenantID, arg.UserID)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const authBindingDelete = `-- name: AuthBindingDelete :execrows
DELETE FROM role_bindings
WHERE id = $1
`

func (q *Queries) AuthBindingDelete(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, authBindingDelete, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const authBindingGet = `-- name: AuthBindingGet :one
SELECT rb.id, rb.user_id, u.username, rb.tenant_id, rb.role, rb.namespace_id, coalesce(n.name, '')::text AS namespace_name,
       rb.site_ids, rb.extra_permissions, rb.created_by, rb.created_at
FROM role_bindings rb
JOIN users u ON u.id = rb.user_id
LEFT JOIN namespaces n ON n.id = rb.namespace_id
WHERE rb.id = $1
`

type AuthBindingGetRow struct {
	ID               string    `json:"id"`
	UserID           string    `json:"user_id"`
	Username         string    `json:"username"`
	TenantID         string    `json:"tenant_id"`
	Role             string    `json:"role"`
	NamespaceID      *string   `json:"namespace_id"`
	NamespaceName    string    `json:"namespace_name"`
	SiteIds          []string  `json:"site_ids"`
	ExtraPermissions []string  `json:"extra_permissions"`
	CreatedBy        string    `json:"created_by"`
	CreatedAt        time.Time `json:"created_at"`
}

func (q *Queries) AuthBindingGet(ctx context.Context, id string) (AuthBindingGetRow, error) {
	row := q.db.QueryRow(ctx, authBindingGet, id)
	var i AuthBindingGetRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.TenantID,
		&i.Role,
		&i.NamespaceID,
		&i.NamespaceName,
		&i.SiteIds,
		&i.ExtraPermissions,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const authBindingInsert = `-- name: AuthBindingInsert :one
INSERT INTO role_bindings (id, user_id, tenant_id, role, namespace_id, site_ids, extra_permissions, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, tenant_id, role, namespace_id, site_ids, extra_permissions, created_by, created_at
`

type AuthBindingInsertParams struct {
	ID               string   `json:"id"`
	UserID           string   `json:"user_id"`
	TenantID         string   `json:"tenant_id"`
	Role             string   `json:"role"`
	NamespaceID      *string  `json:"namespace_id"`
	SiteIds          []string `json:"site_ids"`
	ExtraPermissions []string `json:"extra_permissions"`
	CreatedBy        string   `json:"created_by"`
}

func (q *Queries) AuthBindingInsert(ctx context.Context, arg AuthBindingInsertParams) (RoleBinding, error) {
	row := q.db.QueryRow(ctx, authBindingInsert,
		arg.ID,
		arg.UserID,
		arg.TenantID,
		arg.Role,
		arg.NamespaceID,
		arg.SiteIds,
		arg.ExtraPermissions,
		arg.CreatedBy,
	)
	var i RoleBinding
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Role,
		&i.NamespaceID,
		&i.SiteIds,
		&i.ExtraPermissions,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const authBindingList = `-- name: AuthBindingList :many
SELECT rb.id, rb.user_id, u.username, rb.tenant_id, rb.role, rb.namespace_id, coalesce(n.name, '')::text AS namespace_name,
       rb.site_ids, rb.extra_permissions, rb.created_by, rb.created_at
FROM role_bindings rb
JOIN users u ON u.id = rb.user_id
LEFT JOIN namespaces n ON n.id = rb.namespace_id
WHERE rb.tenant_id = $1::text
  AND ($2::text = '' OR rb.user_id = $2::text)
  AND (NOT $3::boolean
       OR (u.username, rb.created_at, rb.id) > ($4::text, $5::timestamptz, $6::text))
ORDER BY u.username, rb.created_at, rb.id
LIMIT $7
`

type AuthBindingListParams struct {
	TenantID        string    `json:"tenant_id"`
	UserID          string    `json:"user_id"`
	HasCursor       bool      `json:"has_cursor"`
	CursorUsername  string    `json:"cursor_username"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        string    `json:"cursor_id"`
	PageLimit       int32     `json:"page_limit"`
}

type AuthBindingListRow struct {
	ID               string    `json:"id"`
	UserID           string    `json:"user_id"`
	Username         string    `json:"username"`
	TenantID         string    `json:"tenant_id"`
	Role             string    `json:"role"`
	NamespaceID      *string   `json:"namespace_id"`
	NamespaceName    string    `json:"namespace_name"`
	SiteIds          []string  `json:"site_ids"`
	ExtraPermissions []string  `json:"extra_permissions"`
	CreatedBy        string    `json:"created_by"`
	CreatedAt        time.Time `json:"created_at"`
}

func (q *Queries) AuthBindingList(ctx context.Context, arg AuthBindingListParams) ([]AuthBindingListRow, error) {
	rows, err := q.db.Query(ctx, authBindingList,
		arg.TenantID,
		arg.UserID,
		arg.HasCursor,
		arg.CursorUsername,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthBindingListRow{}
	for rows.Next() {
		var i AuthBindingListRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.TenantID,
			&i.Role,
			&i.NamespaceID,
			&i.NamespaceName,
			&i.SiteIds,
			&i.ExtraPermissions,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const authBindingsOfUser = `-- name: AuthBindingsOfUser :many

SELECT id, user_id, tenant_id, role, namespace_id, site_ids, extra_permissions, created_by, created_at
FROM role_bindings
WHERE user_id = $1
ORDER BY created_at, id
`

// Role binding, tenant and namespace lookups of the auth track.
func (q *Queries) AuthBindingsOfUser(ctx context.Context, userID string) ([]RoleBinding, error) {
	rows, err := q.db.Query(ctx, authBindingsOfUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoleBinding{}
	for rows.Next() {
		var i RoleBinding
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantID,
			&i.Role,
			&i.NamespaceID,
			&i.SiteIds,
			&i.ExtraPermissions,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const authBindingsOfUsers = `-- name: AuthBindingsOfUsers :many
SELECT rb.id, rb.user_id, u.username, rb.tenant_id, rb.role, rb.namespace_id, coalesce(n.name, '')::text AS namespace_name,
       rb.site_ids, rb.extra_permissions, rb.created_by, rb.created_at
FROM role_bindings rb
JOIN users u ON u.id = rb.user_id
LEFT JOIN namespaces n ON n.id = rb.namespace_id
WHERE rb.user_id = ANY($1::text[])
  AND ($2::text = '' OR rb.tenant_id = $2::text)
ORDER BY rb.tenant_id, rb.created_at, rb.id
`

type AuthBindingsOfUsersParams struct {
	UserIds  []string `json:"user_ids"`
	TenantID string   `json:"tenant_id"`
}

type AuthBindingsOfUsersRow struct {
	ID               string    `json:"id"`
	UserID           string    `json:"user_id"`
	Username         string    `json:"username"`
	TenantID         string    `json:"tenant_id"`
	Role             string    `json:"role"`
	NamespaceID      *string   `json:"namespace_id"`
	NamespaceName    string    `json:"namespace_name"`
	SiteIds          []string  `json:"site_ids"`
	ExtraPermissions []string  `json:"extra_permissions"`
	CreatedBy        string    `json:"created_by"`
	CreatedAt        time.Time `json:"created_at"`
}

func (q *Queries) AuthBindingsOfUsers(ctx context.Context, arg AuthBindingsOfUsersParams) ([]AuthBindingsOfUsersRow, error) {
	rows, err := q.db.Query(ctx, authBindingsOfUsers, arg.UserIds, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthBindingsOfUsersRow{}
	for rows.Next() {
		var i AuthBindingsOfUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.TenantID,
			&i.Role,
			&i.NamespaceID,
			&i.NamespaceName,
			&i.SiteIds,
			&i.ExtraPermissions,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const authNamespacesOfTenants = `-- name: AuthNamespacesOfTenants :many
SELECT id, tenant_id, name, display_name, description, created_at, updated_at
FROM namespaces
WHERE tenant_id = ANY($1::text[])
ORDER BY tenant_id, name
`

func (q *Queries) AuthNamespacesOfTenants(ctx context.Context, tenantIds []string) ([]Namespace, error) {
	rows, err := q.db.Query(ctx, authNamespacesOfTenants, tenantIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Namespace{}
	for rows.Next() {
		var i Namespace
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const authSitesByIDs = `-- name: AuthSitesByIDs :many
SELECT id, namespace_id, name
FROM sites
WHERE id = ANY($1::text[])
`

type AuthSitesByIDsRow struct {
	ID          string `json:"id"`
	NamespaceID string `json:"namespace_id"`
	Name        string `json:"name"`
}

func (q *Queries) AuthSitesByIDs(ctx context.Context, ids []string) ([]AuthSitesByIDsRow, error) {
	rows, err := q.db.Query(ctx, authSitesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthSitesByIDsRow{}
	for rows.Next() {
		var i AuthSitesByIDsRow
		if err := rows.Scan(&i.ID, &i.NamespaceID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const authTenantExists = `-- name: AuthTenantExists :one
SELECT EXISTS (SELECT 1 FROM tenants WHERE id = $1) AS present
`

func (q *Queries) AuthTenantExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, authTenantExists, id)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const authTenantOwnerBindingsForUpdate = `-- name: AuthTenantOwnerBindingsForUpdate :many
SELECT id
FROM role_bindings
WHERE tenant_id = $1
  AND role = 'owner'
  AND namespace_id IS NULL
  AND cardinality(site_ids) = 0
ORDER BY id
FOR UPDATE
`

func (q *Queries) AuthTenantOwnerBindingsForUpdate(ctx context.Context, tenantID string) ([]string, error) {
	rows, err := q.db.Query(ctx, authTenantOwnerBindingsForUpdate, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const authTenantsAll = `-- name: AuthTenantsAll :many
SELECT id, name, display_name, description, created_at, updated_at
FROM tenants
ORDER BY name
LIMIT $1
`

func (q *Queries) AuthTenantsAll(ctx context.Context, pageLimit int32) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, authTenantsAll, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const authTenantsByIDs = `-- name: AuthTenantsByIDs :many
SELECT id, name, display_name, description, created_at, updated_at
FROM tenants
WHERE id = ANY($1::text[])
ORDER BY name
`

func (q *Queries) AuthTenantsByIDs(ctx context.Context, ids []string) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, authTenantsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
