// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package authdb

import (
	"context"
	"time"
)

const authNamespaceGet = `-- name: AuthNamespaceGet :one
SELECT id, tenant_id, name
FROM namespaces
WHERE id = $1
`

type AuthNamespaceGetRow struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
	Name     string `json:"name"`
}

func (q *Queries) AuthNamespaceGet(ctx context.Context, id string) (AuthNamespaceGetRow, error) {
	row := q.db.QueryRow(ctx, authNamespaceGet, id)
	var i AuthNamespaceGetRow
	err := row.Scan(&i.ID, &i.TenantID, &i.Name)
	return i, err
}

const authNamespacesOfTenant = `-- name: AuthNamespacesOfTenant :many
SELECT id, tenant_id, name
FROM namespaces
WHERE tenant_id = $1
ORDER BY name
`

type AuthNamespacesOfTenantRow struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
	Name     string `json:"name"`
}

func (q *Queries) AuthNamespacesOfTenant(ctx context.Context, tenantID string) ([]AuthNamespacesOfTenantRow, error) {
	rows, err := q.db.Query(ctx, authNamespacesOfTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthNamespacesOfTenantRow{}
	for rows.Next() {
		var i AuthNamespacesOfTenantRow
		if err := rows.Scan(&i.ID, &i.TenantID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const authTokenByHash = `-- name: AuthTokenByHash :one

SELECT t.id, t.tenant_id, t.namespace_id, n.name AS namespace_name, t.name, t.scopes, t.ip_allowlist,
       t.rate_limit_rps, t.expires_at, t.revoked_at
FROM api_tokens t
JOIN namespaces n ON n.id = t.namespace_id
WHERE t.token_hash = $1
`

type AuthTokenByHashRow struct {
	ID            string     `json:"id"`
	TenantID      string     `json:"tenant_id"`
	NamespaceID   string     `json:"namespace_id"`
	NamespaceName string     `json:"namespace_name"`
	Name          string     `json:"name"`
	Scopes        []string   `json:"scopes"`
	IpAllowlist   []string   `json:"ip_allowlist"`
	RateLimitRps  int32      `json:"rate_limit_rps"`
	ExpiresAt     *time.Time `json:"expires_at"`
	RevokedAt     *time.Time `json:"revoked_at"`
}

// API token queries of the auth track.
func (q *Queries) AuthTokenByHash(ctx context.Context, tokenHash []byte) (AuthTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, authTokenByHash, tokenHash)
	var i AuthTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.NamespaceID,
		&i.NamespaceName,
		&i.Name,
		&i.Scopes,
		&i.IpAllowlist,
		&i.RateLimitRps,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const authTokenCount = `-- name: AuthTokenCount :one
SELECT count(*)::integer AS total
FROM api_tokens t
WHERE t.namespace_id = ANY($1::text[])
  AND ($2::boolean OR t.revoked_at IS NULL)
`

type AuthTokenCountParams struct {
	NamespaceIds   []string `json:"namespace_ids"`
	IncludeRevoked bool     `json:"include_revoked"`
}

func (q *Queries) AuthTokenCount(ctx context.Context, arg AuthTokenCountParams) (int32, error) {
	row := q.db.QueryRow(ctx, authTokenCount, arg.NamespaceIds, arg.IncludeRevoked)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const authTokenGet = `-- name: AuthTokenGet :one
SELECT t.id, t.tenant_id, t.namespace_id, n.name AS namespace_name, t.name, t.description, t.token_prefix,
       t.scopes, t.ip_allowlist, t.rate_limit_rps, t.expires_at, t.revoked_at, t.last_used_at, t.last_used_ip,
       t.created_by, t.created_at
FROM api_tokens t
JOIN namespaces n ON n.id = t.namespace_id
WHERE t.id = $1
`

type AuthTokenGetRow struct {
	ID            string     `json:"id"`
	TenantID      string     `json:"tenant_id"`
	NamespaceID   string     `json:"namespace_id"`
	NamespaceName string     `json:"namespace_name"`
	Name          string     `json:"name"`
	Description   string     `json:"description"`
	TokenPrefix   string     `json:"token_prefix"`
	Scopes        []string   `json:"scopes"`
	IpAllowlist   []string   `json:"ip_allowlist"`
	RateLimitRps  int32      `json:"rate_limit_rps"`
	ExpiresAt     *time.Time `json:"expires_at"`
	RevokedAt     *time.Time `json:"revoked_at"`
	LastUsedAt    *time.Time `json:"last_used_at"`
	LastUsedIp    string     `json:"last_used_ip"`
	CreatedBy     string     `json:"created_by"`
	CreatedAt     time.Time  `json:"created_at"`
}

func (q *Queries) AuthTokenGet(ctx context.Context, id string) (AuthTokenGetRow, error) {
	row := q.db.QueryRow(ctx, authTokenGet, id)
	var i AuthTokenGetRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.NamespaceID,
		&i.NamespaceName,
		&i.Name,
		&i.Description,
		&i.TokenPrefix,
		&i.Scopes,
		&i.IpAllowlist,
		&i.RateLimitRps,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const authTokenInsert = `-- name: AuthTokenInsert :one
INSERT INTO api_tokens (
    id, tenant_id, namespace_id, name, description, token_prefix, token_hash, scopes, ip_allowlist,
    rate_limit_rps, expires_at, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12
)
RETURNING id, tenant_id, namespace_id, name, description, token_prefix, scopes, ip_allowlist, rate_limit_rps,
          expires_at, revoked_at, last_used_at, last_used_ip, created_by, created_at
`

type AuthTokenInsertParams struct {
	ID           string     `json:"id"`
	TenantID     string     `json:"tenant_id"`
	NamespaceID  string     `json:"namespace_id"`
	Name         string     `json:"name"`
	Description  string     `json:"description"`
	TokenPrefix  string     `json:"token_prefix"`
	TokenHash    []byte     `json:"token_hash"`
	Scopes       []string   `json:"scopes"`
	IpAllowlist  []string   `json:"ip_allowlist"`
	RateLimitRps int32      `json:"rate_limit_rps"`
	ExpiresAt    *time.Time `json:"expires_at"`
	CreatedBy    string     `json:"created_by"`
}

type AuthTokenInsertRow struct {
	ID           string     `json:"id"`
	TenantID     string     `json:"tenant_id"`
	NamespaceID  string     `json:"namespace_id"`
	Name         string     `json:"name"`
	Description  string     `json:"description"`
	TokenPrefix  string     `json:"token_prefix"`
	Scopes       []string   `json:"scopes"`
	IpAllowlist  []string   `json:"ip_allowlist"`
	RateLimitRps int32      `json:"rate_limit_rps"`
	ExpiresAt    *time.Time `json:"expires_at"`
	RevokedAt    *time.Time `json:"revoked_at"`
	LastUsedAt   *time.Time `json:"last_used_at"`
	LastUsedIp   string     `json:"last_used_ip"`
	CreatedBy    string     `json:"created_by"`
	CreatedAt    time.Time  `json:"created_at"`
}

func (q *Queries) AuthTokenInsert(ctx context.Context, arg AuthTokenInsertParams) (AuthTokenInsertRow, error) {
	row := q.db.QueryRow(ctx, authTokenInsert,
		arg.ID,
		arg.TenantID,
		arg.NamespaceID,
		arg.Name,
		arg.Description,
		arg.TokenPrefix,
		arg.TokenHash,
		arg.Scopes,
		arg.IpAllowlist,
		arg.RateLimitRps,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i AuthTokenInsertRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.NamespaceID,
		&i.Name,
		&i.Description,
		&i.TokenPrefix,
		&i.Scopes,
		&i.IpAllowlist,
		&i.RateLimitRps,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const authTokenList = `-- name: AuthTokenList :many
SELECT t.id, t.tenant_id, t.namespace_id, n.name AS namespace_name, t.name, t.description, t.token_prefix,
       t.scopes, t.ip_allowlist, t.rate_limit_rps, t.expires_at, t.revoked_at, t.last_used_at, t.last_used_ip,
       t.created_by, t.created_at
FROM api_tokens t
JOIN namespaces n ON n.id = t.namespace_id
WHERE t.namespace_id = ANY($1::text[])
  AND ($2::boolean OR t.revoked_at IS NULL)
  AND (NOT $3::boolean OR (t.created_at, t.id) < ($4::timestamptz, $5::text))
ORDER BY t.created_at DESC, t.id DESC
LIMIT $6
`

type AuthTokenListParams struct {
	NamespaceIds    []string  `json:"namespace_ids"`
	IncludeRevoked  bool      `json:"include_revoked"`
	HasCursor       bool      `json:"has_cursor"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        string    `json:"cursor_id"`
	PageLimit       int32     `json:"page_limit"`
}

type AuthTokenListRow struct {
	ID            string     `json:"id"`
	TenantID      string     `json:"tenant_id"`
	NamespaceID   string     `json:"namespace_id"`
	NamespaceName string     `json:"namespace_name"`
	Name          string     `json:"name"`
	Description   string     `json:"description"`
	TokenPrefix   string     `json:"token_prefix"`
	Scopes        []string   `json:"scopes"`
	IpAllowlist   []string   `json:"ip_allowlist"`
	RateLimitRps  int32      `json:"rate_limit_rps"`
	ExpiresAt     *time.Time `json:"expires_at"`
	RevokedAt     *time.Time `json:"revoked_at"`
	LastUsedAt    *time.Time `json:"last_used_at"`
	LastUsedIp    string     `json:"last_used_ip"`
	CreatedBy     string     `json:"created_by"`
	CreatedAt     time.Time  `json:"created_at"`
}

func (q *Queries) AuthTokenList(ctx context.Context, arg AuthTokenListParams) ([]AuthTokenListRow, error) {
	rows, err := q.db.Query(ctx, authTokenList,
		arg.NamespaceIds,
		arg.IncludeRevoked,
		arg.HasCursor,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthTokenListRow{}
	for rows.Next() {
		var i AuthTokenListRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.NamespaceID,
			&i.NamespaceName,
			&i.Name,
			&i.Description,
			&i.TokenPrefix,
			&i.Scopes,
			&i.IpAllowlist,
			&i.RateLimitRps,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.LastUsedIp,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const authTokenRevoke = `-- name: AuthTokenRevoke :one
UPDATE api_tokens
SET revoked_at = coalesce(revoked_at, now())
WHERE id = $1
RETURNING revoked_at
`

func (q *Queries) AuthTokenRevoke(ctx context.Context, id string) (*time.Time, error) {
	row := q.db.QueryRow(ctx, authTokenRevoke, id)
	var revoked_at *time.Time
	err := row.Scan(&revoked_at)
	return revoked_at, err
}

const authTokenTouch = `-- name: AuthTokenTouch :exec
UPDATE api_tokens AS t
SET last_used_at = v.used_at,
    last_used_ip = v.used_ip
FROM (
    SELECT unnest($1::text[]) AS id,
           unnest($2::timestamptz[]) AS used_at,
           unnest($3::text[]) AS used_ip
) AS v
WHERE t.id = v.id
  AND (t.last_used_at IS NULL OR t.last_used_at < v.used_at)
`

type AuthTokenTouchParams struct {
	Ids    []string    `json:"ids"`
	UsedAt []time.Time `json:"used_at"`
	UsedIp []string    `json:"used_ip"`
}

func (q *Queries) AuthTokenTouch(ctx context.Context, arg AuthTokenTouchParams) error {
	_, err := q.db.Exec(ctx, authTokenTouch, arg.Ids, arg.UsedAt, arg.UsedIp)
	return err
}
