// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package authdb

import (
	"context"
	"time"
)

const authBootstrapLock = `-- name: AuthBootstrapLock :exec
SELECT pg_advisory_xact_lock(hashtext('spinneret:bootstrap-platform-admin'))
`

func (q *Queries) AuthBootstrapLock(ctx context.Context) error {
	_, err := q.db.Exec(ctx, authBootstrapLock)
	return err
}

const authNamespaceByName = `-- name: AuthNamespaceByName :one
SELECT id, tenant_id, name
FROM namespaces
WHERE tenant_id = $1 AND name = $2
`

type AuthNamespaceByNameParams struct {
	TenantID string `json:"tenant_id"`
	Name     string `json:"name"`
}

type AuthNamespaceByNameRow struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
	Name     string `json:"name"`
}

func (q *Queries) AuthNamespaceByName(ctx context.Context, arg AuthNamespaceByNameParams) (AuthNamespaceByNameRow, error) {
	row := q.db.QueryRow(ctx, authNamespaceByName, arg.TenantID, arg.Name)
	var i AuthNamespaceByNameRow
	err := row.Scan(&i.ID, &i.TenantID, &i.Name)
	return i, err
}

const authNamespaceInsert = `-- name: AuthNamespaceInsert :one
INSERT INTO namespaces (id, tenant_id, name, display_name)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, name
`

type AuthNamespaceInsertParams struct {
	ID          string `json:"id"`
	TenantID    string `json:"tenant_id"`
	Name        string `json:"name"`
	DisplayName string `json:"display_name"`
}

type AuthNamespaceInsertRow struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
	Name     string `json:"name"`
}

func (q *Queries) AuthNamespaceInsert(ctx context.Context, arg AuthNamespaceInsertParams) (AuthNamespaceInsertRow, error) {
	row := q.db.QueryRow(ctx, authNamespaceInsert,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.DisplayName,
	)
	var i AuthNamespaceInsertRow
	err := row.Scan(&i.ID, &i.TenantID, &i.Name)
	return i, err
}

const authPlatformAdminExists = `-- name: AuthPlatformAdminExists :one
SELECT EXISTS (SELECT 1 FROM users WHERE is_platform_admin) AS present
`

func (q *Queries) AuthPlatformAdminExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, authPlatformAdminExists)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const authTenantByName = `-- name: AuthTenantByName :one
SELECT id, name, display_name, description, created_at, updated_at
FROM tenants
WHERE name = $1
`

func (q *Queries) AuthTenantByName(ctx context.Context, name string) (Tenant, error) {
	row := q.db.QueryRow(ctx, authTenantByName, name)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const authTenantInsert = `-- name: AuthTenantInsert :one
INSERT INTO tenants (id, name, display_name)
VALUES ($1, $2, $3)
RETURNING id, name, display_name, description, created_at, updated_at
`

type AuthTenantInsertParams struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) AuthTenantInsert(ctx context.Context, arg AuthTenantInsertParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, authTenantInsert, arg.ID, arg.Name, arg.DisplayName)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const authUserByID = `-- name: AuthUserByID :one
SELECT id, username, display_name, email, password_hash, is_platform_admin, disabled, locale, last_login_at,
       last_login_ip, password_changed_at, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) AuthUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, authUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.IsPlatformAdmin,
		&i.Disabled,
		&i.Locale,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const authUserByUsername = `-- name: AuthUserByUsername :one

SELECT id, username, display_name, email, password_hash, is_platform_admin, disabled, locale, last_login_at,
       last_login_ip, password_changed_at, created_at, updated_at
FROM users
WHERE username = $1
`

// User and session-related queries of the auth track.
func (q *Queries) AuthUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, authUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.IsPlatformAdmin,
		&i.Disabled,
		&i.Locale,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const authUserCountMembers = `-- name: AuthUserCountMembers :one
SELECT count(*)::integer AS total
FROM users u
WHERE ($1::boolean OR EXISTS (
        SELECT 1 FROM role_bindings rb WHERE rb.user_id = u.id AND rb.tenant_id = $2::text))
  AND ($3::text = ''
       OR strpos(lower(u.username), lower($3::text)) > 0
       OR strpos(lower(u.display_name), lower($3::text)) > 0
       OR strpos(lower(u.email), lower($3::text)) > 0)
`

type AuthUserCountMembersParams struct {
	AllUsers bool   `json:"all_users"`
	TenantID string `json:"tenant_id"`
	Query    string `json:"query"`
}

func (q *Queries) AuthUserCountMembers(ctx context.Context, arg AuthUserCountMembersParams) (int32, error) {
	row := q.db.QueryRow(ctx, authUserCountMembers, arg.AllUsers, arg.TenantID, arg.Query)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const authUserInsert = `-- name: AuthUserInsert :one
INSERT INTO users (id, username, display_name, email, password_hash, is_platform_admin, password_changed_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
RETURNING id, username, display_name, email, password_hash, is_platform_admin, disabled, locale, last_login_at,
          last_login_ip, password_changed_at, created_at, updated_at
`

type AuthUserInsertParams struct {
	ID              string `json:"id"`
	Username        string `json:"username"`
	DisplayName     string `json:"display_name"`
	Email           string `json:"email"`
	PasswordHash    string `json:"password_hash"`
	IsPlatformAdmin bool   `json:"is_platform_admin"`
}

func (q *Queries) AuthUserInsert(ctx context.Context, arg AuthUserInsertParams) (User, error) {
	row := q.db.QueryRow(ctx, authUserInsert,
		arg.ID,
		arg.Username,
		arg.DisplayName,
		arg.Email,
		arg.PasswordHash,
		arg.IsPlatformAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.IsPlatformAdmin,
		&i.Disabled,
		&i.Locale,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const authUserListMembers = `-- name: AuthUserListMembers :many
SELECT u.id, u.username, u.display_name, u.email, u.is_platform_admin, u.disabled, u.locale, u.last_login_at,
       u.created_at
FROM users u
WHERE ($1::boolean OR EXISTS (
        SELECT 1 FROM role_bindings rb WHERE rb.user_id = u.id AND rb.tenant_id = $2::text))
  AND ($3::text = ''
       OR strpos(lower(u.username), lower($3::text)) > 0
       OR strpos(lower(u.display_name), lower($3::text)) > 0
       OR strpos(lower(u.email), lower($3::text)) > 0)
  AND u.username > $4::text
ORDER BY u.username
LIMIT $5
`

type AuthUserListMembersParams struct {
	AllUsers      bool   `json:"all_users"`
	TenantID      string `json:"tenant_id"`
	Query         string `json:"query"`
	AfterUsername string `json:"after_username"`
	PageLimit     int32  `json:"page_limit"`
}

type AuthUserListMembersRow struct {
	ID              string     `json:"id"`
	Username        string     `json:"username"`
	DisplayName     string     `json:"display_name"`
	Email           string     `json:"email"`
	IsPlatformAdmin bool       `json:"is_platform_admin"`
	Disabled        bool       `json:"disabled"`
	Locale          string     `json:"locale"`
	LastLoginAt     *time.Time `json:"last_login_at"`
	CreatedAt       time.Time  `json:"created_at"`
}

func (q *Queries) AuthUserListMembers(ctx context.Context, arg AuthUserListMembersParams) ([]AuthUserListMembersRow, error) {
	rows, err := q.db.Query(ctx, authUserListMembers,
		arg.AllUsers,
		arg.TenantID,
		arg.Query,
		arg.AfterUsername,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthUserListMembersRow{}
	for rows.Next() {
		var i AuthUserListMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Email,
			&i.IsPlatformAdmin,
			&i.Disabled,
			&i.Locale,
			&i.LastLoginAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const authUserRecordLogin = `-- name: AuthUserRecordLogin :exec
UPDATE users
SET last_login_at = now(),
    last_login_ip = $1
WHERE id = $2
`

type AuthUserRecordLoginParams struct {
	Ip string `json:"ip"`
	ID string `json:"id"`
}

func (q *Queries) AuthUserRecordLogin(ctx context.Context, arg AuthUserRecordLoginParams) error {
	_, err := q.db.Exec(ctx, authUserRecordLogin, arg.Ip, arg.ID)
	return err
}

const authUserSetPassword = `-- name: AuthUserSetPassword :one
UPDATE users
SET password_hash = $1,
    password_changed_at = now(),
    updated_at = now()
WHERE id = $2
RETURNING password_changed_at
`

type AuthUserSetPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           string `json:"id"`
}

// AuthUserSetPassword returns the new password generation (sessions store the
// generation they were created with, see sessions.go).
func (q *Queries) AuthUserSetPassword(ctx context.Context, arg AuthUserSetPasswordParams) (*time.Time, error) {
	row := q.db.QueryRow(ctx, authUserSetPassword, arg.PasswordHash, arg.ID)
	var password_changed_at *time.Time
	err := row.Scan(&password_changed_at)
	return password_changed_at, err
}

const authUserUpdate = `-- name: AuthUserUpdate :one
UPDATE users
SET display_name = coalesce($1::text, display_name),
    email = coalesce($2::text, email),
    locale = coalesce($3::text, locale),
    disabled = coalesce($4::boolean, disabled),
    updated_at = now()
WHERE id = $5
RETURNING id, username, display_name, email, password_hash, is_platform_admin, disabled, locale, last_login_at,
          last_login_ip, password_changed_at, created_at, updated_at
`

type AuthUserUpdateParams struct {
	DisplayName *string `json:"display_name"`
	Email       *string `json:"email"`
	Locale      *string `json:"locale"`
	Disabled    *bool   `json:"disabled"`
	ID          string  `json:"id"`
}

func (q *Queries) AuthUserUpdate(ctx context.Context, arg AuthUserUpdateParams) (User, error) {
	row := q.db.QueryRow(ctx, authUserUpdate,
		arg.DisplayName,
		arg.Email,
		arg.Locale,
		arg.Disabled,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.IsPlatformAdmin,
		&i.Disabled,
		&i.Locale,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
