// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hotstate.sql

package hotstatedb

import (
	"context"
	"time"
)

const hotstateAccountMembers = `-- name: HotstateAccountMembers :many
SELECT account_id::text AS account_id, hkey
FROM identities
WHERE site_id = $1
  AND account_id = ANY ($2::text[])
  AND state <> 'retired'
ORDER BY account_id, hkey
`

type HotstateAccountMembersParams struct {
	SiteID     string   `json:"site_id"`
	AccountIds []string `json:"account_ids"`
}

type HotstateAccountMembersRow struct {
	AccountID string `json:"account_id"`
	Hkey      int64  `json:"hkey"`
}

func (q *Queries) HotstateAccountMembers(ctx context.Context, arg HotstateAccountMembersParams) ([]HotstateAccountMembersRow, error) {
	rows, err := q.db.Query(ctx, hotstateAccountMembers, arg.SiteID, arg.AccountIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HotstateAccountMembersRow{}
	for rows.Next() {
		var i HotstateAccountMembersRow
		if err := rows.Scan(&i.AccountID, &i.Hkey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hotstateAccountStateTimes = `-- name: HotstateAccountStateTimes :many
SELECT a.hkey,
       COALESCE((SELECT e.created_at
                 FROM state_events AS e
                 WHERE e.subject_id = a.id
                   AND e.subject_kind = 'account'
                   AND e.shadow = false
                   AND e.action <> 'cooldown'
                 ORDER BY e.created_at DESC
                 LIMIT 1), a.created_at)::timestamptz AS state_changed_at
FROM accounts AS a
WHERE a.hkey = ANY ($1::bigint[])
`

type HotstateAccountStateTimesRow struct {
	Hkey           int64     `json:"hkey"`
	StateChangedAt time.Time `json:"state_changed_at"`
}

// Time of the last lifecycle change of accounts by hot-state key: accounts
// have no state_changed_at column, but every account transition records a
// non-shadow, non-cooldown state event in the same transaction.
func (q *Queries) HotstateAccountStateTimes(ctx context.Context, hkeys []int64) ([]HotstateAccountStateTimesRow, error) {
	rows, err := q.db.Query(ctx, hotstateAccountStateTimes, hkeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HotstateAccountStateTimesRow{}
	for rows.Next() {
		var i HotstateAccountStateTimesRow
		if err := rows.Scan(&i.Hkey, &i.StateChangedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hotstateAccountsByIDs = `-- name: HotstateAccountsByIDs :many
SELECT a.id, a.hkey, a.state, a.ban_until, a.cooldown_until,
       COALESCE((SELECT e.created_at
                 FROM state_events AS e
                 WHERE e.subject_id = a.id
                   AND e.subject_kind = 'account'
                   AND e.shadow = false
                   AND e.action <> 'cooldown'
                 ORDER BY e.created_at DESC
                 LIMIT 1), a.created_at)::timestamptz AS state_changed_at
FROM accounts AS a
WHERE a.site_id = $1
  AND a.id = ANY ($2::text[])
`

type HotstateAccountsByIDsParams struct {
	SiteID string   `json:"site_id"`
	Ids    []string `json:"ids"`
}

type HotstateAccountsByIDsRow struct {
	ID             string     `json:"id"`
	Hkey           int64      `json:"hkey"`
	State          string     `json:"state"`
	BanUntil       *time.Time `json:"ban_until"`
	CooldownUntil  *time.Time `json:"cooldown_until"`
	StateChangedAt time.Time  `json:"state_changed_at"`
}

func (q *Queries) HotstateAccountsByIDs(ctx context.Context, arg HotstateAccountsByIDsParams) ([]HotstateAccountsByIDsRow, error) {
	rows, err := q.db.Query(ctx, hotstateAccountsByIDs, arg.SiteID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HotstateAccountsByIDsRow{}
	for rows.Next() {
		var i HotstateAccountsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Hkey,
			&i.State,
			&i.BanUntil,
			&i.CooldownUntil,
			&i.StateChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hotstateDeleteIdentitySnapshots = `-- name: HotstateDeleteIdentitySnapshots :exec
DELETE FROM hot_state_snapshots
WHERE site_id = $1
  AND subject IN ('ie', 'ig')
  AND subject_id = ANY ($2::text[])
`

type HotstateDeleteIdentitySnapshotsParams struct {
	SiteID      string   `json:"site_id"`
	IdentityIds []string `json:"identity_ids"`
}

func (q *Queries) HotstateDeleteIdentitySnapshots(ctx context.Context, arg HotstateDeleteIdentitySnapshotsParams) error {
	_, err := q.db.Exec(ctx, hotstateDeleteIdentitySnapshots, arg.SiteID, arg.IdentityIds)
	return err
}

const hotstateDeleteProxySnapshots = `-- name: HotstateDeleteProxySnapshots :exec
DELETE FROM hot_state_snapshots
WHERE subject = 'ps'
  AND subject_id = ANY ($1::text[])
`

func (q *Queries) HotstateDeleteProxySnapshots(ctx context.Context, proxyIds []string) error {
	_, err := q.db.Exec(ctx, hotstateDeleteProxySnapshots, proxyIds)
	return err
}

const hotstateExistingSiteHkeys = `-- name: HotstateExistingSiteHkeys :many
SELECT hkey
FROM sites
WHERE hkey = ANY ($1::bigint[])
`

func (q *Queries) HotstateExistingSiteHkeys(ctx context.Context, hkeys []int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, hotstateExistingSiteHkeys, hkeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var hkey int64
		if err := rows.Scan(&hkey); err != nil {
			return nil, err
		}
		items = append(items, hkey)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hotstateGroupIDsByHkeys = `-- name: HotstateGroupIDsByHkeys :many
SELECT hkey, id
FROM endpoint_groups
WHERE site_id = $1
  AND hkey = ANY ($2::bigint[])
`

type HotstateGroupIDsByHkeysParams struct {
	SiteID string  `json:"site_id"`
	Hkeys  []int64 `json:"hkeys"`
}

type HotstateGroupIDsByHkeysRow struct {
	Hkey int64  `json:"hkey"`
	ID   string `json:"id"`
}

func (q *Queries) HotstateGroupIDsByHkeys(ctx context.Context, arg HotstateGroupIDsByHkeysParams) ([]HotstateGroupIDsByHkeysRow, error) {
	rows, err := q.db.Query(ctx, hotstateGroupIDsByHkeys, arg.SiteID, arg.Hkeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HotstateGroupIDsByHkeysRow{}
	for rows.Next() {
		var i HotstateGroupIDsByHkeysRow
		if err := rows.Scan(&i.Hkey, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hotstateIdentitiesByIDs = `-- name: HotstateIdentitiesByIDs :many
SELECT i.id,
       i.hkey,
       i.client,
       i.type_id,
       t.name    AS type_name,
       t.version AS type_version,
       i.state,
       i.ban_until,
       i.quarantine_until,
       i.region,
       i.payload_version,
       i.activated_at,
       a.hkey           AS account_hkey,
       a.state          AS account_state,
       a.ban_until      AS account_ban_until,
       a.cooldown_until AS account_cooldown_until,
       p.hkey           AS proxy_hkey,
       i.state_changed_at
FROM identities i
JOIN identity_types t ON t.id = i.type_id
LEFT JOIN accounts a ON a.id = i.account_id
LEFT JOIN proxy_bindings b ON b.identity_id = i.id
LEFT JOIN proxies p ON p.id = b.proxy_id
WHERE i.site_id = $1
  AND i.id = ANY ($2::text[])
`

type HotstateIdentitiesByIDsParams struct {
	SiteID string   `json:"site_id"`
	Ids    []string `json:"ids"`
}

type HotstateIdentitiesByIDsRow struct {
	ID                   string     `json:"id"`
	Hkey                 int64      `json:"hkey"`
	Client               string     `json:"client"`
	TypeID               string     `json:"type_id"`
	TypeName             string     `json:"type_name"`
	TypeVersion          int32      `json:"type_version"`
	State                string     `json:"state"`
	BanUntil             *time.Time `json:"ban_until"`
	QuarantineUntil      *time.Time `json:"quarantine_until"`
	Region               string     `json:"region"`
	PayloadVersion       int32      `json:"payload_version"`
	ActivatedAt          *time.Time `json:"activated_at"`
	AccountHkey          *int64     `json:"account_hkey"`
	AccountState         *string    `json:"account_state"`
	AccountBanUntil      *time.Time `json:"account_ban_until"`
	AccountCooldownUntil *time.Time `json:"account_cooldown_until"`
	ProxyHkey            *int64     `json:"proxy_hkey"`
	StateChangedAt       time.Time  `json:"state_changed_at"`
}

func (q *Queries) HotstateIdentitiesByIDs(ctx context.Context, arg HotstateIdentitiesByIDsParams) ([]HotstateIdentitiesByIDsRow, error) {
	rows, err := q.db.Query(ctx, hotstateIdentitiesByIDs, arg.SiteID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HotstateIdentitiesByIDsRow{}
	for rows.Next() {
		var i HotstateIdentitiesByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Hkey,
			&i.Client,
			&i.TypeID,
			&i.TypeName,
			&i.TypeVersion,
			&i.State,
			&i.BanUntil,
			&i.QuarantineUntil,
			&i.Region,
			&i.PayloadVersion,
			&i.ActivatedAt,
			&i.AccountHkey,
			&i.AccountState,
			&i.AccountBanUntil,
			&i.AccountCooldownUntil,
			&i.ProxyHkey,
			&i.StateChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hotstateIdentitiesPage = `-- name: HotstateIdentitiesPage :many
SELECT i.id,
       i.hkey,
       i.client,
       i.type_id,
       t.name    AS type_name,
       t.version AS type_version,
       i.state,
       i.ban_until,
       i.quarantine_until,
       i.region,
       i.payload_version,
       i.activated_at,
       a.hkey           AS account_hkey,
       a.state          AS account_state,
       a.ban_until      AS account_ban_until,
       a.cooldown_until AS account_cooldown_until,
       p.hkey           AS proxy_hkey,
       i.state_changed_at
FROM identities i
JOIN identity_types t ON t.id = i.type_id
LEFT JOIN accounts a ON a.id = i.account_id
LEFT JOIN proxy_bindings b ON b.identity_id = i.id
LEFT JOIN proxies p ON p.id = b.proxy_id
WHERE i.site_id = $1
  AND i.hkey > $2
ORDER BY i.hkey
LIMIT $3
`

type HotstateIdentitiesPageParams struct {
	SiteID    string `json:"site_id"`
	AfterHkey int64  `json:"after_hkey"`
	PageSize  int32  `json:"page_size"`
}

type HotstateIdentitiesPageRow struct {
	ID                   string     `json:"id"`
	Hkey                 int64      `json:"hkey"`
	Client               string     `json:"client"`
	TypeID               string     `json:"type_id"`
	TypeName             string     `json:"type_name"`
	TypeVersion          int32      `json:"type_version"`
	State                string     `json:"state"`
	BanUntil             *time.Time `json:"ban_until"`
	QuarantineUntil      *time.Time `json:"quarantine_until"`
	Region               string     `json:"region"`
	PayloadVersion       int32      `json:"payload_version"`
	ActivatedAt          *time.Time `json:"activated_at"`
	AccountHkey          *int64     `json:"account_hkey"`
	AccountState         *string    `json:"account_state"`
	AccountBanUntil      *time.Time `json:"account_ban_until"`
	AccountCooldownUntil *time.Time `json:"account_cooldown_until"`
	ProxyHkey            *int64     `json:"proxy_hkey"`
	StateChangedAt       time.Time  `json:"state_changed_at"`
}

func (q *Queries) HotstateIdentitiesPage(ctx context.Context, arg HotstateIdentitiesPageParams) ([]HotstateIdentitiesPageRow, error) {
	rows, err := q.db.Query(ctx, hotstateIdentitiesPage, arg.SiteID, arg.AfterHkey, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HotstateIdentitiesPageRow{}
	for rows.Next() {
		var i HotstateIdentitiesPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Hkey,
			&i.Client,
			&i.TypeID,
			&i.TypeName,
			&i.TypeVersion,
			&i.State,
			&i.BanUntil,
			&i.QuarantineUntil,
			&i.Region,
			&i.PayloadVersion,
			&i.ActivatedAt,
			&i.AccountHkey,
			&i.AccountState,
			&i.AccountBanUntil,
			&i.AccountCooldownUntil,
			&i.ProxyHkey,
			&i.StateChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hotstateIdentityIDsByHkeys = `-- name: HotstateIdentityIDsByHkeys :many
SELECT hkey, id
FROM identities
WHERE site_id = $1
  AND hkey = ANY ($2::bigint[])
`

type HotstateIdentityIDsByHkeysParams struct {
	SiteID string  `json:"site_id"`
	Hkeys  []int64 `json:"hkeys"`
}

type HotstateIdentityIDsByHkeysRow struct {
	Hkey int64  `json:"hkey"`
	ID   string `json:"id"`
}

func (q *Queries) HotstateIdentityIDsByHkeys(ctx context.Context, arg HotstateIdentityIDsByHkeysParams) ([]HotstateIdentityIDsByHkeysRow, error) {
	rows, err := q.db.Query(ctx, hotstateIdentityIDsByHkeys, arg.SiteID, arg.Hkeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HotstateIdentityIDsByHkeysRow{}
	for rows.Next() {
		var i HotstateIdentityIDsByHkeysRow
		if err := rows.Scan(&i.Hkey, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hotstateIdentityRef = `-- name: HotstateIdentityRef :one
SELECT id, hkey, client, state
FROM identities
WHERE id = $1
  AND site_id = $2
`

type HotstateIdentityRefParams struct {
	ID     string `json:"id"`
	SiteID string `json:"site_id"`
}

type HotstateIdentityRefRow struct {
	ID     string `json:"id"`
	Hkey   int64  `json:"hkey"`
	Client string `json:"client"`
	State  string `json:"state"`
}

func (q *Queries) HotstateIdentityRef(ctx context.Context, arg HotstateIdentityRefParams) (HotstateIdentityRefRow, error) {
	row := q.db.QueryRow(ctx, hotstateIdentityRef, arg.ID, arg.SiteID)
	var i HotstateIdentityRefRow
	err := row.Scan(
		&i.ID,
		&i.Hkey,
		&i.Client,
		&i.State,
	)
	return i, err
}

const hotstateListSites = `-- name: HotstateListSites :many
SELECT id, hkey, namespace_id
FROM sites
ORDER BY hkey
`

type HotstateListSitesRow struct {
	ID          string `json:"id"`
	Hkey        int64  `json:"hkey"`
	NamespaceID string `json:"namespace_id"`
}

func (q *Queries) HotstateListSites(ctx context.Context) ([]HotstateListSitesRow, error) {
	rows, err := q.db.Query(ctx, hotstateListSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HotstateListSitesRow{}
	for rows.Next() {
		var i HotstateListSitesRow
		if err := rows.Scan(&i.ID, &i.Hkey, &i.NamespaceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hotstateLiveIdentityHkeys = `-- name: HotstateLiveIdentityHkeys :many
SELECT hkey
FROM identities
WHERE site_id = $1
  AND state <> 'retired'
  AND hkey = ANY ($2::bigint[])
`

type HotstateLiveIdentityHkeysParams struct {
	SiteID string  `json:"site_id"`
	Hkeys  []int64 `json:"hkeys"`
}

func (q *Queries) HotstateLiveIdentityHkeys(ctx context.Context, arg HotstateLiveIdentityHkeysParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, hotstateLiveIdentityHkeys, arg.SiteID, arg.Hkeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var hkey int64
		if err := rows.Scan(&hkey); err != nil {
			return nil, err
		}
		items = append(items, hkey)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hotstateLiveProxyHkeys = `-- name: HotstateLiveProxyHkeys :many
SELECT hkey
FROM proxies
WHERE namespace_id = $1
  AND hkey = ANY ($2::bigint[])
`

type HotstateLiveProxyHkeysParams struct {
	NamespaceID string  `json:"namespace_id"`
	Hkeys       []int64 `json:"hkeys"`
}

func (q *Queries) HotstateLiveProxyHkeys(ctx context.Context, arg HotstateLiveProxyHkeysParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, hotstateLiveProxyHkeys, arg.NamespaceID, arg.Hkeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var hkey int64
		if err := rows.Scan(&hkey); err != nil {
			return nil, err
		}
		items = append(items, hkey)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hotstateNamespaceSites = `-- name: HotstateNamespaceSites :many
SELECT id, hkey, namespace_id, paused
FROM sites
WHERE namespace_id = $1
ORDER BY hkey
`

type HotstateNamespaceSitesRow struct {
	ID          string `json:"id"`
	Hkey        int64  `json:"hkey"`
	NamespaceID string `json:"namespace_id"`
	Paused      bool   `json:"paused"`
}

func (q *Queries) HotstateNamespaceSites(ctx context.Context, namespaceID string) ([]HotstateNamespaceSitesRow, error) {
	rows, err := q.db.Query(ctx, hotstateNamespaceSites, namespaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HotstateNamespaceSitesRow{}
	for rows.Next() {
		var i HotstateNamespaceSitesRow
		if err := rows.Scan(
			&i.ID,
			&i.Hkey,
			&i.NamespaceID,
			&i.Paused,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hotstateProxiesByIDs = `-- name: HotstateProxiesByIDs :many
SELECT id, hkey, state, kind, region, provider, tags, max_concurrency, url_version, cooldown_until, ban_until,
       state_changed_at
FROM proxies
WHERE namespace_id = $1
  AND id = ANY ($2::text[])
`

type HotstateProxiesByIDsParams struct {
	NamespaceID string   `json:"namespace_id"`
	Ids         []string `json:"ids"`
}

type HotstateProxiesByIDsRow struct {
	ID             string     `json:"id"`
	Hkey           int64      `json:"hkey"`
	State          string     `json:"state"`
	Kind           string     `json:"kind"`
	Region         string     `json:"region"`
	Provider       string     `json:"provider"`
	Tags           []string   `json:"tags"`
	MaxConcurrency int32      `json:"max_concurrency"`
	UrlVersion     int32      `json:"url_version"`
	CooldownUntil  *time.Time `json:"cooldown_until"`
	BanUntil       *time.Time `json:"ban_until"`
	StateChangedAt time.Time  `json:"state_changed_at"`
}

func (q *Queries) HotstateProxiesByIDs(ctx context.Context, arg HotstateProxiesByIDsParams) ([]HotstateProxiesByIDsRow, error) {
	rows, err := q.db.Query(ctx, hotstateProxiesByIDs, arg.NamespaceID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HotstateProxiesByIDsRow{}
	for rows.Next() {
		var i HotstateProxiesByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Hkey,
			&i.State,
			&i.Kind,
			&i.Region,
			&i.Provider,
			&i.Tags,
			&i.MaxConcurrency,
			&i.UrlVersion,
			&i.CooldownUntil,
			&i.BanUntil,
			&i.StateChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hotstateProxiesPage = `-- name: HotstateProxiesPage :many
SELECT id, hkey, state, kind, region, provider, tags, max_concurrency, url_version, cooldown_until, ban_until,
       state_changed_at
FROM proxies
WHERE namespace_id = $1
  AND hkey > $2
ORDER BY hkey
LIMIT $3
`

type HotstateProxiesPageParams struct {
	NamespaceID string `json:"namespace_id"`
	AfterHkey   int64  `json:"after_hkey"`
	PageSize    int32  `json:"page_size"`
}

type HotstateProxiesPageRow struct {
	ID             string     `json:"id"`
	Hkey           int64      `json:"hkey"`
	State          string     `json:"state"`
	Kind           string     `json:"kind"`
	Region         string     `json:"region"`
	Provider       string     `json:"provider"`
	Tags           []string   `json:"tags"`
	MaxConcurrency int32      `json:"max_concurrency"`
	UrlVersion     int32      `json:"url_version"`
	CooldownUntil  *time.Time `json:"cooldown_until"`
	BanUntil       *time.Time `json:"ban_until"`
	StateChangedAt time.Time  `json:"state_changed_at"`
}

func (q *Queries) HotstateProxiesPage(ctx context.Context, arg HotstateProxiesPageParams) ([]HotstateProxiesPageRow, error) {
	rows, err := q.db.Query(ctx, hotstateProxiesPage, arg.NamespaceID, arg.AfterHkey, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HotstateProxiesPageRow{}
	for rows.Next() {
		var i HotstateProxiesPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Hkey,
			&i.State,
			&i.Kind,
			&i.Region,
			&i.Provider,
			&i.Tags,
			&i.MaxConcurrency,
			&i.UrlVersion,
			&i.CooldownUntil,
			&i.BanUntil,
			&i.StateChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hotstateProxyBindingsByProxyIDs = `-- name: HotstateProxyBindingsByProxyIDs :many
SELECT i.site_id, i.hkey AS identity_hkey, p.hkey AS proxy_hkey
FROM proxy_bindings b
JOIN identities i ON i.id = b.identity_id
JOIN proxies p ON p.id = b.proxy_id
WHERE b.proxy_id = ANY ($1::text[])
ORDER BY i.site_id, i.hkey
`

type HotstateProxyBindingsByProxyIDsRow struct {
	SiteID       string `json:"site_id"`
	IdentityHkey int64  `json:"identity_hkey"`
	ProxyHkey    int64  `json:"proxy_hkey"`
}

func (q *Queries) HotstateProxyBindingsByProxyIDs(ctx context.Context, proxyIds []string) ([]HotstateProxyBindingsByProxyIDsRow, error) {
	rows, err := q.db.Query(ctx, hotstateProxyBindingsByProxyIDs, proxyIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HotstateProxyBindingsByProxyIDsRow{}
	for rows.Next() {
		var i HotstateProxyBindingsByProxyIDsRow
		if err := rows.Scan(&i.SiteID, &i.IdentityHkey, &i.ProxyHkey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hotstateProxyIDsByHkeys = `-- name: HotstateProxyIDsByHkeys :many
SELECT hkey, id
FROM proxies
WHERE namespace_id = $1
  AND hkey = ANY ($2::bigint[])
`

type HotstateProxyIDsByHkeysParams struct {
	NamespaceID string  `json:"namespace_id"`
	Hkeys       []int64 `json:"hkeys"`
}

type HotstateProxyIDsByHkeysRow struct {
	Hkey int64  `json:"hkey"`
	ID   string `json:"id"`
}

func (q *Queries) HotstateProxyIDsByHkeys(ctx context.Context, arg HotstateProxyIDsByHkeysParams) ([]HotstateProxyIDsByHkeysRow, error) {
	rows, err := q.db.Query(ctx, hotstateProxyIDsByHkeys, arg.NamespaceID, arg.Hkeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HotstateProxyIDsByHkeysRow{}
	for rows.Next() {
		var i HotstateProxyIDsByHkeysRow
		if err := rows.Scan(&i.Hkey, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hotstateSiteGroupHkeys = `-- name: HotstateSiteGroupHkeys :many
SELECT hkey
FROM endpoint_groups
WHERE site_id = $1
ORDER BY hkey
`

func (q *Queries) HotstateSiteGroupHkeys(ctx context.Context, siteID string) ([]int64, error) {
	rows, err := q.db.Query(ctx, hotstateSiteGroupHkeys, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var hkey int64
		if err := rows.Scan(&hkey); err != nil {
			return nil, err
		}
		items = append(items, hkey)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hotstateSiteRef = `-- name: HotstateSiteRef :one

SELECT id, hkey, namespace_id, paused
FROM sites
WHERE id = $1
`

type HotstateSiteRefRow struct {
	ID          string `json:"id"`
	Hkey        int64  `json:"hkey"`
	NamespaceID string `json:"namespace_id"`
	Paused      bool   `json:"paused"`
}

// Queries of the hot-state synchronization layer (internal/hotstate). They
// load the PostgreSQL truth materialized into Redis (spec §5) and map compact
// hot-state keys back to entity IDs.
func (q *Queries) HotstateSiteRef(ctx context.Context, id string) (HotstateSiteRefRow, error) {
	row := q.db.QueryRow(ctx, hotstateSiteRef, id)
	var i HotstateSiteRefRow
	err := row.Scan(
		&i.ID,
		&i.Hkey,
		&i.NamespaceID,
		&i.Paused,
	)
	return i, err
}

const hotstateSnapshotIdentityEndpointPage = `-- name: HotstateSnapshotIdentityEndpointPage :many
SELECT s.subject_id,
       s.endpoint_group_id,
       i.hkey AS identity_hkey,
       g.hkey AS group_hkey,
       s.score,
       s.samples,
       s.consecutive_failures,
       s.last_failure_at,
       s.cooldown_until,
       s.reuse_until,
       s.last_used_at,
       s.updated_at
FROM hot_state_snapshots s
JOIN identities i ON i.id = s.subject_id AND i.site_id = s.site_id
JOIN endpoint_groups g ON g.id = s.endpoint_group_id AND g.site_id = s.site_id
WHERE s.site_id = $1
  AND s.subject = 'ie'
  AND i.state <> 'retired'
  AND (s.subject_id > $2::text
       OR (s.subject_id = $2::text AND s.endpoint_group_id > $3::text))
ORDER BY s.subject_id, s.endpoint_group_id
LIMIT $4
`

type HotstateSnapshotIdentityEndpointPageParams struct {
	SiteID         string `json:"site_id"`
	AfterSubjectID string `json:"after_subject_id"`
	AfterGroupID   string `json:"after_group_id"`
	PageSize       int32  `json:"page_size"`
}

type HotstateSnapshotIdentityEndpointPageRow struct {
	SubjectID           string     `json:"subject_id"`
	EndpointGroupID     string     `json:"endpoint_group_id"`
	IdentityHkey        int64      `json:"identity_hkey"`
	GroupHkey           int64      `json:"group_hkey"`
	Score               float64    `json:"score"`
	Samples             int32      `json:"samples"`
	ConsecutiveFailures int32      `json:"consecutive_failures"`
	LastFailureAt       *time.Time `json:"last_failure_at"`
	CooldownUntil       *time.Time `json:"cooldown_until"`
	ReuseUntil          *time.Time `json:"reuse_until"`
	LastUsedAt          *time.Time `json:"last_used_at"`
	UpdatedAt           time.Time  `json:"updated_at"`
}

func (q *Queries) HotstateSnapshotIdentityEndpointPage(ctx context.Context, arg HotstateSnapshotIdentityEndpointPageParams) ([]HotstateSnapshotIdentityEndpointPageRow, error) {
	rows, err := q.db.Query(ctx, hotstateSnapshotIdentityEndpointPage,
		arg.SiteID,
		arg.AfterSubjectID,
		arg.AfterGroupID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HotstateSnapshotIdentityEndpointPageRow{}
	for rows.Next() {
		var i HotstateSnapshotIdentityEndpointPageRow
		if err := rows.Scan(
			&i.SubjectID,
			&i.EndpointGroupID,
			&i.IdentityHkey,
			&i.GroupHkey,
			&i.Score,
			&i.Samples,
			&i.ConsecutiveFailures,
			&i.LastFailureAt,
			&i.CooldownUntil,
			&i.ReuseUntil,
			&i.LastUsedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hotstateSnapshotIdentityGlobalPage = `-- name: HotstateSnapshotIdentityGlobalPage :many
SELECT s.subject_id,
       i.hkey AS identity_hkey,
       s.score,
       s.samples,
       s.cooldown_until,
       s.reuse_until,
       s.last_used_at,
       s.updated_at
FROM hot_state_snapshots s
JOIN identities i ON i.id = s.subject_id AND i.site_id = s.site_id
WHERE s.site_id = $1
  AND s.subject = 'ig'
  AND s.endpoint_group_id = ''
  AND i.state <> 'retired'
  AND s.subject_id > $2::text
ORDER BY s.subject_id
LIMIT $3
`

type HotstateSnapshotIdentityGlobalPageParams struct {
	SiteID         string `json:"site_id"`
	AfterSubjectID string `json:"after_subject_id"`
	PageSize       int32  `json:"page_size"`
}

type HotstateSnapshotIdentityGlobalPageRow struct {
	SubjectID     string     `json:"subject_id"`
	IdentityHkey  int64      `json:"identity_hkey"`
	Score         float64    `json:"score"`
	Samples       int32      `json:"samples"`
	CooldownUntil *time.Time `json:"cooldown_until"`
	ReuseUntil    *time.Time `json:"reuse_until"`
	LastUsedAt    *time.Time `json:"last_used_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
}

func (q *Queries) HotstateSnapshotIdentityGlobalPage(ctx context.Context, arg HotstateSnapshotIdentityGlobalPageParams) ([]HotstateSnapshotIdentityGlobalPageRow, error) {
	rows, err := q.db.Query(ctx, hotstateSnapshotIdentityGlobalPage, arg.SiteID, arg.AfterSubjectID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HotstateSnapshotIdentityGlobalPageRow{}
	for rows.Next() {
		var i HotstateSnapshotIdentityGlobalPageRow
		if err := rows.Scan(
			&i.SubjectID,
			&i.IdentityHkey,
			&i.Score,
			&i.Samples,
			&i.CooldownUntil,
			&i.ReuseUntil,
			&i.LastUsedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hotstateSnapshotProxyPage = `-- name: HotstateSnapshotProxyPage :many
SELECT s.subject_id,
       p.hkey AS proxy_hkey,
       s.score,
       s.samples,
       s.consecutive_failures,
       s.last_failure_at,
       s.cooldown_until,
       s.updated_at
FROM hot_state_snapshots s
JOIN sites st ON st.id = s.site_id
JOIN proxies p ON p.id = s.subject_id AND p.namespace_id = st.namespace_id
WHERE s.site_id = $1
  AND s.subject = 'ps'
  AND s.endpoint_group_id = ''
  AND s.subject_id > $2::text
ORDER BY s.subject_id
LIMIT $3
`

type HotstateSnapshotProxyPageParams struct {
	SiteID         string `json:"site_id"`
	AfterSubjectID string `json:"after_subject_id"`
	PageSize       int32  `json:"page_size"`
}

type HotstateSnapshotProxyPageRow struct {
	SubjectID           string     `json:"subject_id"`
	ProxyHkey           int64      `json:"proxy_hkey"`
	Score               float64    `json:"score"`
	Samples             int32      `json:"samples"`
	ConsecutiveFailures int32      `json:"consecutive_failures"`
	LastFailureAt       *time.Time `json:"last_failure_at"`
	CooldownUntil       *time.Time `json:"cooldown_until"`
	UpdatedAt           time.Time  `json:"updated_at"`
}

func (q *Queries) HotstateSnapshotProxyPage(ctx context.Context, arg HotstateSnapshotProxyPageParams) ([]HotstateSnapshotProxyPageRow, error) {
	rows, err := q.db.Query(ctx, hotstateSnapshotProxyPage, arg.SiteID, arg.AfterSubjectID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HotstateSnapshotProxyPageRow{}
	for rows.Next() {
		var i HotstateSnapshotProxyPageRow
		if err := rows.Scan(
			&i.SubjectID,
			&i.ProxyHkey,
			&i.Score,
			&i.Samples,
			&i.ConsecutiveFailures,
			&i.LastFailureAt,
			&i.CooldownUntil,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
